### ISSUE TITLE
[Request] melt should respect stringsAsFactors option for variable.factor

### ISSUE THREAD

**Issue by botanize** [Rdatatable/data.table#1030]
In my mind, I've already told R I don't want strings converted to factors by default, but I have to go out of my way to specify that in the melt function. It would be nice to have melt respect my preference.

**Comment by arunsrinivasan** [comment]
It is to be consistent with `reshape2::melt` so that code doesn't break if people just convert from data.frames to data.tables. 

This is why I provided an additional argument `variable.factor` with default `TRUE` (to be consistent with `reshape2`, once again). You can set that to `FALSE` for `variable` column to return a character.

I don't see another way out of this without breaking existing code for many users...

**Comment by m-dz** [comment]
Hi, just a comment, as I currently ran into similar issue: I am so used to (and thankful for!) the default behaviour of e.g. `fread` that I almost forgot about factors, and suddenly `melt` changes character values to them. This was quite surprising and took some time to spot! Maybe a message saying this is happening would be possible?

**Comment by franknarf1** [comment]
Maybe one way around it would be `variable.factor = getOption("datatable.melt.variable.factor")` defaulting to TRUE. Kind of makes sense to make that particular option available since it clashes with the rest of data.table's non-factor defaults; and I can't think of a way it would break existing code.

**Comment by jangorecki** [comment]
@franknarf1 option sounds fine but @m-dz comment is more about spotting the factor so option will generally not help on that.

**Comment by m-dz** [comment]
@franknarf1, @jangorecki is correct, the default, **"silent"**, converting to factor by `melt.data.table` was very confusing. Maybe a message with option to turn in off (by `datatable.melt.variable.factor.message`?) would be worth consideration?
