### ISSUE TITLE
fread fails if whitespace before first character

### ISSUE THREAD

**Issue by dpastoor** [Rdatatable/data.table#1035]
The program I use by default gives output like so:

```
" ITERATION    THETA1       THETA2"                
"            0  3.95527E+01  2.10651E+01"

```

I first tried with the stable version (1.9.4) and got the following error:

```
Expected sep (',') but new line, EOF (or other non printing character) ends field 1 on line 4 when detecting types:             0  3.95527E+01  2.10651E+01 
```

with the development version (1.9.5) I get the following error:

```
Not positioned correctly after testing format of header row. ch=' '
```

This seems like it would be resolved by #758 or #558 (variable whitespace delimiter)

but just wanted to give another example of a situation where fread currently fails and need to fall back to read.table(sep="") to get the table to read in properly

**Comment by GHarmata** [comment]
I am experiencing a similar problem; however, the R session completely aborts in 1.9.4, instead of giving a warning message.

Here is an example illustrating the format of dataset with which I am working:

```
"  22 4 6 4" 
"  34 22 34 5"
"  6 2 1 4"
```

Each row begins with two white spaces, but the separator for the rest of the values is a single white space.

In version 1.9.4, when I attempted to use fread() in RStudio with my much larger dataset, I received the following pop-up warning (and the application had to be restarted):

```
R Session Aborted
R encountered a fatal error. The session was terminated.
```

Using version 1.9.5, I instead received this error message:

```
Not positioned correctly after testing format of header row. ch=' '
```

**Comment by jaapwalhout** [comment]
I had the same problem. This works:
    df <- read.table("./data/train/X_train.txt")

but reading the same file with `fread` does not work and throws me an error:
```
> dt <- fread("./data/train/X_train.txt")
Error in fread("./data/train/X_train.txt") : 
  Not positioned correctly after testing format of header row. ch=' '
```

The file in question can be [downloaded from here](https://dl.dropboxusercontent.com/u/57047/X_train.txt) (66MB's).

**Comment by arunsrinivasan** [comment]
Fixed in devel. Please upgrade and test.

**Comment by jaapwalhout** [comment]
@arunsrinivasan Tested. It now works on the file I specified above.
