### ISSUE TITLE
Make `rbindlist` work on unnamed lists too

### ISSUE THREAD

**Issue by DavidArenburg** [Rdatatable/data.table#1036]
It also seems like the error message is a bit misleading. It should be something like *"Error in rbindlist(Res, idcol = "id") : Please name the objects within your list"*

```r
library(data.table) ; library(tidyr)
set.seed(123)
Res <- lapply(1:3, function(x) sample(10, x))

unnest(Res, "id")
#   id  x
# 1 X1  3
# 2 X2  8
# 3 X2  4
# 4 X3  9
# 5 X3 10
# 6 X3  1

rbindlist(Res, idcol = "id")
# Error in rbindlist(Res, idcol = "id") : 
#   Item 1 of list input is not a data.frame, data.table or list
```

**Comment by arunsrinivasan** [comment]
`rbindlist()` works with list (of lists), data.frames and data.tables, not with list of atomic types. `unnest` and `rbindlist` aren't equivalent. 

Even if `rbindlist` were to work here.. the expected result would be:

```R
#    V1 V2 V3
# 1:  3 NA NA
# 2:  8  4 NA
# 3:  9 10  1
```
when `fill=TRUE` and error otherwise.

**Comment by eantonya** [comment]
@arunsrinivasan I'm confused why that would be the result, and not same as this (if running without `idcol` argument):

```R
rbindlist(lapply(Res, function(x) as.data.table(x)))
#    x
#1:  3
#2:  8
#3:  4
#4:  9
#5: 10
#6:  1
```

**Comment by arunsrinivasan** [comment]
If you bind *atomic* vectors, then `rbind` would return the result I mention (ignoring the fill argument).

```R
x = list(1:2, 3:4)
do.call(rbind, x)
#      [,1] [,2]
# [1,]    1    2
# [2,]    3    4
```
If the desired result is what you show, then you should provide the input in that format.

**Comment by eantonya** [comment]
I think it's pretty clear that base does the wrong thing there. `data.frame`, `as.data.frame`, `matrix` and `as.matrix` all return a column vector when applied on `c(1:5)`.

**Comment by arunsrinivasan** [comment]
If I've a list of atomic vectors and I was told to `rbind` that list, I definitely won't be thinking of a result which has 1 column and n rows. That's just an `unlist()` operation.

What you propose is converting the atomic vector to a 1-column data.frame (with n-rows). What base R seems to do (conceptually) is to convert it to a 1-row data.frame (with n columns). Personally, I find base-R makes more sense.

**Comment by eantonya** [comment]
Well, my viewpoint is that `rbind` is an undefined operation for vectors, since they don't have a concept of a "row". So a vector needs to be converted into a matrix first, and I agree that a vector can be equivalently interpreted as either a column-matrix or a row-matrix, but none of the standard base functions conversions interpret vectors as row matrices (and actually in `data.table` we seem to prefer the column-matrices even if explicitly given a row-matrix, e.g. `data.table(a = 1:2)[, t(c(1:3)), by = a]`), so I don't see the rationale to converting to row-matrices except for the one you mentioned, that doing otherwise is equivalent to `unlist` (but why is that relevant?).

Anyway, regardless of your interpretation of `vector->matrix` for `rbind`, it would still be quite useful to have `rbindlist` support lists of atomic vectors imo (and maybe add an explicit param that would resolve the `vector` to `matrix` ambiguity).
