### ISSUE TITLE
tests.Rraw test indexing

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1134]
An internal feature request for alternative indexing new tests in tests.Rraw. The incremental numeric do not work bests in distributed development where multiple branches are likely to produce overlapping numerics.
`test` function could accept `num = '#1012.1'` then we could at least refer to issues.

**Comment by MichaelChirico** [comment]
As to tests done for things not related to specific issues, how about deciding a convention?

First proposal:

    function.feature/argument.number

e.g., current test 1658.1 could become `fwrite.quote.1`

**Comment by MichaelChirico** [comment]
@jangorecki I think we missed the boat on doing this... `tests.Rraw` has almost tripled in size since this issue was filed:

https://github.com/Rdatatable/data.table/blob/7a92ccee5731b19ec718a38242b9b6fa452b1a5d/inst/tests/tests.Rraw

(not to mention the other test suites for `froll`/etc)

Any hope of getting this done by now?

**Comment by jangorecki** [comment]
no hope, closing
