### ISSUE TITLE
Selective Insertions into a column

### ISSUE THREAD

**Issue by dataPulvurizer** [Rdatatable/data.table#1199]
Amended: This bug is relevant for data.table version 1.9.4. running on R version R version 3.2.0.

I would like to be able to selectively insert data into a column using notation DT[col1 == "x", col1 := "y"]. But there is a bug associated with this. Here is an illustrative example:

```
library(data.table)
dat <- data.table("col1" = sample(LETTERS[1:5], 100, T), "col2" = runif(100))
head(dat[col1 == "A",])
#   col1      col2
#1:    A 0.6280871
#2:    A 0.0452715
#3:    A 0.3910744
#4:    A 0.1749796
#5:    A 0.9016917
#6:    A 0.8591779

dat[col1 == "A", col1 := "Z"]
dat[col1 == "Z",]
# Empty data.table (0 rows) of 2 cols: col1,col2
dat[col1 == "A",]
# Empty data.table (0 rows) of 2 cols: col1,col2

head(dat[col1 == "Z" | col1 == "A",])
#    col1      col2
# 1:    Z 0.6280871
# 2:    Z 0.0452715
# 3:    Z 0.3910744
# 4:    Z 0.1749796
# 5:    Z 0.9016917
# 6:    Z 0.8591779

## Of course you can do the bizzaro
dat[dat[, col1 == "A"], col1 := "Z"]
## Which works but is unintuitive
```

**Comment by arunsrinivasan** [comment]
It's always essential to post the version of data.table you're using. Also, to check the NEWS and bugs that have been fixed, and test with the latest version (as detailed in the `Contributing.md` file).

This is most another likely due to an *auto indexing* bug, which has since then been fixed in `v1.9.5`. Unfortunately, the updated version is not yet on CRAN.

You've two options:

1. Update to the devel version, until this is pushed to CRAN (as v1.9.6).
2. Set `options(datatable.auto.index = FALSE)` to disable the feature, and keep using `1.9.4`.
