### ISSUE TITLE
[Question] ggvis and data.table issue

### ISSUE THREAD

**Issue by dselivanov** [Rdatatable/data.table#1285]
**ggvis** `layer_lines()` grouping works fine with `data.frame`, but not with `data.table`.
This is related to rstudio/ggvis#430.
How can I check whether it `data.table` (probably, bacause `data.table` claimed it only inherits from `data.frame` ) or `ggvis` issue?
Compare:

```
library(data.table)
library(ggvis)
mtcars %>% ggvis(~wt, ~mpg, stroke = ~as.character(gear)) %>%
  layer_points() %>% 
  layer_lines()
```

and

```
mtcars_dt <- as.data.table(mtcars)
mtcars_dt %>% ggvis(~wt, ~mpg, stroke = ~as.character(gear)) %>%
  layer_points() %>% 
  layer_lines()
```

**Comment by arunsrinivasan** [comment]
Strange, but I've no idea where the issue is. I tried to debug, and caught up in a maze of function cals.. and gave up after traversing through them for a while.

Is there a special way to debug through these many function calls?

**Comment by arunsrinivasan** [comment]
To reiterate, the answer is "I don't know as well".

**Comment by mattdowle** [comment]
Please @dselivanov can you include the error message as well in your report?  Otherwise you leave the onus on us to rurun the code and hope/expect that we get the same error that you did.  We might not for a variety of reasons.  Do you see how this has the potential to waste time?  I can't glance at this issue for example and maybe give an answer without running code,  because I *have* to startup R and reproduce the error before I see the error.   You could have just pasted it to save me time.

Please run with `options(datatable.verbose=TRUE)` and report the output.  There might be a message similar to 'data.table decided <x> is/isn't data.table aware'

**Comment by arunsrinivasan** [comment]
@mattdowle there's no error. There are no connecting lines with input object as data.table.

**Comment by mattdowle** [comment]
Wish that had been stated clearly up front.  Any clue from verbose mode?

**Comment by arunsrinivasan** [comment]
Here's the verbose output:

```r
# Detected that j uses these columns: gear 
# Assigning to all 32 rows
# Direct plonk of unnamed RHS, no copy.
# order optimisation is on, i changed from 'order(...)' to 'forder(DT, ...)'.
```

Nothing pops out..

**Comment by mattdowle** [comment]
Thanks.  Good info now.  Will come back to it.

**Comment by smartinsightsfromdata** [comment]
Not sure if this can help, but it seems that the following is rendered correctly:
```
mtcars_dt <- as.data.table(mtcars)
mtcars_dt %>% ggvis(~wt, ~mpg, stroke = ~as.character(gear)) %>%
  layer_points()
````

The problem stems from the fact that the last chunk: `%>% layer_lines()` is like not executed or ignored (as no layer_lines are generated).

**Comment by dselivanov** [comment]
@mattdowle , sorry, it was hard to add screenshots at that moment. Pics were exactly the same, @arunsrinivasan attached few posts above. Anything else I can do?

**Comment by dselivanov** [comment]
Cleanup - closing. Not sure what exactly has happened for last 2 years, but now it works fine :-)
