### ISSUE TITLE
text labels for months / weekdays

### ISSUE THREAD

**Issue by jaapwalhout** [Rdatatable/data.table#1286]
At this moment using `month(x)` stores the months as an integer. However, when I want to get the names of the months, I have to fall back to `months` from base R. An example borrowed from [this answer of me](http://stackoverflow.com/a/31927948/2204410) on StackOverflow.

The following code:

```
setDT(temp)[, lapply(.SD, mean), by=.(year(date), month(date))]
```

gives me:

```
   year month amount
1: 2011     2 42.610
2: 2011     3 23.195
3: 2011     4 61.891
```

In order to get the monthnames, I need:

```
setDT(temp)[,date:=as.IDate(date)][, lapply(.SD, mean), by=.(year(date), months(date))]
```

which gives:

```
   year   months amount
1: 2011 februari 42.610
2: 2011    maart 23.195
3: 2011    april 61.891
```

Wouldn't it be nice to get that same result with someting like this:

```
setDT(temp)[, lapply(.SD, mean), by=.(year(date), month(date, label=TRUE))]
```

In such an implementation the default behavior should off course be `label = FALSE` to preserve the speed of working with integers.

The same applies to the names of the weekdays.

Possibly related to [#750](https://github.com/Rdatatable/data.table/issues/750)

**Comment by DavidArenburg** [comment]
This one is actually a really easy one. I hate PRs but maybe someone's is up to it

```r
month <- function(x, label = FALSE){
  if(isTRUE(label)) return(months(as.POSIXct(x)))
  as.POSIXlt(x)$mon + 1L  
}

x <- c("2011-02-01", "2011-05-02", "2011-10-03")

month(x)
## [1]  2  5 10
month(x, label = TRUE)
## [1] "February" "May"  "October"
```

**Comment by jangorecki** [comment]
I would prefer to keep `month` return type integer. It is easy to manage on the user side. Should be even faster and easier using `month.name` R variable.
```r
temp <- structure(list(date = structure(1:6, .Label = c("2011-02-01", "2011-02-02", "2011-03-03", "2011-03-04", "2011-04-05", "2011-04-06"), class = "factor"), 
                       amount = c(1.67, 83.55, 24.4, 21.99, 98.882, 24.9)), 
                  .Names = c("date", "amount"), class = c("data.frame"), row.names = c(NA, -6L))
library(data.table)
setDT(temp)[, lapply(.SD, mean), by=.(year(date), months = month.name[month(date)])]
#    year   months amount
# 1: 2011 February 42.610
# 2: 2011    March 23.195
# 3: 2011    April 61.891
```

**Comment by MichaelChirico** [comment]
@jangorecki just checking, `month.name` is locale-specific?

**Comment by jangorecki** [comment]
@MichaelChirico AFAIR yes

**Comment by franknarf1** [comment]
I would like to see an option to get `wday` as an ordered factor, with levels determined per the locale.

I was doing something like `dcast(DT, id ~ wd)` and realized I needed to go back and factorize my `wday = weekdays(d)`. 

It may also make sense to have such a feature for `month`.

**Comment by ben-schwen** [comment]
As pointed out by help `?month.name` contains the month names in English while locale-specific months are available with `format`, `format(ISOdate(2000, 1:12, 1), "%B")`.

**Comment by MichaelChirico** [comment]
There was #6310 towards supporting this, but we are deciding now to just close this FR.

 - Having function returning different class/type depending on some arguments is not always ideal
 - If we return `character`, this becomes just a wrapper around `strftime()`/`format.Date()` functionality -- users can just use base instead
 - Returning a `factor()` with names in the "right" order would be kinda nice, but comes with a fair amount of maintenance overhead for days-of-the-week because different locales will want Monday vs. Sunday to be the first level.

To support that level of detail, we'd want this to be heavily requested feature, which appears not to be the case. Ultimately, a more specialized package may be more suitable, e.g. this would be a good {lubridate} FR.

{data.table} main focus for I{Date,Time} class is low-storage support for time/date columns that's not available elsewhere.
