### ISSUE TITLE
setnames doesn't work with parallel foreach

### ISSUE THREAD

**Issue by ziyadsaeed** [Rdatatable/data.table#1303]
setnames doesn't work when using parallel foreach. See code below as well as screenshot of the result.
using Windows 8,1 and Revolution R Open 3.2.1, data.table 1.9.4 as well as 1.9.5 checked out today August 31, 2015

```R
library("doParallel")
registerDoParallel(2)
library("foreach")
library("data.table")
DT1 <- data.table(mtcars)
DT2 <- copy(DT1)
lists <- list(list(data = DT1), list(data = DT2))
foreach(l = lists, .export = "setnames") %dopar% setnames(l$data, "mpg", "milespergallon")
lapply(lists, function(l) names(l$data)[1])
```
![setnames](https://cloud.githubusercontent.com/assets/12503225/9582090/c6dcb8be-501c-11e5-9352-98358bed33f1.png)

**Comment by jangorecki** [comment]
I believe it is due to parallel processing limitation which has to return updated data from the workers to your R session. Try below code. If it solves your issue you can close the ticket here, if not I think you can get better parallel related response on stackoverflow, just include good R parallel related tags.
```r
r = foreach(l = lists, .export = "setnames") %dopar% {setnames(l$data, "mpg", "milespergallon"); l}
lapply(r, function(l) names(l$data)[1])
# [[1]]
# [1] "milespergallon"
# 
# [[2]]
# [1] "milespergallon"
```

**Comment by ziyadsaeed** [comment]
thanks.
