### ISSUE TITLE
File-backed data.tables

### ISSUE THREAD

**Issue by zachmayer** [Rdatatable/data.table#1336]
[SFrames](https://dato.com/products/create/docs/generated/graphlab.SFrame.html) are graphlab create's version of data.frames, and have some [impressive performance benchmarks](http://blog.dato.com/interactively-analyzing-terabytes-of-data-using-graphlab-create) on single machines.

I'd really love to see something similar for data.table that could use disk rather than RAM to store the data.

**Comment by arunsrinivasan** [comment]
Agreed.

**Comment by zachmayer** [comment]
:+1:

**Comment by zachmayer** [comment]
@arunsrinivasan Any updates here?  It'd still be a useful feature to have.

**Comment by mbacou** [comment]
+1

**Comment by arunsrinivasan** [comment]
@zachmayer no updates yet, but would like to add to v2.0.0 milestone.. Will revisit soon. Thanks for the ping.

**Comment by clarkfitzg** [comment]
+1

**Comment by vors** [comment]
🙏

**Comment by jaapwalhout** [comment]
The links in the original post of @zachmayer are not valid anymore. The GitHub repo of Graphlab/Dato/Turi can be [found here](https://github.com/turi-code/SFrame). Because Graphlab/Dato/Turi has been acquired by Apple, this repo has been moved [to here](https://github.com/apple/turicreate). It looks like it has evolved into a library for the development of machine learning models.

In case above two links stop working, I've created a [fork in my own profile](https://github.com/jaapwalhout/SFrame).

**Comment by aquasync** [comment]
One potential implementation strategy is via R's custom allocator mechanism. I constructed a file-backed `data.table` with individual columns backed by mmap-d files based on the code [here](https://gist.github.com/s-u/6712c97ca74181f5a1a5).

See this [gist](https://gist.github.com/aquasync/20006038a6d06b63ba4f3402e87e3024), where I create the 2B row dataset (~75GB) from the benchmarks and run some aggregations on my laptop (16GB ram). There's many missing pieces that make this far from a user-friendly solution though. Among them: R's custom allocator is used for the entire array object, so there is an R implementation specific header prepended to the data; can't share even read-only between R sessions due to the former; can't hook data.table allocations for new objects (columns/indices) so they won't be memory-mapped; no support for real string columns; requires manual persistence of column attributes.

All those caveats aside, I've already found it to be quite useful when working with a large number of moderate sized datasets, where each is sequentially memory mapped, data.table is told they're already sorted (`attr(DT, 'order') = ...`) and then performing a "roll" join to extract data with a given lookback, such that the only the data needed for the binary search and the subsequent values needs to be read from disk.

**Comment by waynelapierre** [comment]
Any update on this? If this feature is planned to be included in data.table 2.0, when will be data.table 2.0 be released?

**Comment by jonekeat** [comment]
Is something similar to what @aquasync [proposed](https://github.com/Rdatatable/data.table/issues/1336#issuecomment-455975139) already implemented? I have tried to use [mmap](https://cran.r-project.org/web/packages/mmap/index.html) package to memory map each column in a list, then `setDT`, but it cannot work with `data.table` methods. I am looking for any alternatives before using databases/spark or rewrite into c/c++

**Comment by jangorecki** [comment]
@jonekeat disk.frame is possibly an alternative but I haven't tried it myself.

**Comment by GitHunter0** [comment]
> @jonekeat disk.frame is possibly an alternative but I haven't tried it myself.

`disk.frame` is the most promising R solution for this matter I've seen so far. It would be very interesting to see `data.table` and `disk.frame` contributors working together

**Comment by r2evans** [comment]
As a current-day workaround, what about the use of `arrow::open_dataset` and `dtplyr` or similar? The data is immutable so "saving" data would need to be an explicit step, but at least fast access to on-desk data should be feasible. (I recognize this does not fully address all likely use-cases for on-disk `data.table` operations.)

**Comment by tdhock** [comment]
This is currently out of scope https://github.com/Rdatatable/data.table/blob/master/GOVERNANCE.md#the-r-package and I don't think anyone has the time/interest/skill to implement, so I'm closing.

**Comment by r2evans** [comment]
I don't disagree, it's definitely big-scope. I offered my comment to illustrate alternative paths.

**Comment by MichaelChirico** [comment]
> This is currently out of scope https://github.com/Rdatatable/data.table/blob/master/GOVERNANCE.md#the-r-package and I don't think anyone has the time/interest/skill to implement, so I'm closing.

to clarify I'd be glad to have scope expanded for this high-demand FR, but as noted current maintainer core has no time/ability to support this. outside contributions (and commitment to ownership) welcome.
