### ISSUE TITLE
Bug: inner DT's levels are preferred in merge

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1340]
I am not 100% sure this is a bug, but it's certainly not what I would expect.

When we merge two tables on a `factor`-vs-`character`/`factor` column, the `level`s of the `factor` in the first are overwritten in the output. What's particularly confusing is that when we merge a `factor` to a `character`, the _order_ is that of the `character`, but the _type_ is still `factor`. Examples:

```r
require(data.table)
DT1 <- data.table(id = factor(1:3, levels = 3:1), var = 5:3) #when ordered, 3 is first
DT2 <- data.table(id = paste0(1:3), var2 = 8:10) #character ID
DT3 <- data.table(id = factor(1:3, levels = c(2, 1, 3)), var3 = 20:22)
```

When we merge 1 to 2:

```r
DT1[DT2, on = "id"][order(id)]
   id var var2
1:  1   5    8
2:  2   4    9
3:  3   3   10
DT1[DT2, on = "id"][ , class(id)]
[1] "factor"
```

When we merge 1 to 3:
```r
DT1[DT3, on = "id"][order(id)]
   id var var3
1:  2   4   21
2:  1   5   20
3:  3   3   22
```

I would expect the characteristics of the left `data.table` to reign supreme; the alternative _should_ be that the characteristics of the _right_ `data.table` reign supreme, but we don't have this either--we get the _order_ of the right `data.table` but the `type` of the left `data.table`. Rather confusing.

(this also happens when the tables are `key`ed.)

**Comment by arunsrinivasan** [comment]
For each row of `DT2`, we extract the matching rows in `DT1`.

In the first scenario, you input a character vector for `DT2$ID`. Since we perform joins as subsets, we do not modify `DT1$ID` to character type. Instead `DT2$ID` gets converted to `factor`. And those levels are `1,2,3` = in the result, as expected.

In the second scenario, again, the levels from `DT2` is preserved in result.

Perhaps, we need a warning that the levels aren't identical when they aren't? If you agree, could you file a new issue for that please? Thanks.
