### ISSUE TITLE
Time intervals integer data type IPeriod

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#1390]
New function to round `IDate` and `ITime` together, produces integer-stored period intervals including attributes for unit and amount of units within period. Also `origin` argument allows to store lower values on integer, so it is easy to have < 100k which according to `?IDateTime` gives additional speed up.
Some benchmark: [SO](http://stackoverflow.com/a/33137917/2490497).  
man online: https://jangorecki.github.io/drat/iperiod/

``` r
install.packages("data.table", repos = "https://jangorecki.github.io/drat/iperiod")
```

@tshort FYI

**Comment by jangorecki** [comment]
First benchmark looks promising, on tick data in 22M rows.
```r
# Unit: seconds
#  expr      min       lq     mean   median       uq      max neval
#   xts 6.916758 7.028135 7.267980 7.261469 7.507824 7.632221     4
#    dt 1.432376 1.435704 1.454868 1.446551 1.474032 1.493994     4
```
5x times speed-up: [gist](https://gist.github.com/jangorecki/12a6a219b203cddc9a34)

**Comment by jangorecki** [comment]
Once the #1391 will be resolved it can get even more speed-up. As below, but it currently it returns integer, not `IUnit` class integer.
```r
microbenchmark(times = 4L,
               xts = align.time(period.apply(xt, INDEX=endpoints(xt, "mins", 15), FUN=mean), 15*60),
               dt = dt[, iunit := round.IDateTime(idate, itime, "mins", 15L)
                       ][, .(junit = iunit[1L], price = mean(price)), .(iunit) # update once [data.table#1391](https://github.com/Rdatatable/data.table/issues/1391) solved
                         ][, junit := NULL
                           ][],
               dt2 = dt[, .(price = mean(price)),.(iunit = as.integer(round.IDateTime(idate, itime, "mins", 15L)))])
# Unit: milliseconds
#  expr       min        lq      mean    median        uq       max neval
#   xts 7349.1733 7361.7811 7536.1951 7468.8496 7710.6091 7857.9079     4
#    dt 1471.7809 1472.3348 1490.4924 1474.7741 1508.6500 1540.6405     4
#   dt2  683.8656  693.9473  705.6785  705.6185  717.4097  727.6115     4
```

**Comment by jangorecki** [comment]
Although there is some work already done, and significant speed up has been observed, I would close this one and redirect that functionality to https://github.com/lsilvest/nanoival package (@lsilvest). Haven't look into its internals yet so not sure how different it is from my work on interval type: https://github.com/Rdatatable/data.table/compare/master...jangorecki:iunit

**Comment by jangorecki** [comment]
@lsilvest I have seen recent development in nanotime but cannot find the implementation of period type that would correspond to mine implementation mentioned here. nanoival looks nice but its features has to compromise its performance. If user is interested in truncating POSIXct (or nanotime) to time intervals, like 1 hours, then what would be the fastest way to do it in nanotime?

**Comment by lsilvest** [comment]
`nanoival` is a different concept and cannot be used as a replacement for `IPeriod`. The main role of `nanoival` is to construct complex `nanotime` subsetting (and because of the set operations defined on `nanoival` it is possible to capture simultaneity quite nicely among other things).

From a quick look at the `IPeriod` examples, it seems it is mainly used for the concept of aggregation. My view is that aggregation is better seen as a mapping from one time series to another, so it's more intuitive to keep the original point in time type (e.g. `POSIXct` or `nanotime`) rather than creating a new one. 

In addition to aggregation the other very closely linked concept is alignment. @eddelbuettel and myself have envisioned further developments to the `nanotime` package for generalised aggregation and alignment (see the experimental package [dtts.utils](https://github.com/lsilvest/dtts.utils)).

I think we can provide something very similar to `IPeriod` with some of the code we already have, and it would be great to work with you to make sure we make `nanotime` as useful as possible when used with `data.table`.

I have created eddelbuettel/nanotime#64 to keep track of this enhancement.

**Comment by jangorecki** [comment]
@lsilvest Thanks. Great to hear that! looking forward for this functionality. Closing this issue then as it fits much better to nanotime package.

**Comment by joshuaulrich** [comment]
> First benchmark looks promising, on tick data in 22M rows.
> 
> ```r
> # Unit: seconds
> #  expr      min       lq     mean   median       uq      max neval
> #   xts 6.916758 7.028135 7.267980 7.261469 7.507824 7.632221     4
> #    dt 1.432376 1.435704 1.454868 1.446551 1.474032 1.493994     4
> ```

I know this was 5 years ago, but I'm curious what xts functionality you used here.  I'd really appreciate if you could give me the command to replicate these results. I'd like to see if there's a way to improve xts' performance.

**Comment by jangorecki** [comment]
@joshuaulrich I contacted GitHub support, hope they will recover my deleted gist where I kept that code
https://gist.github.com/jangorecki/12a6a219b203cddc9a34

**Comment by joshuaulrich** [comment]
Thanks, I appreciate it!  I would also really appreciate it if you mention me when you benchmark xts' performance.  I'm always looking for ways to make xts faster.

**Comment by jangorecki** [comment]
@joshuaulrich I got reply from GH support

> We only keep backups on our servers for a short period of time after they're deleted, so unfortunately we won't be able to restore this for you.

It turned out there is a script in https://stackoverflow.com/a/33137917/2490497

**Comment by joshuaulrich** [comment]
Thanks Jan, I really appreciate you taking the time to find that for me!

**Comment by lsilvest** [comment]
Tried out something similar to the Stackoverflow code, and I get different results, I suppose because of code changes since the original performance numbers. I find that `xts`, `shhhhi` and `IPeriod` are within the same ballpark. Here is the code I ran:
``` R
library(rbenchmark)
library(data.table)
library(xts)
library(nanotime)


shhhhi <- function(your.time){
    strptime("1970-01-01", "%Y-%m-%d", tz="UTC") + round(as.numeric(your.time)/900)*900
}

PLapointe <- function(a){
    as.POSIXlt(round(as.double(a)/(15*60))*(15*60),origin=(as.POSIXlt('1970-01-01')))
}

shhhhi_nanotime  <- function(your.time){
    nanotime("1970-01-01", tz="UTC") + round(as.integer64(unclass(your.time))/900e9)*900e9
}


dt <- fread("~/temp/.btceUSD.csv")

x = as.POSIXct(dt[[1L]], tz="UTC", origin="1970-01-01")
idt <- IDateTime(x)
idate <- idt$idate
itime <- idt$itime
nn  <- as.nanotime(x)

benchmark(
    shhhhi                = shhhhi(x),
    PLapointe             = PLapointe(x),
    xts                   = align.time(x, 15*60),
    ip                    = periodize(idate, itime, "mins", 15),
    "ip_posix"            = as.POSIXct(periodize(idate, itime, "mins", 15), tz="UTC"),
    "nanotime (period)"   = ceilingtogrid(nn, as.nanoperiod("00:15:00"), "UTC"),
    "nanotime (duration)" = ceilingtogrid(nn, as.nanoduration("00:15:00"), "UTC"),
    "nanotime (shhhhi)"   = shhhhi_nanotime(x),
    replications=10,
    columns = c("test", "replications", "elapsed", "relative"))

```
And here are the results I get:
```
                 test replications elapsed relative
4                  ip           10   6.009    1.086
5            ip_posix           10  11.571    2.091
7 nanotime (duration)           10   6.724    1.215
6   nanotime (period)           10   7.927    1.433
8   nanotime (shhhhi)           10  11.408    2.062
2           PLapointe           10  45.142    8.159
1              shhhhi           10   6.657    1.203
3                 xts           10   5.533    1.000
```

So `xts` has slightly better performance than `IPeriod` when the latter is not dealing with `POSIXct`. `xts` simply uses the modulo operator:
``` R
align.time.POSIXct <- function(x, n=60, ...) {
  if(n <= 0) stop("'n' must be positive")
  structure(unclass(x) + (n - unclass(x) %% n),class=c("POSIXct","POSIXt"))
}
```
whereas `IPeriod` uses a representation that is the number of units*amount since the origin (i.e. in this case the number of 15 minutes), and goes through one multiplication and one division similar to `shhhhi` but without the rounding:

``` R
    iunits_in_day = as.integer(iunits_in_day)
    idate_n = (unclass(x) - as.integer(as.Date(origin))) * iunits_in_day
    itime_n = unclass(itime) %/% secs_in_iunit
    as.IPeriod(idate_n + itime_n, unit, amount, origin, type)
```

The experimental version in `nanotime` has a different approach, and constructs a grid first and then aligns to that grid, thus paying a price for the grid construction, but this comes with some flexibility as it is able to handle an arbitrary aggregation length with days and months and timezone correctness when operating on a `nanoperiod`.

That said, I have reservations on all these functions and I will elaborate further in eddelbuettel/nanotime#64.
