### ISSUE TITLE
Reproducible crash in fread

### ISSUE THREAD

**Issue by qinjs** [Rdatatable/data.table#1464]
Reported On here:
http://stackoverflow.com/questions/34194984/fread-crash-when-reading-the-small-txt-file

**Comment by st-pasha** [comment]
This is a duplicate of #2194

**Comment by mattdowle** [comment]
Thanks @qinjs. Yes as Pasha linked to, file size is a multiple of 4096 and final row ends abruptly without a final newline. Tested your file works now. Not adding the file to test suite as the file size of this one is a bit bigger and this issue is now well covered by the other test files added in this fix.
