### ISSUE TITLE
While using it with SQL SERVER 2016 CTP3 getting error

### ISSUE THREAD

**Issue by creepystranger** [Rdatatable/data.table#1520]
Hi 

I am getting this error while running my R script "in data base"

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'chron'
Error: package or namespace load failed for 'data.table'

this could be an configuration issue in SQL SERVER but what could lead to this problem ?
btw I have the package chron installed but seems its ignoring this

**Comment by jangorecki** [comment]
I believe you should contact SQL Server support. They are just starting to integrate with R in sql server 2016 so I wouldn't expect that integration be production ready.  
When writing in this repo please read [Support page](https://github.com/Rdatatable/data.table/wiki/Support) first.  

Regards your problem...
`chron` package is a dependency of a data.table, install `chron`, then install `data.table`. Currently data.table doesn't have any other dependencies than `chron` so that should be enough.
If possible please report back how data.table did work inside SQL server, I'm quite interested about that. Thanks in advance.

**Comment by arunsrinivasan** [comment]
Try `install.packages("data.table", dependencies=TRUE)`.
