### ISSUE TITLE
FR: lapply + other columns: improving automatic handling of column names

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1604]
```
DT <- data.table(x = 1:5, y = 1:5, z = 6:10)

DT[ , c(list(x), lapply(.SD, `^`, 2)), .SDcols = c("y", "z")]
#    V1  y   z
#1:  1  1  36
#2:  2  4  49
#3:  3  9  64
#4:  4 16  81
#5:  5 25 100
```

Is conjugate to the approach without `.SD`:

```
DT[ , .(x, y^2, z^2)]
#    x V2  V3
#1: 1  1  36
#2: 2  4  49
#3: 3  9  64
#4: 4 16  81
#5: 5 25 100
```

Seems like it's clear in the first case that `V1` should be named `x` (fixed with `c(list(x=x, ...))`)

**Comment by arunsrinivasan** [comment]
possible dup of https://github.com/Rdatatable/data.table/issues/618

**Comment by MichaelChirico** [comment]
@arunsrinivasan certainly related, and the solution may be the same. But distinct from the user's side.

**Comment by jangorecki** [comment]
I would say the example in first post is fine, if one wants a named column then named list should be provided, not just `list(x)`.
`lapply` is another thing that we catch and optimize before evaluation, thus dynamic naming make sense.
So the preferred way to achieve what Michael asks for in first post should be
```r
DT <- data.table(x = 1:5, y = 1:5, z = 6:10)
DT[ , c(list(x = x), lapply(.SD, `^`, 2)), .SDcols = c("y", "z")]
```
I understand this issue is about naming of column `c(list(x), ...)`. Naming of `lapply` is in #2311. Thus closing, re-open if you strongly disagree about `list(x = x)` requirement in such cases.
