### ISSUE TITLE
foverlaps 

### ISSUE THREAD

**Issue by ywhuofu** [Rdatatable/data.table#1617]
I think for the generality, I need to illustrate my example by using `SQL` code. 

```
select * from dt1 left join dt2
on dt1.id=dt2.id 
and dt1.date between dt2.begdt and dt2.enddt
```

Currently,  foverlaps can only accept the second condition `dt1.date between dt2.begdt and dt2.enddt`, but how about the first (`dt1.id=dt2.id`)? To my understanding, currently `foverlaps` can only do the following:

```
dt1[, dummy:=date]
setkey(dt2, begdt, enddt)
foverlaps(dt2, dt1, by.x=c('date', 'dummy'), type='within')
```

Is there anyway to add the condition to join on `id` as well?

**Comment by jangorecki** [comment]
Did you read `?foverlaps`?

**Comment by ywhuofu** [comment]
@jangorecki  I did read it. I don't know what I've missed. my data.table is 1.9.6.

**Comment by jangorecki** [comment]
@ywhuofu from manual in 1.9.7

`by.x, by.y` arguments:

> A vector of column names (or numbers) to compute the overlap joins. The **last two columns** in both by.x and by.y should each correspond to the start and end interval columns in x and y respectively. And the start column should always be <= end column. If x is keyed, by.x is equal to key(x), else key(y). by.y defaults to key(y).

Only last to columns can be used for your *between* case, arbitrary number of leading columns (except the last two) will be used for equi join condition, exactly as you need.

Here you can find **temporarily hosted** manual for 1.9.7 for `foverlaps`: http://jangorecki.gitlab.io/data.table/split/html/foverlaps.html

Let me know if it didn't help you to solve your case, otherwise feel free to close issue.

**Comment by arunsrinivasan** [comment]
@ywhuofu, at the time `foverlaps()` was written, we did not really think about it being used for *range joins* as well. It was designed for *interval joins*. Hence the roundabout way for creating a dummy column to create interval.

This Q has come up quite frequently on SO that we wanted to construct the column internally automatically for range joins, so that user doesn't have to create them. I think there's a FR somewhere for this.

However, we're now in the process of implementing more complete non-equi joins, #1452 (you've commented there already). With that done, this could become easier with `[.data.table` syntax as follows:

```r
# no need to set keys even!
dt1[dt2, on=.(id, x.date >= i.begdate, x.date <= i.enddate)]
```

**Comment by ywhuofu** [comment]
@arunsrinivasan  this is awesome! As you can see, I've bounced around on this issue for a while. Unfortunately, I am capable of contributing on coding...
