### ISSUE TITLE
"interesting" side effect of assignment by reference

### ISSUE THREAD

**Issue by zuoliang** [Rdatatable/data.table#1693]
I noted an *interesting* side effect of assignment by reference operation of data.table. 

Sample code:

```{r}
require(data.table)
DT = data.table(a=1:2, b=3:4)
varnames = names(DT)
print(address(DT))
print(varnames)
DT[,c:=5:6]
print(address(DT))
print(varnames)
DT$d = 7:8
print(address(DT))
print(varnames)
```
The first `print(varnames)` generates output:

> [1] "a" "b"

The second `print(varnames)` generates output:

> [1] "a" "b" "c"

as if the `varnames` is also updated by adding one column to `DT`.

The third `print(varnames)` generates output:

> [1] "a" "b" "c"

without updating `varnames` even though one column is added to `DT`.

By checking `address(DT)` before the three print expressions, it can be noted that the address of `DT` doesn't change after `DT[, c:=5:6]`, but does change after `DT$d = 7:8`.  This partly explain the changes of `varnames`.

However, we cannot assume that *assignment by reference* will keep updating `varnames`, as demonstrated in the following sample code:

```{r}
size = 100
DT = data.table(a=1:2, b=3:4)
varnames = names(DT)
for (x in paste('X', 1:size, sep='')) {
  oldnames = copy(varnames)
  DT[,`:=`(x, 1:2), with=FALSE]
  print(address(DT))
  if(length(oldnames) == length(varnames)) print(varnames)
}
```

In my machine (R version 3.2.5, data.table version 1.9.6),  after adding 98 new columns, address of `DT` changed, and `varnames` stopped updating.

But I guess this is an issue more to R itself than to data.table, as more discussion in

[http://adv-r.had.co.nz/memory.html#modification](http://adv-r.had.co.nz/memory.html#modification)

**Comment by arunsrinivasan** [comment]
This is quite a well known issue. See [this SO post](http://stackoverflow.com/a/15913648/559784). Also see the *Reference Semantics* vignette from the [Getting Started](https://github.com/Rdatatable/data.table/wiki/Getting-started) page, where this is also explained.

I can't go through all the details here, but it happens because R's *copy on write*. The first assignment step `varnames = names(DT)` does not actually copy `varnames`. It points to the same location as `names(DT)`. Then by updating `DT` by reference, `varnames` simply gets updated. Using `copy()` *deep copies `varnames` and during the assignment step is therefore containing an entirely new copy of `DT`'s names in memory.

Unfortunately `DT$d = 7:8` doesn't help your case, because it *shallow copies* the data.table, so that it can allocate an extra column `d` to add in the value `7:8`. R used to deep copy the entire data.table here (hence the `:=` syntax to begin with). Here, the address changes, but it's a shallow copy. Since R doesn't have a way of letting us know clearly, it's hard to tell what kind of copy has happened without having a relatively large data.table and measuring the time it takes, IIUC.

[This](http://stackoverflow.com/a/23393859/559784), [this](http://stackoverflow.com/a/23911746/559784) and perhaps [this](http://stackoverflow.com/a/25962445/559784) SO post could probably be of some help.
