### ISSUE TITLE
FR: allow natural syntax for semi-anti-joins

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#1799]
I posed this as an [SO Q](http://stackoverflow.com/questions/35191486/performing-a-semi-anti-join-in-binary-search) a while back; I still think it'd be a useful feature to see implemented for clarity of code.

Example:

```
DT <- data.table(a = rep(LETTERS, each = 10), id = rep(1:10, 26), key = c("a", "id"))
#desired syntax
DT[.(!"A", !3:4)]
#equivalent current syntax
DT[CJ(setdiff(unique(a), "A"), setdiff(unique(id), 3:4))]
```

**Comment by jangorecki** [comment]
I think we first need to have `!=` operator (and `!(a%in%b)`) for non-equi join, then it could be processed fast. Currently it may be better to use just `i = a!="A" & !(id %in% 3:4)` instead of proposed `CJ` syntax which won't scale in memory. Of course it depends on the data, but better to wait using vector scan than get a memory issues and swapping.

**Comment by arunsrinivasan** [comment]
Agree with Jan. This'll become more straightforward when `!=` is added to non-equi joins. Have added to #1801.
