### ISSUE TITLE
foverlaps does not returned expected result

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#1814]
Hey @arunsrinivasan thanks for your great work on foverlaps, I use it all the time.

I ran into an issue today, not sure if this is a bug or not. When I do foverlaps(dt.keyed.on.integer, dt.keyed.on.numeric, nomatch=0L) I don't get the expected number of rows back, if the numbers I am using are large enough. 

The example below does not work:

```r
data.vec <- c(87, 1e2, 1e3, 1e4, 1e5, 263169)
data.dt <- data.table(data=as.integer(data.vec))
data.dt[, data0 := data]
n.edge <- 11
edge.vec <- 10^seq(log10(min(data.vec)), log10(max(data.vec)), l=n.edge)
window.dt <- data.table(min.data=edge.vec[-n.edge], max.data=edge.vec[-1])
setkey(window.dt, min.data, max.data)
setkey(data.dt, data, data0)
over.dt <- foverlaps(data.dt, window.dt, nomatch=0L)
stopifnot(nrow(over.dt)==nrow(data.dt))
```

I got 

```
> stopifnot(nrow(over.dt)==nrow(data.dt))
Error: nrow(over.dt) == nrow(data.dt) is not TRUE
> over.dt
     min.data    max.data   data  data0
1:    87.0000    193.9058     87     87
2:    87.0000    193.9058    100    100
3:   963.2386   2146.8685   1000   1000
4:  4784.9455  10664.6974  10000  10000
5: 52977.5213 118076.4214 100000 100000
> data.dt
     data  data0
1:     87     87
2:    100    100
3:   1000   1000
4:  10000  10000
5: 100000 100000
6: 263169 263169
> 
```

If I reduce the value of the largest int, say `data.vec <- c(87, 100)` then I do get the right answer:

```
> stopifnot(nrow(over.dt)==nrow(data.dt))
> over.dt
   min.data  max.data data data0
1: 87.00000  88.22006   87    87
2: 98.61703 100.00000  100   100
> data.dt
   data data0
1:   87    87
2:  100   100
> 
```

**Comment by MichaelChirico** [comment]
Have you tried using `integer64`?

**Comment by tdhock** [comment]
no

**Comment by arunsrinivasan** [comment]
Please provide the version number at all times. I'm guessing this is in devel v1.9.7.

It's very likely due to item 32 under `Notes` section under [NEWS](https://github.com/Rdatatable/data.table/blob/master/NEWS.md). Also see [this SO post](http://stackoverflow.com/q/37625189/559784). We don't use any internal mechanisms for dealing with limitations in floating point numbers anymore. 

```r
sprintf("%.21f", as.numeric(data.dt$data[6]))
# [1] "263169.000000000000000000000"
sprintf("%.21f", window.dt$max.data[10])
# [1] "263168.999999999941792339087"
```

Obviously the 1st one is not inside the 2nd one. You're free to use `?setNumericRounding` (which is the only method we provide) which will round off the last 2 bytes off the numeric value and is embedded in `foverlaps`' implementation.

If you've a better way, please feel free to let us know, or even provide a PR. Thresholding with an arbitrary value is [not a solution](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/).

---

Note that the above can be done using the new non-equi joins feature as well:

```r
data.vec <- c(87, 1e2, 1e3, 1e4, 1e5, 263169)
data.dt <- data.table(data=as.integer(data.vec))

n.edge <- 11
edge.vec <- 10^seq(log10(min(data.vec)), log10(max(data.vec)), l=n.edge)
window.dt <- data.table(min.data=edge.vec[-n.edge], max.data=edge.vec[-1])

window.dt[data.dt, .(x.min.data, x.max.data, data), on=.(min.data<=data, max.data>=data)]
#    x.min.data  x.max.data   data
# 1:    87.0000    193.9058     87
# 2:    87.0000    193.9058    100
# 3:   963.2386   2146.8685   1000
# 4:  4784.9455  10664.6974  10000
# 5: 52977.5213 118076.4214 100000
# 6:         NA          NA 263169

# also check out ?"%inrange%"
```

although the same mismatch will occur due to the same problem.

**Comment by tdhock** [comment]
sorry I did not report the version number, but I did try it on the most recent github version

I guess that is sensible that you assume that users can deal with their own numeric issues. I found my own workaround.

however it may be useful to add a warning "you are doing a join of integer on numeric, you may get un-intended results" or something like that. That would have helped me identify the problem and solution faster.

**Comment by arunsrinivasan** [comment]
No worries. Glad it's on the devel version.

On warning, it's really no different from a normal comparison operation you'd do, for e.g., on a subset:

```r
data.dt[data > window.dt$max.data[6]]
#      data  data0
# 1: 100000 100000
# 2: 263169 263169
```

This is the nature of computations on floating point numbers. I don't think we should warn here.. and joins are no different.

**Comment by tdhock** [comment]
ok, that sounds reasonable, sorry for all the trouble

have a nice day
