### ISSUE TITLE
Bumping column from INT to STR when using integer64 = 'character' option

### ISSUE THREAD

**Issue by BlindApe** [Rdatatable/data.table#1872]
At last I find the origin of the problem I wrote in #1790

require(data.table)
dtb <- data.table('c1' = c(44, 81, 44, 45, 66, 66, 85, 100, 84, 103, 66, 85 ,101.5, 85, 96) , 'c2' = rep(1234567891234567, 15), 'c3' = rep(2, 15))
write.csv(dtb, file = 'data.csv', row.names = FALSE)
dtb <- fread('data.csv', verbose = TRUE, integer64 = 'character')
sapply(dtb, class)
dtb <- fread('data.csv', verbose = TRUE)
sapply(dtb, class)

The problem is when you use integer64 = 'character', then INT is converted to STR instead of REAL.

Seams the INT -> REAL conversion has a internal step to INT64 (!?):

Bumping column 1 from INT to INT64 on data row 13, field contains '101.5'
Bumping column 1 from INT64 to REAL on data row 13, field contains '101.5'

and when we use integer64 = 'character' the REAL conversion isn't reached.

**Comment by smouksassi** [comment]
Swipe typed from Blackberry.                                                                                                                                                                                                                From: Blind ApeSent: Sunday, October 9, 2016 13:45To: Rdatatable/data.tableReply To: Rdatatable/data.tableSubject: [Rdatatable/data.table] Bumping column from INT to STR when using integer64 = 'character' option (#1872)At least I find the origin of the problem I wrote in #1790

require(data.table)
dtb <- data.table('c1' = c(44, 81, 44, 45, 66, 66, 85, 100, 84, 103, 66, 85 ,101.5, 85, 96) , 'c2' = rep(1234567891234567, 15), 'c3' = rep(2, 15))
write.csv(dtb, file = 'data.csv', row.names = FALSE)
dtb <- fread('data.csv', verbose = TRUE, integer64 = 'character')
sapply(dtb, class)
dtb <- fread('data.csv', verbose = TRUE)
sapply(dtb, class)

The problem is when you use integer64 = 'character', then INT is converted to STR instead of REAL.

Seams the INT -> REAL conversion has a internal step to INT64 (!?):

Bumping column 1 from INT to INT64 on data row 13, field contains '101.5'
Bumping column 1 from INT64 to REAL on data row 13, field contains '101.5'

and when we use integer64 = 'character' the REAL conversion isn't reached.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Rdatatable/data.table","title":"Rdatatable/data.table","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Rdatatable/data.table"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Bumping column from INT to STR when using integer64 = 'character' option (#1872)"}],"action":{"name":"View Issue","url":"https://github.com/Rdatatable/data.table/issues/1872"}}}

**Comment by st-pasha** [comment]
In the latest dev version of data.table, I get the following:
```
> dtb1 <- fread('data.csv', integer64 = 'character')
> dtb2 <- fread('data.csv')
> sapply(dtb1, class)
         c1          c2          c3 
  "numeric" "character"   "integer" 
> sapply(dtb2, class)
         c1          c2          c3 
  "numeric" "integer64"   "integer" 
```
so the problem no longer exists.
