### ISSUE TITLE
setDT and setkey(v) not working with pipes

### ISSUE THREAD

**Issue by ctbrown** [Rdatatable/data.table#1894]
`setDT` and `setkey` do not seem to work as with `margrittr `or `pipeR `as expected:

```
library(magrittr)  # or library(pipeR)
library(data.table)

df <- data.frame( letters=letters[1:5], numbers = 1:5 )  
df %>% setDT( key="letters" )
key(df)      # NULL

df <- data.frame( letters=letters[1:5], numbers = 1:5 )  
df %>% setDT() %>% setkey(letters)
key(df)      # NULL
```

The setting of the keys are not respected.  But if we add an additional assignment they are, e.g. :

```
df <- data.frame( letters=letters[1:5], numbers = 1:5 )  
df <- df %>% setDT( key="letters" )
key(df)      # letters
```

It is not clear why the assignment in the second line above is required to have the key recognized.  This is highly problematic because it does not setkey does not work in data flows in which keys need to be set.

**Comment by franknarf1** [comment]
Huh, that's odd. Also that this works:

    library(magrittr)
    library(data.table)

    df <- data.frame( letters=letters[1:5], numbers = 1:5 )  
    df %>% setDT
    df %>% setkey(letters)
    key(df)
    # "letters"

**Comment by ctbrown** [comment]
@franknarf1, I noticed that as well. I don't think that this is a data.table problem, per se, Your example also works with pipeR. 

```
df <- data.frame( letters=letters[1:5], numbers = 1:5 )
df %>>% setDT
df %>>% setkey(letters)
key(df)
[1] "letters"
```

**Comment by sz-cgt** [comment]
@ctbrown I think you need to re-read how %>% works.  Values are only ever passed to the right.

In your example, the results of the `setDT()` are never saved back to `df` so you `keys(df)` fails. Try `str(df)` or `class(df)` and you'll see that you do not have a data.table.

    df %>% setDT() %>% setkey(letters) %>% keys()

will have the keys you expect.

Either use the `%<>%` operator or assign the result of the pipe to something.

**Comment by franknarf1** [comment]
@sz-cgt The class of `df` is changed in your example because `df` _was_ passed by reference, not by value. The problem is that magrittr insists on returning a value, contrary to how the `set*` functions were written. 

    library(data.table)

    df1 <- data.frame( letters=letters[1:5], numbers = 1:5 ) 
    z1 = setDT(df1)

    df2 <- data.frame( letters=letters[1:5], numbers = 1:5 ) 
    z2 = df2 %>% setDT()

    address(df1) == address(z1) # TRUE
    address(df2) == address(z2) # FALSE

So it may come down to magrittr not wanting to play nice with return-reference functions, or just an oversight. Either way, seems like their problem.

Btw, the function is `key`, not `keys`, at least in my version of data.table.

**Comment by sz-cgt** [comment]
Given it's written in R, magrittr can't treat pass by reference functions differently.  It has no way of knowing which functions are pass by reference vs pass by value.

That said, this works as expected

```
set.seed(1)
dt = data.table(colA = 1:10, colB = letters[runif(10, 1, 26)])
dt[(colA % 2) == 1, colC := 11:15] %>% .[is.na(colC), colD := 'y'] %>% setnames(c('w', 'x', 'y', 'z') %>% setkey(x)
str(dt)
Classes ‘data.table’ and 'data.frame':	10 obs. of  4 variables:
 $ w: int  10 5 1 2 3 9 8 4 6 7
 $ x: chr  "b" "f" "g" "j" ...
 $ y: int  NA 13 11 NA 12 15 NA NA NA 14
 $ z: chr  "y" NA NA "y" ...
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, "sorted")= chr "x"
```

PS; typo fixed.

**Comment by ctbrown** [comment]
I concur with that this is probably not a _magrittr_ problem for two reasons:

- It is likely easier handled by DT (just a hunch)
- It fits the MO of DT to be compatible with data.frames as much as possible.

@sz-cgt, 

The reason the provided example works as expected is that the `dt` object is already a `data.table`.  This is similar to what @franknarf1 pointed out ealier in the thread.  Here is a minimal working example that captures your point.:

```
dt <- data.table( letters=letters[1:5], numbers = 1:5 )  
dt %>% setkey(letters)
key(dt)      # "letters"
```

This is pretty much the same as:

```
df <- data.frame( letters=letters[1:5], numbers = 1:5 )  
df %>% setDT 
df %>% setkey(letters)
key(df)      # "letters"
```

What is curious is that the single pipes also work:

```
df <- data.frame( letters=letters[1:5], numbers = 1:5 )   %>% setDT( key="letters" )
key(df)      # "letters"

df <- data.frame( letters=letters[1:5], numbers = 1:5 )  %>% setDT() %>% setkey(letters)
key(df)      # "letters"
```

This demonstrates what a mess this really is. Until a fix is proposed and added, I think following @franknarf1 observation is probably the best practice ... do not make setDT as part of a pipe.  Always define a data table whether by `setDT` or `data.table` in its own statement.

**Comment by sz-cgt** [comment]
A final thought (cause I was off for Thanksgiving)...

It’s not actually a mess.  There is no conceptual difference between

`df <- data.frame( letters=letters[1:5], numbers = 1:5 )  %>% setDT() %>% setkey(letters)
`

and

`df <- setkey(setDT(data.frame( letters=letters[1:5], numbers = 1:5 )))
`

The assignment captures the result of the expression and saves if for future use.

Where things do become messy is when you mix two different forms of non-standard evaluation (NSE), as your original example did.  The short answer is “don’t do that” :-)

For proof see this:

```
> df = data.frame(x=1:5)
> address(df)
[1] "0x1227f8d8"
> setDT(df)
> address(df)
[1] "0x125da240"
```

Clearly, `setDT()` created a new physical object when it converted the original data frame.  It works however because I gave it a symbol, `df`, to assign the new object to.

In your original example, the object is passed anonymously by value, so there's no symbol for `setDT()` to save the new result to.  Hence the `keys()` fails because the value of `df` is untouched by the sequence of operations.

The example @franknarf1  gave using pipeR worked because it uses it's own NSE that does carry forward the symbols, or at least treats a bare symbol at the leftmost end of a expression as having an implied assignment operation involved.  Magrittr will do exactly the same thing if you use the `%<>%` operator instead of `%>%` in your original example.

```
> df = data.frame(x=1:5)
> df %<>% setDT() %>% setkey()
> key(df)
[1] "x"

```

**Comment by franknarf1** [comment]
> `setDT()` created a new physical object when it converted the original data frame. It works however because I gave it a symbol, `df`, to assign the new object to.

@sz-cgt  I think I'm missing something still.

    library(magrittr)
    list(x = 1) %T>% { print(address(.)) } %>% setDF %>% { print(address(.)) }
    # [1] "000000000622D0A8"
    # [1] "000000000622D0A8"

Here, using `setDF` but no symbol other  than `.`, I see that the address doesn't change. 

Maybe there's just a bug in `setDT`? It shouldn't change the address since it's modifying by reference, according to the docs:

> From `?setDT`: The `setDT` function takes care of this issue by allowing to convert lists - both named and unnamed lists and data.frames by reference instead. That is, the input object is modified in place, no copy is being made.
