### ISSUE TITLE
IDateTime fails on POSIXct without tzone.

### ISSUE THREAD

**Issue by lbilli** [Rdatatable/data.table#1973]
The function IDateTime generates an error when applied to POSIXct values without tzone attribute:

    library(data.table)
    IDateTime(Sys.time())
    # Error in if (tz == "UTC") { : argument is of length zero

Versions
R: 3.3.2
data.table: 1.10.0 and latest 1.10.1

**Comment by MichaelChirico** [comment]
This almost feels like an R bug more than a `data.table` bug.

It seems like by default a `POSIXct` object is supposed to have non-`NULL` `"tzone"` attribute:

```
attr(as.POSIXct('2017-03-17 00:00:00'), 'tzone')
#[1] ""
```

But this isn't the case for `Sys.time()`:

```
attr(Sys.time(), 'tzone')
# NULL
```

There's something going on with lazy evaluation that's causing the discrepancy between

```
IDateTime(Sys.time())
```

> Error in `if (tz == "UTC") {` : argument is of length zero

and

```
x = Sys.time()
data.table(idate = as.IDate(x), itime = as.ITime(x))
#         idate    itime
# 1: 2017-03-17 16:28:10
```

(this is an unexpected error because `IDateTime.default` is precisely the above):

```
data.table:::IDateTime.default
# function (x, ...) 
# {
#     data.table(idate = as.IDate(x), itime = as.ITime(x))
# }
```

I'm not sure when `Sys.time()` picks up a `"tzone"` attribute such that the latter approach works...
