### ISSUE TITLE
Extend 2 billion row benchmarks e.g. memory usage, sorting, joining, by-reference

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#2]
We've currently gone to 2E9 rows (the 32bit index limit) with 9 columns (100GB).  See benchmarks page on wiki.

Ideally it would be great to compare **all** available tools that are either specifically developed for large in-memory data manipulation or are capable of handling data at these sizes much better than base. Of course base-R should also be included, typically as control.

Aspect of benchmarking should be to highlight not just _run time_ (speed), but also _memory usage_. The sorting/ordering by reference, _sub-assignment_ by reference etc.. features, for example, at this data size should display quite clearly on speed and memory gains attainable.

**Comment by arunsrinivasan** [comment]
Figured `cgmemtime` out. Quite straightforward. Just need some time to run through grouping/joins/reshaping benchmarks.

**Comment by jangorecki** [comment]
I would like to close this one as it is already epic, and will be epic for a long time, due to broad scope defined here.
Work on benchmarks has been shifted to a dedicated h2o project https://github.com/h2oai/db-benchmark and related issues are:
- memory: https://github.com/h2oai/db-benchmark/issues/9
- join: https://github.com/h2oai/db-benchmark/issues/18
- sort: https://github.com/h2oai/db-benchmark/issues/61
- by reference ops: https://github.com/h2oai/db-benchmark/issues/62
