### ISSUE TITLE
Strange error with fread

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#2108]
What's the meaning of the following error?

```
Error in fread("myfile.csv", encoding = "UTF-8", stringsAsFactors = F,  : 
  Jump 0 did not end exactly where jump 1 found its first good line start: prevEnd(0000000012E86135)<<160701006396,GMGM350562911015,5/22/1935,12/31/2006>> != thisStart(prevEnd+375628)<<160701007085,GNPR331268904013,12/28/1933,12/31/200>>
```

**Comment by st-pasha** [comment]
This is an internal fread's error: multiple threads were reading different chunks of the input file in parallel, and then somehow those chunks were found to be either overlapping or having a gap between them. 
This error should not normally occur. If you have a reproducible example of a file where it does, then please share the file so that the chunk detection logic can be improved.
