### ISSUE TITLE
Update section g in intro vignette regarding with=FALSE

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2147]
with=FALSE is no longer needed for those examples and it's now much easier.

**Comment by mattdowle** [comment]
Thanks @MichaelChirico!  That edit was great.

**Comment by MichaelChirico** [comment]
@mattdowle doing what I can! One thing that I thought might be useful but which I don't have solidly myself is when to use `with = FALSE` vs. `..` now.

**Comment by arunsrinivasan** [comment]
Is there a reason this issue remains open?

@MichaelChirico would you mind updating the vignette in the Getting Started page under Wiki as well?

**Comment by MichaelChirico** [comment]
I'll put it on my list w a few other things.

@arunsrinivasan long time no see! welcome back! thanks for doing some housework/tidying :stuck_out_tongue:

**Comment by MichaelChirico** [comment]
@arunsrinivasan which document are you referring to? I only see [Introduction to `data.table`](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) linked from the [Getting Started](https://github.com/Rdatatable/data.table/wiki/Getting-started) wiki. Since that link pointing to CRAN, I think it will be updated automatically with a new push to CRAN.

**Comment by MichaelChirico** [comment]
I don't see a compiled version in the repository where we could just point to the HTML for now.... I guess it's created within CRAN.

**Comment by mattdowle** [comment]
Yes this looks closed.  Thanks @MichaelChirico!
