### ISSUE TITLE
[Request] rbindlist default behavior change request for empty lists

### ISSUE THREAD

**Issue by davidrosenberg** [Rdatatable/data.table#2183]
I'm converting from a sparse key:value type representation to a data.table using rbindlist.  It seems to drop lists that are empty, while with fill=TRUE I think it would be more usable to make the whole row NA.  Otherwise, it becomes much more complicated to match rows of the new data.table to the list entries in the original.  Here's an example:

`x=list(list(), list(a=1,c=2),list(b=2,c=4));rbindlist(x, fill=TRUE, idcol=TRUE)`
which returns
```
   .id  a c  b
1:   2  1 2 NA
2:   3 NA 4  2
```

I'd prefer the output to include a row of NAs, like

```
   .id   a  c  b
1:   1  NA NA NA
2:   2   1  2 NA
3:   3  NA  4  2
```

**Comment by franknarf1** [comment]
Hm, I don't think I'd want to see the default changed. A zero-row table should yield zero rows in the result (instead of having a special rule that 0 maps to 1).

For your case, I'd suggest:

```
rbindlist(x, fill=TRUE, idcol=TRUE)[.(seq_along(x)), on=.(.id)]
```

**Comment by davidrosenberg** [comment]
I think a zero-row table would correspond to list(), and I agree that should yield a 0 row table.  

I'm suggesting that we keep rows that would be filled to have all NAs.  Suppose we're recording results of medical tests.  Each row is a patient and after rbindlist, each column is a different test.  Some patients don't have any tests.  But we don't want to drop them from the table.

**Comment by MichaelChirico** [comment]
@franknarf1 I think this suggestion is in line with the spirit of the `fill = TRUE` argument, which _does_ already "create" data.

In the output the `.id` column is _not_ missing from the first element of `x` in David's example -- the existence of the first element is _per se_ its non-missingness. 

The _rest_ of the columns _are_ missing, but that's common for a (small or large) subset of the columns when `fill = TRUE` is used. 

As I see it, this suggestion simply takes the `fill = TRUE` logic to the extreme case of _all_ columns being missing for some elements.

**Comment by franknarf1** [comment]
@MichaelChirico I think the right approach, predicated on well-organized data (in David's example, including a separate "patients" table that can be joined with the "test results" table when needed), is to include zero rows for zero-row input tables. If filling-zero-rows-as-one is added, it certainly should not be the default; maybe it would fit as an option like `fillrows` defaulting to false. 

I see nothing special about single rows as a default substitute for zero-row tables, even when using `fill`. Suppose I have a list of tables, each having 100 rows, with various columns missing and some tables missing entirely. In that use-case, if I really wanted to fill in rows for missing tables, presumably I would want to fill in 100 rows for each missing table. So, to accommodate my expectations in this counterfactual scenario, we need an option to determine # rows to fill in. (It's "counterfactual" since I would never do this, instead organizing my data into multiple tables.)

**Comment by davidrosenberg** [comment]
@franknarf1 Ok -- now I understand what you're saying.  I was thinking about rbindlist as a way to rbind individual rows, which is how I was using it.  But it's primarily for rbinding tables, in which case I agree it makes no sense to replace an empty table with an empty row.
