### ISSUE TITLE
[Support] object 'CfreadR' not found

### ISSUE THREAD

**Issue by dustindall** [Rdatatable/data.table#2191]
I installed the latest development version of data.table and got the following error when trying to read in a csv file using fread. 

`fread("C:/Users/xxxxx/Desktop/iris.csv")`
`Error in fread("C:/Users/xxxxx/Desktop/iris.csv") : 
  object 'CfreadR' not found`

I was not having this issue when was using the CRAN version 1.10.4.

`sessionInfo()`
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.5

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0

**Comment by dustindall** [comment]
Forgot to include dependencies when downloading from github.

`install.packages("data.table", type = "source", dependencies=TRUE,  repos = "http://Rdatatable.github.io/data.table")`

Issue is resolved.

**Comment by MichaelChirico** [comment]
More likely this is related to a problem where overwriting an existing
install sometimes fails to execute properly (unless I'm not thinking
straight, data.table has no dependencies, so that shouldn't have been the
issue). If this happens, be sure to fully remove the old version of
data.table before updating.

See the instalation wiki for a preferred alternative to using
install_github as well.
