### ISSUE TITLE
`week` return wrong week number before 2006

### ISSUE THREAD

**Issue by changshun** [Rdatatable/data.table#2224]
I find a small bug in my R environment when using the `data.table::week`. It returns wrong week number when the Date is before 2006. I wonder whether it is a general bug or just because of  my personal environment. That is the code:

```
> data.table::week(as.Date("2005-05-13"))
[1] 20
> lubridate::week(as.Date("2005-05-13"))
[1] 19
> data.table::week(as.Date("2005-05-13"))
[1] 20
> lubridate::week(as.Date("2005-05-13"))
[1] 19
> data.table::week(as.Date("2005-12-02"))
[1] 49
> lubridate::week(as.Date("2005-12-02"))
[1] 48
> data.table::week(as.Date("2006-01-04"))
[1] 1
> lubridate::week(as.Date("2006-01-04"))
[1] 1
> Sys.getlocale()
[1] "LC_COLLATE=Chinese (Simplified)_People's Republic of China.936;LC_CTYPE=Chinese (Simplified)_People's Republic of China.936;LC_MONETARY=Chinese (Simplified)_People's Republic of China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_People's Republic of China.936"
```

**Comment by MichaelChirico** [comment]
off the top of my head I think lubricate returns the ISO week by default?
so try data.tables ISO week function

On Jun 28, 2017 6:42 PM, "Changshun" <notifications@github.com> wrote:

I find a small bug in my R environment when using the data.table::week. It
returns wrong week number when the Date is before 2006. I wonder whether it
is a general bug or just because of my personal environment. That is the
code:

> data.table::week(as.Date("2005-05-13"))
[1] 20
> lubridate::week(as.Date("2005-05-13"))
[1] 19
> data.table::week(as.Date("2005-05-13"))
[1] 20
> lubridate::week(as.Date("2005-05-13"))
[1] 19
> data.table::week(as.Date("2005-12-02"))
[1] 49
> lubridate::week(as.Date("2005-12-02"))
[1] 48
> data.table::week(as.Date("2006-01-04"))
[1] 1
> lubridate::week(as.Date("2006-01-04"))
[1] 1
> Sys.getlocale()
[1] "LC_COLLATE=Chinese (Simplified)_People's Republic of
China.936;LC_CTYPE=Chinese (Simplified)_People's Republic of
China.936;LC_MONETARY=Chinese (Simplified)_People's Republic of
China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_People's Republic
of China.936"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rdatatable/data.table/issues/2224>, or mute the thread

**Comment by MichaelChirico** [comment]
Confirming that `lubridate` uses ISO week by default:

```
data.table::isoweek(as.Date("2005-05-13"))
# [1] 19
lubridate::week(as.Date("2005-05-13"))
# [1] 19
data.table::isoweek(as.Date("2005-05-13"))
# [1] 19
lubridate::week(as.Date("2005-05-13"))
# [1] 19
data.table::isoweek(as.Date("2005-12-02"))
# [1] 48
lubridate::week(as.Date("2005-12-02"))
# [1] 48
data.table::isoweek(as.Date("2006-01-04"))
# [1] 1
lubridate::week(as.Date("2006-01-04"))
# [1] 1
```

So if the ISO week is what you want, please use `isoweek`
