### ISSUE TITLE
frank dense option needs to be explained more and more examples.

### ISSUE THREAD

**Issue by skanskan** [Rdatatable/data.table#2226]
Hello.

The frank function has an option` ties.method="dense"`  that says:
 `which returns the ranks without any gaps in the ranking. See examples.`
`frankv(x, ties.method="dense")
`
But that's all.

Could you explain a little bit more whats supposed to do or provide more examples, please?

The same goes for the min and max options.

I also can't see the difference between `frank ` and `frankv`

Thanks

**Comment by arunsrinivasan** [comment]
I honestly have no idea how to improve the definition more than that, because that's what it precisely does. If you understood what other ranks did, from reading `?rank` (or using them), this shouldn't be hard to grasp. Have you read `?rank`?

Have you looked at the examples:

```r
x = c(4, 1, 4, NA, 1, NA, 4)
...

# ties.method = min
frankv(x, ties.method="min")
# ties.method = dense
frankv(x, ties.method="dense")
```

and try to understand the difference between `min` and `dense`?

Well, from `?frank`:

```r
frank(x, ..., na.last=TRUE, ties.method=c("average", 
  "first", "random", "max", "min", "dense"))

frankv(x, cols=seq_along(x), order=1L, na.last=TRUE, 
      ties.method=c("average", "first", "random", 
        "max", "min", "dense"))
```

I can see there's a difference in the function definition. And the arguments are explained underneath:

> `...`	Only for lists, data.frames and data.tables. The columns to calculate ranks based on. Do not quote column names. If ... is missing, all columns are considered by default. To sort by a column in descending order prefix a "-", e.g., frank(x, a, -b, c). The -b works when b is of type character as well.
`cols`	A character vector of column names (or numbers) of x, to which obtain ranks for.
`order`	An integer vector with only possible values of 1 and -1, corresponding to ascending and descending order. The length of order must be either 1 or equal to that of cols. If length(order) == 1, it's recycled to length(cols).

This is in accordance with `setkey / setkeyv`, `setorder / setorderv` etc..

**Comment by skanskan** [comment]
OK, I can see the difference.
with "min" the numbering after the tie continues as if there where no ties.
with "desde" it continues as if the repeated elementes count as one.

**Comment by MichaelChirico** [comment]
@skanskan it seems you were contented by @arunsrinivasan's response; is there still something to add to the documentation?

**Comment by skanskan** [comment]
No, thank you.  You can close the issue.
