### ISSUE TITLE
Segfault with fread

### ISSUE THREAD

**Issue by etienne-s** [Rdatatable/data.table#2299]
I get a segfault when using `fread` on this file: [test.txt](https://github.com/Rdatatable/data.table/files/1222407/test.txt)

I use the latest dev version, the problem does not occur with the CRAN version.

The file can be fixed by adding a separator at the end of line 116.

Not sure whether it is related to an existing issue or not.

**Comment by st-pasha** [comment]
On my MacOS machine, I get the following:
```
> fread("~/Downloads/test.txt")
Error in fread("~/Downloads/test.txt") : 
  Expecting 7 cols but row 0 contains only 6 cols (sep='|'). Consider fill=true. <<"aa aa aa aa aa aa aa aa !"|1|aa.aa.aa|"aa aa aa aa aa aa aa aa ! 1 aaûaa 1 aa aa1 aa : aa aa aa'aa aa aa aaé aa aa aa aa ! aa aa aa aa !"|aa aa aa aa aa aa aa aa ! ,|>>
```
This is a valid error message (except that the line number is incorrect) -- the line shown does have 6 fields instead of expected 7; and adding option `fill=TRUE` does read the file correctly. There is no segfault.

However I haven't tested this on a Windows machine yet -- maybe the problem is platform specific?
