### ISSUE TITLE
Specifying nrows in fread doesn't change memory usage while reading

### ISSUE THREAD

**Issue by bushal01** [Rdatatable/data.table#2321]
I have a 74GB file that I want to read in 5m rows at a time (total size ~200m rows x 83 cols).  

When I use fread with nrows = 0, nrows = 1000, or nrows = 5000000 it always uses up the same amount of memory (~74 GB of RAM) while reading in/parsing the file.  Is there a way to avoid this problem?  Other similar functions (read.table from base, read_delim from readr) do not have this problem.  I looked here and on SO for a post about this, but couldn't find anything.

Also, it is probably related to the memory usage issue, but fread is also very slow when performing this operation (~1 minute to read in the first 1000 rows x 83 cols of a 74 GB file compared to < 1s with read.table).

**Comment by tcederquist** [comment]
For a quick consideration: fread appears to use a memory map (mmap c api call) to map the entire file to memory. If your memory size cannot fit this entire image, it's likely swapping though the page file which is very slow (memory through disk). If you are using linux, you might consider splitting the file with something like "split -l 5000 yourfile.csv yourfileparts". Do you have headers in the file? only the first part would have them, you'd probably have to cat the head -1 of the file into each part if you need them. Not a clean solution but a quick option if you need one. Having looked at the fread c library up the point of mmap, I'm not sure it would be easy to consider reading it as a partial file. However, I've only looked at the code at a glance.

**Comment by tcederquist** [comment]
Thinking further about this as it should be a common workflow to speed up large file research. We also have lots of data in hadoop that's just too large for one machine. Seems a good place to add a related considerations if a patch/optimization could be implemented for this issue:

 - Getting just n rows as the api suggests but without using all the memory for the entire file mmap per @bushal01 
 - Chunk file support might become feasible for paging the data through memory to support filters without the memory hit of a full load into memory on very large files
 - % sample feature could be supported without loading all of the file into memory at once. (ie: 10% random sample of a file to prototype logic or preliminary analytical results)

Possible method - when called for, switch to loading memory through fgets or freadf or similar stream method.

Challenges:
 - Although files could be simpler to support with streaming preview to id the byte size for nrows and then continue using mmap and length and offsets parms, pipes are forward only. mmap reads the whole thing and stops when its out of shared memory or pipe ends. (linux does anyhow which is a problem for docker with its 64M default which truncates streams at that point)
 - Streaming would need to fill the memory buffer dynamically instead of mmap directly when chunking for nrows parm. Memory re-allocs and fragmentation are a risk and slower but the benefit would be support for large files and only used when the api call requires it.

**Comment by mattdowle** [comment]
Thanks for the detailed report.
[NEWS](https://github.com/Rdatatable/data.table/blob/master/NEWS.md) for dev 1.10.5 contains this as item 3 : 
> Memory maps lazily; e.g. reading just the first 10 rows with nrow=10 is 12s down to 0.01s from cold for the 9GB file. Large files close to your RAM limit may work more reliably too. The progress meter will commence sooner and more consistently.

That change was early last year so hopefully you found it and tried dev by now. It's not on CRAN yet as it's wrapped up in the parallel fread effort too.  If you haven't seen NEWS from dev,  now is a good time to give it try.

Anyway, please retry dev 1.10.5 and I'm pretty sure it's as you expect now.  Please open a new issue if not. Thanks.
