### ISSUE TITLE
as.xts.data.table does not properly support all date based classes for index

### ISSUE THREAD

**Issue by ebs238** [Rdatatable/data.table#2408]
xts objects support many date classes for the index, but the `as.xts` function only explicitly checks for small subset of classes.

fortunately, the `xts::timeBased` function will perform this check properly

i.e. replace 
`if (!any((index_class <- class(x[[1L]])) %in% c("POSIXct", "Date"))) `
with:
`if(!xts::timeBased(x[[1L]]))`

**Comment by ebs238** [comment]
drop in replacement:
```
as.xts.data.table <- function(x, ...) {
    stopifnot(requireNamespace("xts"), !missing(x), is.data.table(x))
    if (!timeBased(x[[1L]])) stop("data.table must have a time based column in first position, use `setcolorder` function to change the order, or see ?timeBased for supported types")
    colsNumeric = sapply(x, is.numeric)[-1L]
    if (any(!colsNumeric)) warning(paste("Following columns are not numeric and will be omitted:", paste(names(colsNumeric)[!colsNumeric], collapse = ", ")))
    r = setDF(x[, .SD, .SDcols = names(colsNumeric)[colsNumeric]])
    xts::as.xts(r, order.by = x[[1L]])
}
```

**Comment by MichaelChirico** [comment]
Nice catch! Feel free to file a PR, see [Contribution Guidelines](https://github.com/Rdatatable/data.table/wiki/Contributing)! happy to help facilitate

**Comment by ebs238** [comment]
i have fixes and test in https://github.com/ebs238/data.table. 
The fix works and looks clean to me, but I cant get the test to pass, and im not sure why. 
This is my first attempt at a PR, so any suggestions would be appreciated

**Comment by MichaelChirico** [comment]
Can you attempt to pull into master please? it'll be easier for me to see
the output of Travis & help you out

On Oct 13, 2017 11:47 PM, "ebs238" <notifications@github.com> wrote:

i have fixes and test in https://github.com/ebs238/data.table.
The fix works and looks clean to me, but I cant get the test to pass, and
im not sure why.
This is my first attempt at a PR, so any suggestions would be appreciated

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Rdatatable/data.table/issues/2408#issuecomment-336491143>,
or mute the thread
