### ISSUE TITLE
Unable to use factors with column keys

### ISSUE THREAD

**Issue by galloppinggryphon** [Rdatatable/data.table#2414]
This issue/bug appears to be related to #1361 and may actually belong there. Whereas binary search of factor column data now works, using key columns does not.

Example:
```
dt <- data.table(i=LETTERS[1:3], f=as.factor(1:10))
dt[f==1] #works
   i f
1: A 1
setkeyv(dt, c("i", "f"))
dt[J("A", c(1,7))] #does not work
Error in bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,  : 
  x.'f' is a factor column being joined to i.'V2' which is type 'double'. Factor columns must join to factor or character columns.
```

Using `R 3.3.3` and `data.table 1.10.4`.

**Comment by MichaelChirico** [comment]
the error message is suggesting what's going wrong. have you tried

DT[J('A', factor(c(1, 7)))]

On Oct 13, 2017 12:39 AM, "galloppinggryphon" <notifications@github.com>
wrote:

This issue/bug appears to be related to #1361
<https://github.com/Rdatatable/data.table/issues/1361> and may actually
belong there. Whereas binary search of factor column data now works, using
key columns does not.

Example:

dt <- data.table(i=LETTERS[1:3], f=as.factor(1:10))
dt[f==1] #works
   i f
1: A 1
setkeyv(dt, c("i", "f"))
dt[J("A", c(1,7))] #does not work
Error in bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,  :
  x.'f' is a factor column being joined to i.'V2' which is type
'double'. Factor columns must join to factor or character columns.

Using R 3.3.3 and data.table 1.10.4.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rdatatable/data.table/issues/2414>, or mute the thread

**Comment by galloppinggryphon** [comment]
@MichaelChirico Thanks, that works, but the point is that it works without factor() in `dt[f==3]`. It was reported as an issue and fixed. So for consistency, it shouldn't it be possible to do the same using keys?

**Comment by franknarf1** [comment]
@galloppinggryphon Fyi, this happens with other column types as well:

```
library(data.table)
DT = data.table(d = as.IDate("2011-11-11") + 0:10)
DT[d == "2011-11-11"]
DT[.("2011-11-11"), on=.(d)]
# Error in bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,  : 
#   typeof x.d (integer) != typeof i.V1 (character)
```

The issue is that you are expecting data.table to do coercion, but it doesn't here. If you want to take advantage of fast joins and such, it's probably best to match consistent types.

Btw, it is about joins, not keys.

**Comment by galloppinggryphon** [comment]
@franknarf1 Thank you, I see the point now. I'll take it that coercion works in simple operations like binary search, but not for more advanced operations like join.

**Comment by MichaelChirico** [comment]
Related: #3506

**Comment by MichaelChirico** [comment]
I'd say `factor`-to-naked-`integer` is a fragile strategy (relies on knowing for sure the order of levels of the factor); if you want to join on underlying integer, it seems to me it's safer to use a `factor` to do so. Most natural to me feels like `factor`-to-`character`; both of these are covered by the helpful warning:

> x.'f' is a factor column being joined to i.'V2' which is type 'double'. Factor columns must join to factor or character columns.
