### ISSUE TITLE
fwrite crashes R with "memory not mapped"

### ISSUE THREAD

**Issue by jsams** [Rdatatable/data.table#2450]
edit: used `split` to cut my data.table approximately in half and was able to call fwrite with append on the two halves to achieve the same objective. So, it does appear that there is a bit of an issue here with the number of rows. `</edit>`

I have a 2,127,958,282 row data.table with 3 columns of type integer, integer, and numeric. I am trying to write this data.table to a file in append mode. The file is a minimal matrix market format, so only has a couple of lines at the top to append to. I've used fwrite in this fashion with other large data.table's, but none quite this large. My guess is that something is hitting the row limit of data.table, but I'm not exactly sure why.

unfortunately, with these big data problems, creating minimal reproducible examples is non-trivial.

since it seems related, is there any interest/timeline for releasing a version of data.table that is not constrained to the number of rows being less than integer.max?

the function call and resulting stack output is:
```
> writeMM.dt(affil_matdt, sprintf(ALL_DATA, "affils_mat_all.mm"))

 *** caught segfault ***
address 0x7f539f171b28, cause 'memory not mapped'

Traceback:
 1: fwrite(outmat, filename, append = T, sep = " ")
 2: writeMM.dt(affil_matdt, sprintf(ALL_DATA, "affils_mat_all.mm"))

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 2

```

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /software/free/r/R-3.4.0/lib/R/lib/libRblas.so
LAPACK: /software/free/r/R-3.4.0/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.2-10     lubridate_1.6.0   fasttime_1.0-2    data.table_1.10.4

loaded via a namespace (and not attached):
[1] compiler_3.4.0  magrittr_1.5    tools_3.4.0     stringi_1.1.5   grid_3.4.0      stringr_1.2.0   lattice_0.20-35
```

**Comment by mattdowle** [comment]
Thanks for the good report.  Could you try with 1.10.5 from dev please:  https://github.com/Rdatatable/data.table/wiki/Installation

There have been changes in dev to `fwrite` and it's possible this is fixed.

**Comment by jsams** [comment]
yep, latest dev seems to have fixed the issue. Thanks!

I've looked around but don't see an answer (which might be the answer): are you guys doing any work to allow data.tables to have more than MAXINT rows? where can I keep abreast of that progress?

**Comment by mattdowle** [comment]
@jsams  Thanks for the confirm -- great. Closing then.

We've always wanted more than MAXINT rows and it's not hugely difficult or anything now that R supports long vectors from R 3.0.0.  Just nobody started that.  The code has to be swept through and types and methods changed to, for example, `XLENGTH()`.  Then somehow we need to test it.  Testing big files and operations on that many rows is going to be necessarily compute and RAM demanding.  Such tests can't be done on AppVeyor or Travis so we need a big-data test environment creating.  Both for benchmarking and correctness.  There may be a performance impact on "smaller" data under 2 billion rows since I assume we will just change everything to 64-bit indexing and not try and have mixed 32-bit and 64bit indexes which would complicate the code and could give rise to more bugs.

This issue is the closest I found:  https://github.com/Rdatatable/data.table/issues/570

Can anyone help with big data (>2bn rows) testing and benchmarking?

**Comment by jsams** [comment]
Yea, having test servers for big data (especially in memory) is of course not easy to solve. While I have access to some other people's resources for running my own code, I unfortunately don't have any of my own to offer up (and those other resources are already quite oversubscribed). Your profile says you are in Palo Alto. Maybe there's something in the comp sci or stats departments at Stanford to provide resources for big data tools? Or maybe Berkeley, they do have some of the CRAN stuff already, right?

Sorry I can't be of greater assistance there.

**Comment by aadler** [comment]
I have access to a server with 532GB RAM at work so I may be able to test a file here and there. I cannottie it up too long as we do need it for actual work :)
