### ISSUE TITLE
"fread "segfault from C stack overflow" using 1M+ columns"N2

### ISSUE THREAD

**Issue by AndreV84** [Rdatatable/data.table#2556]
How to get Rstudio-server to recognize 
ulimit -s 65535
or
/etc/security/limits.conf 
changes ?

The changes are reflected by R, but Web-interface of rstudio server[ec2 ami amazon instance] persists reflecting the constant value on Cstack_info() .

**Comment by AndreV84** [comment]
Neither execution from Rstudio seem to impact the Cstack_info() output:
 system("ulimit -s 65535")
> Cstack_info()
      size    current  direction eval_depth 
   7969177

**Comment by mattdowle** [comment]
I don't know about the Rstudio aspects,  but the `fread C stack overflow` is vaguely familiar, and I'm pretty sure fixed in dev.
Can you please confirm the version number of data.table that you are using?  If you are using the CRAN version, please try dev. The output of `sessionInfo()` was asked for in the new issue template - we need that to know the version numbers.  See points 1 and 3 here:  https://github.com/Rdatatable/data.table/wiki/Support
If you still have the problem, please raise a new issue.
