### ISSUE TITLE
Use Rperform

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#2584]
https://github.com/analyticalmonk/Rperform

IIUC, like CodeCov, it would auto run in a PR and let us know any impact to performance (deliberate or otherwise).

**Comment by MichaelChirico** [comment]
See also #3928 -- curious if anyone has any idea for scaling up the approach there to be something like performance monitoring.

As of now it's only especially useful for detecting performance of a specific example.

We can easily iterate over commits and run `test.data.table()` but of course the size of the test suite is growing over time & even if we return the performance at an individual test level, it will have to be run many times to be useful as such.

Alternatively we could start building a library of performance tests gradually.

**Comment by jangorecki** [comment]
I will look into Rperform.
`test.data.table` and checking time over
By plugging [dtq](https://github.com/jangorecki/dtq) package when running reverse dependencies we can get fine grained information about timings. That would unlock really complex analytics on data.table usage, for example. tracking down that `.SD` usage in `j` caused slowdown, or an `i` argument of 1-row data.table caused slowdown, or non-missing `.SDcols` caused slowdown.
Note it only tracks `[.data.table` calls, also activating for revdeps it means we check it only for toy data.

**Comment by jangorecki** [comment]
There is also https://gitlab.com/jangorecki/macrobenchmark which I created exactly for the same purpose as Rperform. In this repo it is example how to use it: https://gitlab.com/jangorecki/macrobenchmarking

**Comment by jangorecki** [comment]
> IIUC, like CodeCov, it would auto run in a PR and let us know any impact to performance (deliberate or otherwise).

For that it would need to have a server to archive results, as codecov.io. Rperform does not seem to be actively developed anymore. After looking at demo examples in https://github.com/DevinderKaur/RpeformDEMO it doesn't really look to be that useful.

Much simpler seems to be just write down to csv a table having timings of all tests and compare that over time, we just need a storage for that. Maybe we could add it as a part of release process, so we can at least compare version vs version. Anyway because times of unit tests are so tiny I don't think it will be that useful, variance will be relatively high, so would need multiple iterations to take averages.

And for more serious cases, not tests, but benchmarks, it will be covered by #4687
