### ISSUE TITLE
memory issue in devel when doing subset

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2635]
```r
library(data.table)
packageVersion("data.table")

n = 1e6
K = 100
set.seed(1)
DT = data.table(
    char1 = sample(sprintf("id%010d",1:(n/K)), n, TRUE),
    char2 = sample(sprintf("id%03d",1:K), n, TRUE),
    char3 = sample(sprintf("id%1d",1:5), n, TRUE),
    int1 = sample(n/K, n, TRUE),
    int2 = sample(K, n, TRUE),
    int3 = sample(5, n, TRUE),
    double1 = sample(seq(0, 1, length.out=n/K), n, TRUE),
    double2 = sample(seq(0, 1, length.out=K), n, TRUE),
    double3 = sample(seq(0, 1, length.out=5), n, TRUE)
)

# query subset filters
subn = 0.001
res = DT[sample(n, n*subn, FALSE)]
cin1 = res[["char1"]]
iin1 = res[["int1"]]
din1 = res[["double1"]]
cin1 = unique(cin1)
iin1 = unique(iin1)
din1 = unique(din1)

# query
DT[char1%in%cin1 & int1%in%iin1 & double1%in%din1]
```
output on 1.10.4.3
```
[1] ‘1.10.4.3’
             char1 char2 char3 int1 int2 int3    double1    double2 double3
   1: id0000009348 id078   id1 3313   63    2 0.15461546 0.49494949    0.00
   2: id0000003862 id043   id4 8495    1    2 0.90929093 0.44444444    0.75
   3: id0000006380 id098   id4 9588   77    1 0.02410241 0.29292929    0.00
   4: id0000007731 id089   id3 6355   44    2 0.29822982 0.85858586    0.50
   5: id0000002179 id001   id3 5293   70    4 0.90779078 0.32323232    0.00
  ---                                                                      
1866: id0000006149 id041   id3 1573   65    3 0.45184518 0.82828283    0.25
1867: id0000000520 id080   id2 2914   16    5 0.24002400 0.09090909    0.00
1868: id0000005978 id077   id4 2264   92    1 0.21452145 0.84848485    1.00
1869: id0000008768 id044   id3 7501   25    2 0.62416242 0.69696970    1.00
1870: id0000002430 id033   id3 4688   42    2 0.44774477 0.79797980    0.75
```
output on latest 1.10.5
```
[1] ‘1.10.5’
Error: cannot allocate vector of size 6.5 Gb
```
@MarkusBonsch it might eventually be related to your subset PR.

**Comment by HughParsonage** [comment]
I don't get an out-of-memory error but it does take a few minutes to complete.

**Comment by MarkusBonsch** [comment]
You are right, this change in behaviour is a result of the new optimization strategy.
It is using `CJ` to construct the `i` data.table with all the combinations of values to match. In your case, this means constructing a `length(unique(cin1)) * length(unique(iin1)) * length(unique(din1)) ~ 866e6` row data.table. 
I wouldn't call it a bug, it is a corner case where the new optimization strategy is clearly not optimal.
I would propose to change so that the optimization is switched off, when the CJ result is estimated to have more than 1e4L columns. While the threshold is arbitrary, it prevents problems like yours and I feel that normal queries rather have < 100 rows in the resulting `i` data.table. If you agree, I will create a PR.

**Comment by jangorecki** [comment]
This is tiny case. Cross product of all elements in `i` won't scale. In case of "fact" tables you easily have 10+ dimensions to filter on, and filter by ranges, not single values, you will run out of memory very fast. It is much better to loop a query on each field separately using `which` and then `intersect`. This is exactly how it is implemented in (data.cube)[https://gitlab.com/jangorecki/data.cube].

**Comment by MarkusBonsch** [comment]
I agree (as mentioned above) that the cross-join approach is not suitable for your case. I am not fully sure, if I understand your proposal, but I guess that is what is called a "vector scan" and is done by data.table if optimization is not taking place. So I guess that my proposed fix would solve your issue by disabling optimization for large cross products?

**Comment by jangorecki** [comment]
It not really a matter of case but cpu and memory balance. Worst case scenarios for just a 10 row data.table requires 37gb.
```r
library(data.table)
l = lapply(1:10, function(x) 1:10)
DT = as.data.table(l)
DT[V1%in%1:10 & V2%in%1:10 &
   V3%in%1:10 & V4%in%1:10 &
   V5%in%1:10 & V6%in%1:10 &
   V7%in%1:10 & V8%in%1:10 &
   V9%in%1:10 & V10%in%1:10]
#Error: cannot allocate vector of size 37.3 Gb
```
not vector scan but `bmerge` using index on each column separately.

**Comment by arunsrinivasan** [comment]
Non-equi joins require:

a) a pre-processing step to determine how many *non-equi* groups there are (as I call it).
b) running a binary search (equi-join) for each of those non-equi groups.

In essence, it does more work. If all one needs is to do a row subset, there's no need for all the extra book-keeping (which rows in 'x' match for which rows in 'i' etc.). Therefore you'd end up doing more work.

I'm pretty sure, there are scenarios where simple vector scans (perhaps even run in parallel across each query from a given compound query, e.g., a%in% b & c %in%d would run two vector scans in parallel and combine them)..

These things need to be tested more so that depending on the query in Q, we can choose the appropriate method (like in DBs). 

I'm curious to know as to when the the amount of (extra) work done during binary search (noting down the indices, rather than just TRUE/FALSE state) becomes complex enough to be slower than a simple vector scan (or an enhanced parallel-vector-scan)..

**Comment by MarkusBonsch** [comment]
Having thought about the loop bmerge solution a bit more, I am very sceptical that this can be a good optimization strategy. Se my update on the post with pros, cons, and recommendation.

**Comment by jangorecki** [comment]
I am not saying using index separately and loop is a way to go, it is just workaround, and it scales. In reporting platforms you index data once after reloading from sources and then re-use it till next reload (usually daily/hourly), and in such platforms queries like this are not edge cases but stuff which happens daily. Probably the proper way to is to push down more stuff to C.

**Comment by mattdowle** [comment]
PR merged but issue left open. Thought process in [this comment](  https://github.com/Rdatatable/data.table/pull/2637#issuecomment-367459407).

**Comment by MarkusBonsch** [comment]
Great, glad to hear. i will replace the "bug" label with "performance" since the behaviour is definitely not worse than 1.10.4, imho. @jangorecki feel free to change back to bug if you feel it is more appropriate.

**Comment by jangorecki** [comment]
"bug" label refers to fact that many queries which previously runs fine started failing due to memory limitation, which is definitely worse than 1.10.4, but is solved by 1e4 threshold for now. As of now the issue is about documenting that, which will be done in separate doc.
