### ISSUE TITLE
fail when wrap "subset within each group" in function?

### ISSUE THREAD

**Issue by chenwq** [Rdatatable/data.table#2709]
```
subset.grp = function(df, subset, grp){
  subset = substitute(subset)
  df = data.table(df)
  df[df[, .(ix = .I[eval(subset)]), by = get(grp)]$ix] 
}
foo = function(x)subset.grp(iris, Sepal.Length > x, 'Species')
```
succeed when I directly run subset.grp():

```
x = 5 
subset.grp(iris, Sepal.Length > x, 'Species')    

```
fail when I run foo():
```
rm(x) # It seems foo just use 'x' in .GlobalEnv
foo(x=5)
 Error in eval(expr, envir, enclos) : object 'x' not found 
```

**Comment by jangorecki** [comment]
Add `print(subset)` inside your function and you should get the answer why it is not working.

**Comment by chenwq** [comment]
no difference of print

**Comment by franknarf1** [comment]
This probably belongs on StackOverflow, since it's related to R, not data.table, as far as I can tell.

Fwiw, I would do

```
library(data.table)

DT = data.table(iris)

sg = function(df, cond, grp){
  ex = substitute(.(ix = .I[eval(cond)]), list(cond=cond))
  print(ex)
  df[df[, eval(ex), by = grp]$ix] 
}

subset.grp(DT, substitute(Sepal.Length > x, list(x=5)), 'Species') # works fine

foo = function(x) subset.grp(DT, substitute(Sepal.Length > x, list(x=x)), 'Species')    

foo(x = 5) # same thing
```

... since I never bothered learning how to use substitute() except with a second argument.

**Comment by jangorecki** [comment]
This definitely belongs to SO. `x` was defined in `foo` scope and was not passed to `subset.grp` scope. What was passed to `subset.grp` is expression which uses `x` argument that is unknown in scope where evaluation happens. If you would pass `x` from `foo` to `subse.t.grp` your query will work fine, but probably Frank solution is what you really need - substitute `x` before passing to to `subset.grp`. Next time use SO for such questions, and use `as.data.table(df)` instead of `data.table(df)`.
