### ISSUE TITLE
`max` Gforce optimization may be not accounting for typing with length 0 vector inputs

### ISSUE THREAD

**Issue by aomidpanah** [Rdatatable/data.table#2737]
I am calling max in an aggregation using `by=` in `[.data.table` where some inputs are possibly length 0 (after excluding NA values). The default in R is to produce `-Inf` which, is a typeof of double, not integer. I do not think data.table.optimize properly accounts for this in the typing.

https://stackoverflow.com/questions/49781741/aggregation-and-typing-inconsistency-in-data-table

Reproducible example:
```

dt <- data.table(id = c(1,1,1,3,3,3), num = 1:6, log = c(F,F,F,T,F,T))
dt[, .(mnum = max(num[log], na.rm=T)), by=id]
```

says

```
Error in `[.data.table`(dt, , .(mnum = max(num[log], na.rm=T)), by=id1] :
 Column 1 of result for group 2 is type 'integer' but expecting type 'double'. Column types 
```

The expected output would be:
```
mnum id
-Inf  1
   6  3

```

**Comment by arunsrinivasan** [comment]
The expression isn't optimised with GForce in this case. You can check this by adding `verbose=TRUE` argument.

```r
> dt[, .(mnum = max(num[log], na.rm=T)), by=id, verbose=TRUE]
# Detected that j uses these columns: num,log 
# Finding groups using forderv ... 0.000sec 
# Finding group sizes from the positions (can be avoided to save RAM) ... 0.000sec 
# lapply optimization is on, j unchanged as 'list(max(num[log], na.rm = T))'
# GForce is on, left j unchanged
# Old mean optimization is on, left j unchanged.
# Making each group and running j (GForce FALSE) ... 

# Error in `[.data.table`(dt, , .(mnum = max(num[log], na.rm = T)), by = id,  : 
#   Column 1 of result for group 2 is type 'integer' but expecting type 'double'. Column types must be consistent for each group.

# In addition: Warning message:
# In max(num[log], na.rm = T) :
  no non-missing arguments to max; returning -Inf
```

The error happens because, as the error message mentions, type of object returned from the function evaluated in `j` is different across groups. You can test this simply with a `print()` or `cat()`.

```r
dt[, cat("\n", class(max(num[log], na.rm=T)), "\n"), by=id]
#  numeric 
# integer 
# Empty data.table (0 rows) of 1 col: id
# Same warning message
```

This happens because of the -Inf result due to length=0 input. Simply wrap your expression with `as.numeric(max(...))` and it should work fine.

Checking (and coercing) object types for every group for every column will make things terribly slow. Besides, IMHO, this is an inconsistency in base R. It'd be much more consistent if object types returned from functions are consistent.

HTH.

**Comment by jangorecki** [comment]
I don't think there is anything more we have to do about this issue.
