### ISSUE TITLE
Reduce number of suggested dependencies

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2740]
Ideally we want suggested dependency to be packages that we call from data.table functions (conditionally of course). Packages that are only used in tests will fit better into our integration tests workflow (`test.data.table(with.other.packages=TRUE)`) thus should be moved from `./DESCRIPTION` to `./inst/tests/tests-DESCRIPTION`.
Current Suggests:
- [x] bit64 - supported data type in data.table
- [x] curl - used in `fread` to access https/ftps, probably needed on R 3.1.0
- [x] knitr - used to build vignettes
- [x] xts - used in `as.data.table.xts`
- [x] nanotime - used in `fwrite`
- [x] zoo - used in `as.data.table.xts` - it is dependency for xts anyway
- [ ] chron
- [ ] reshape2
- [ ] testthat (>= 0.4)
- [ ] GenomicRanges - https://github.com/Rdatatable/data.table/issues/2726

**Comment by mattdowle** [comment]
I already reduced the number of Suggests from 21 to 10 in PR #2671.
In that PR I added reasons why the remaining Suggests remain, near the top of tests.Rraw, [here](https://github.com/Rdatatable/data.table/blob/master/inst/tests/tests.Rraw#L66).  In that content I'm not sure what the tick boxes mean in the first comment here above this issue.  Let's try and keep those reasons in one place there, in the code.
It would be good to remove GenomicRanges in Suggests for the reasons you state there, so let's keep #2726 open. But otherwise, we're good for now I think.

**Comment by jangorecki** [comment]
- reshape2 has `melt` generic so we can safely remove call to reshape2 there, it will dispatch to next method from reshape2. `dcast` is not generic in reshape2, we could make PR adding that. Then should be fine to move reshape2 integration tests.
- testthat - this is not covered in tests.Rraw, maybe it is a matter of calling `test_check()` from other.Rraw...

Both those packages has multiple recursive dependencies..

**Comment by jangorecki** [comment]
As discussed it make sense to remove a little bit more of suggested dependencies, as we actually not suggesting them, we are just using them in tests. `testthat` is pretty heavy.

**Comment by mattdowle** [comment]
Yes I suggested yesterday we could remove `testthat` in this release.
