### ISSUE TITLE
fwrite's quote argument could allow more flexibility (as does write.csv)

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#2762]
Inspired by: https://stackoverflow.com/a/49894448/3576984

`write.csv` allows the user to _specify_ columns to quote: 

> `quote` | a logical value (`TRUE` or `FALSE`) or a numeric vector. If `TRUE`, any character or factor columns will be surrounded by double quotes. If a numeric vector, its elements are taken as the indices of columns to quote... If `FALSE`, nothing is quoted.

Should we do this, and one better by allowing _named_ columns to quote (i.e. simply using `chmatch` of course)?

`quote = "auto"` works perfectly in the cited use case, but I can imagine some benefits for the flexibility in some cases.

**Comment by mattdowle** [comment]
Ideally, it would be good. But since `quote='auto'` works and we've over 600 other open issues, let's take that as a win! Until someone can provide a use-case when `quote='auto'` does not work and column specific quoting is needed.

It's good to have this as an issue in closed status so it can still be returned from search. Any project member can reopen the issue, or a user can provide a use-case in a new issue and link to this.
