### ISSUE TITLE
Crash when running test.data.table() on Windows

### ISSUE THREAD

**Issue by etienne-s** [Rdatatable/data.table#2822]
I installed the latest CRAN Windows binary today (version `1.11.0`), and running `test.data.table()` completely crashes my system.

I tried 2 times, and on the 2nd time I observed that the crash seemed to happen at test id 1642.007.

<details><summary>Session info</summary>

``` 
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.11.0

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.19
```

</details>

**Comment by mattdowle** [comment]
And all packages need to be reinstalled for R 3.5.0 because R's internal binary format has changed.  I think there's supposed to be a message preventing you from loading a binary package from before, into R 3.5.0.  But you can circumvent that with `checkBuilt=FALSE`.  Is there any chance something like that is happening?  `test.data.table()` loads `bit64`, `xts`, `nanotime` and `chron`.  Perhaps try removing those and rerunning `test.data.table()`, then reinstalling them.

**Comment by etienne-s** [comment]
Thanks for your answer. I had reinstalled all my packages when I upgraded to R 3.5.0. I had `bit64` and `chron` installed, but not `nanotime` nor `xts`.

Here is what I've just done:

1. removed `data.table`, `bit64` and `chron`
2. rebooted
3. reinstalled `data.table`
4. ran `test.data.table()` --> everything went fine
5. reinstalled `bit64` and `chron`
6. ran `test.data.table()` again --> everything went fine again

So it was probably just a .dll problem. Sorry for the trouble and thanks again!
