### ISSUE TITLE
Support data.table at remote GPU?

### ISSUE THREAD

**Issue by harryprince** [Rdatatable/data.table#2877]
Does anyone consider to support data.table at remote GPU/CPU? Just like [dask](http://dask.pydata.org/en/latest/spark.html)/[ray on pandas](https://rise.cs.berkeley.edu/blog/pandas-on-ray/), which can help us to train reinforcement learning model like A3C.

**Comment by jangorecki** [comment]
Which particular data.table operations you see as good to be computed on GPU?
IIUC your question asks for two things at once.
1. There is no built in support for remote computing. This can be easily achieved using Rserve and RSclient. You can see working implementation in [big.data.table](https://github.com/jangorecki/big.data.table) - it fully answer your question about remote computing (you can ignore sharding and use just single remote node).
2. There is no (yet) support for GPU computing. This can be achieved using OpenMP 4 target constructs. The problem is that compilers are not yet fully support this features, and assuming that most R users don't deal too much with compilers, only tiny fraction of users would benefit from that. Of course this is good goal for a future development.
