### ISSUE TITLE
export split.data.table

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#2920]
It might happened that users miss that we have split method just because we exported it as a method only, and not as function directly, thus `split.data.table` cannot be accessed without `:::`.
There is no harm in exporting that.

**Comment by mattdowle** [comment]
> thus split.data.table cannot be accessed without :::

that's not true because `split(DT)` dispatches to split.data.table if `DT` is a data.table.  It was already done properly before using `S3method(split, data.table)` in NAMESPACE.  Exporting the method explicitly (i.e. the `export(split.data.table)` that was added) means that users can then call the method directly and they're not supposed to do that.  They're supposed to leave it to the generic function: split(DT).  In this case the split generic is in base so we're supposed to respect it and not bypass it.  The harm in exporting methods explicitly is that they might start to diverge/become incompatible with that generic.  Since when a user calls the exported split.data.table method,  it's not really a method anymore,  that's the method being used directly as a function.
