### ISSUE TITLE
cross-platform version of fread("tail -1 file")?

### ISSUE THREAD

**Issue by tdhock** [Rdatatable/data.table#3128]
Hi there @mattdowle @arunsrinivasan 

I am using fread + tail to read only the last line of a really big file (because I don't need it all in memory, but I want to look at the last line to verify the integrity of the file's contents). e.g.

```r
cat("1 foo\n2 bar\n3 baz", file=tmp <- tempfile())
fread(paste("tail -1", tmp))
```

But I fear that the above is not portable to windows.

I wonder if it would be possible/easy to implement a new fread option that allows reading the last line? I know that we can read the first line using `fread(tmp, nrows=1)`. Seems like negative numbers for nrows are currently unused/undefined, so maybe it could be `fread(tmp, nrows=-1)` to read only the last line?

Or is there a way to read the last line using existing options?

I know that fread is already reading the last line during the initial scan/sample, so I figured it would be easy/fast to implement.

**Comment by MichaelChirico** [comment]
Related: #583, #1643

**Comment by MichaelChirico** [comment]
For now, I would use `readLines` on a `connection` to your file. This can be used to cycle through the file line-by-line without having to keep it all in memory. I'm not sure about the speed.

You can see an example of the usage in this WIP PR: 

https://github.com/Rdatatable/data.table/pull/2656/files#diff-537009978509c34a2382eec1cb263c70R97

**Comment by jangorecki** [comment]
Instead of powershell I would use http://mingw.org/ so R code stays portable, but there is one more OS dependency, which could be useful in many other shell tasks anyway.

**Comment by chinsoon12** [comment]
Another option (similar to MichaelChirico's approach) if you have Rtools and its in your PATH environment variable:

```
fname <- "test.txt"
fwrite(data.table(ID=LETTERS, VAL=1:1e7), fname)

system.time({
    nl <- as.numeric(strsplit(system(paste("wc -l", fname), intern=TRUE), " ")[[1]][1])
    fread(fname, skip=nl-1)
})
#   user  system elapsed 
#    0.69    0.09    2.56

unlink(fname)
```

**Comment by jangorecki** [comment]
If Rtools have `wc` maybe it have `tail` also?

**Comment by tdhock** [comment]
hi @chinsoon12 thanks for the idea to use wc, that would probably work for my purposes

**Comment by mattdowle** [comment]
Windows 10 has the Linux subsystem built in now,  so `tail -1` and everything else is now portable on Windows too.   Since that's the direction of Windows, I don't think we should build this in to `fread`.
https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

Building `tail` into `fread` wouldn't be too hard in simple cases, but in edge cases of invalid csvs or even valid but complicating quoted fields, the jump point wouldn't be correct.  There's a concept of the head position which must be handed over between chunks and if there's any problem there, the head position continues to reread the next chunk from the proper jump position which has lineage from the start of the file.  This ensures that only absolutely correct jump points are used.  Adding complexity for this `tail -1` feature is possible, and may not be even that hard, but there's just so much else to do given that Linux is native in Windows now.

**Comment by jangorecki** [comment]
only `tail` command will also get rid of headers, to retain headers you can use the following:
```r
fread(cmd=sprintf("(head -n1 && tail -n1) < %s", "file.csv")
```
