### ISSUE TITLE
structure( , class=) is slower than using class<-

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3280]
As it's said in the title, `structure()` does more than simply assigning a class to an object, so it's generally better to avoid using `structure`. The fix is as simple as it is minor.

**Comment by mattdowle** [comment]
I seem to remember from way back that `class<-` was slower than `structure(,class=)` because `class<-` did several deep copies.  I don't doubt you're right now but it would be nice to have concrete test or a pointer to some advice from r-devel or something.  If I am remembering correctly, when did this change in R happen: was it before or after 3.1.0?
