### ISSUE TITLE
DT[ , {}] should return DT, consistent with DT[ , ]

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3313]
Follow-up to #2142 and related to #2876... in the original issue I said:

> I guess I would expect this to just return DT since that's what DT[ , ] does

But the fix I filed returns `NULL`, which I don't think makes sense

**Comment by jangorecki** [comment]
If talking about consistency...
```r
is.null({})
df = data.frame(v1=1, v2=2)
with(df, {})
```

**Comment by mattdowle** [comment]
Yes I think I agree with `DT[, {}]` returning `NULL` as it does currently.  As Jan wrote: `is.null({})` is true.
`DT[ , {}]` is different to `DT[,]` because `j=` is provided in the first case, but is missing in the second.  So I don't see the consistency argument there.
We sometimes use `{}` to do one or more side-effects and then return nothing (`NULL`); i.e. grouping just for its side-effects only.  In those cases we might do something like `DT[, { side-effect1; side-effect2; NULL }, by=]`.  The last value inside `{ ... }` is the `{}`'s value.  Empty `{}` having value NULL seems reasonable and is consistent with j's value being returned.

**Comment by mattdowle** [comment]
Let's close for now.  Current behavior has been justified so we'll go with no change.
