### ISSUE TITLE
Purge <- usage when not strictly necessary

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#3590]
Follow-up to comment here:

https://github.com/Rdatatable/data.table/pull/3582#discussion_r287075480

Also added to [Contributing](https://github.com/Rdatatable/data.table/wiki/Contributing)

There's a decent amount of manual clean-up to do, unless someone has as better regex for catching the valid `<-` usages:

```
grep -r "<-" R | wc -l
628
```

I wonder how feasible it is to just blanket replace & then patch in the `=` that cause errors because `<-` is required 🤔

**Comment by jangorecki** [comment]
IMO this is not really that important stuff. I prefer to use `=`, but when I see `<-` around, then I align to style in the file that I am writing to. AFAIR top level functions definitions uses `<-`.
There is not really any harm (as opposed to what is widely preached) to have both, assuming people who read data.table code knows R. The harm might be only for newcomers to R language, to whom those preaches are targeted to. Can we close this one?

**Comment by MichaelChirico** [comment]
I don't really notice much myself, but the linked comment and this commit: https://github.com/Rdatatable/data.table/pull/3580/commits/50243432f2c20310107989606d56ab52fab28ad4

led me to file this in the spirit of consistency

**Comment by mattdowle** [comment]
Like @jangorecki, I don't think I would have put effort into this either. But now Michael has, it's quite nice to get this out of the way. It should make PRs easier/faster, particularly as we see new contributors hopefully.
Using `=`, we don't need to worry about the danger of `x<-3`; i.e. `x<-3` does not assign 3 to x,  but it compares x to -3.  And since assignment is a function in R which has a value (and 3 is coerced to TRUE silently),  this error can go undetected.  Using `=` we don't need to implement and maintain quality control checks to ensure spaces are around every `<-`. I wonder how many of the people who've been told to use `<-` realize this.
