### ISSUE TITLE
data.table 1.12.2 using 1 threads

### ISSUE THREAD

**Issue by sumersao** [Rdatatable/data.table#3695]
I'm using R 3.6, and the following line of code produced the following error:

Line: 

library(data.table)

Error:
**********
This installation of data.table has not detected OpenMP support. It should still work but in single-threaded mode. If this is a Mac, please ensure you are using R>=3.4.0 and have followed our Mac instructions here: https://github.com/Rdatatable/data.table/wiki/Installation. This warning message should not occur on Windows or Linux. If it does, please file a GitHub issue.
**********

I'm currently running my code on a linux server, so I reported the issue!

**Comment by MichaelChirico** [comment]
@sumersao thanks for the report. Could you please share more details about your machine? e.g. from `sessionInfo()`

**Comment by jangorecki** [comment]
no feedback after few months, closing, will re-open if issue still exists and requested details will be provided.

**Comment by zeomal** [comment]
Reopening this, as I have a similar issue. `data.table` does not detect OpenMP support with the default `gcc` compiler installed.

Output of `sessioninfo()`, after installing `data.table` with after removing `gcc72` using `sudo yum erase gcc72`, because as per this [Stackoverflow](https://stackoverflow.com/questions/48576682/r-and-data-table-on-aws) answer, `data.table` doesn't play nice with it.

`R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2018.03

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.9

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2    yaml_2.2.1`

OpenMP is not detected with `gcc72` installed, but is explicitly mentioned at the start of compiling `data.table` in that case.

**Comment by jangorecki** [comment]
@zeomal Thanks for reporting. I don't think it is the same issue, because original report does not mention Amazon Linux, which seems to be relevant. Could you please post it as a new issue? including output of
```r
utils::install.packages("data.table", repos="https://rdatatable.gitlab.io/data.table")
## or, depends how you install devel data.table
utils::install.packages("data.table_1.12.9.tar.gz", repos=NULL)
```

**Comment by zeomal** [comment]
Hi @jangorecki , I was able to fix the issue following the instructions on [this](https://stackoverflow.com/questions/48307251/aws-linux-server-install-r-package) Stackoverflow answer. Do you want me to open an issue anyway and post the solution?

**Comment by jangorecki** [comment]
@zeomal great to hear that. No need creating new issue then. If you wish, you are welcome to improve our https://github.com/Rdatatable/data.table/wiki/Installation page.

**Comment by zeomal** [comment]
Okay, sure. I'll add something there to help people facing the same issue.

**Comment by jangorecki** [comment]
@zeomal Thank you, looks good!
