### ISSUE TITLE
fread : Specifying colClasses of file with 2 columns with same name, using col and col.1 does not work

### ISSUE THREAD

**Issue by wsrfad** [Rdatatable/data.table#3924]
Unlike readr::read_csv, if we have a file with two columns with same names , then if we want to specify colClasses for each one of them then it is not possible, as it gives error that col.1 does not exist

fread(file, colClasses(col = "character", col.1 = "character"), check.names = TRUE)

It seems the check.names = TRUE is performed later, after the file is read. Is there any workaround to help do it. I need to preserve the precision of the columns col...

**Comment by ben-schwen** [comment]
Since `colClasses` behaves like `colClasses` from `utils::read.csv` you could simply use a vector of same length of the number of columns you have.

**Comment by jangorecki** [comment]
I think @ben-schwen suggestion is quite on point here. If you have duplicated column names then a reliable way is to refer to them by location. More reliable than the names that got automatically created. Imagine if you have two `col.1` cols, should you expect the latter one will get named as `col.2` or `col.1.1`? Of course duplicated column names should be avoided in the first place. If you can't do that, then I suggest to use rely on column order.
For future please include reproducible example, then we can basically provide you a workable solution rather than just pointing it.
