### ISSUE TITLE
GForce optimize weighted.mean

### ISSUE THREAD

**Issue by renkun-ken** [Rdatatable/data.table#3977]
I'm not sure if it is possible to GForce optimize `weighted.mean`? It's quite different from existing GForce functions because it takes two variables.

**Comment by MichaelChirico** [comment]
I think it should be doable. Several other `g` functions are taking several arguments (though none taking several _vector_ arguments...)

**Comment by renkun-ken** [comment]
Yes, that's exactly what I was trying to say. It'd be great if it can be supported since I use a lot, one `weighted.mean` in the call makes everything broken, sometimes I have to single out this and merge later.

**Comment by myoung3** [comment]
+1 for this. The current workaround is to first take a product and assign it a new column, then doing the sum in a subsequent by-group call.

**Comment by ben-schwen** [comment]
I took a look into this and we have basically two options.

1. Write everything as a new gforce function
2. Implement it like this `gweighted.mean = function(x, w, ..., na.rm=FALSE) { if (is.null(w)) gmean(x, na.rm) else gsum(x*w, na.rm) / gsum(w, na.rm)}`

## Advantages / Disadvantages
Option 2 is easy maintenance since it dispatches everything onto `gsum`/`gmean` but is less verbose and might return confusing error messages/warnings. 

Benchmarking both, it turns out that option 2 is also faster than option 1 (at least with a naive implementation similar to `gvar`/`gsd`) since `gsum` is heavily optimized. However, option 2 is numerically more stable.
