### ISSUE TITLE
remove check for R built version in onLoad

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4009]
I think we should remove the following check
https://github.com/Rdatatable/data.table/blob/fc8d0790d4319ec451b40a965319c2378e9a2333/R/onLoad.R#L30-L34
It was added as a port of https://github.com/Rdatatable/data.table/pull/3972 to improve consistency in checking for recent R version where `cbind` and `rbind` are capable to dispatch to class methods.

The version match is not always the case, for example R-devel binaries on CRAN might have been built using R release version. This was reported in https://github.com/r-hub/rhub/issues/310

**Comment by mattdowle** [comment]
But if we remove it, how to give the message that it doesn't work.  Because it doesn't work.

**Comment by mattdowle** [comment]
I've confirmed that `packageDescription()$Built` is not the version of R used to run `R CMD build` and create the package `tar.gz`, or `.zip` on Windows.  What `Built` really refers to is the version of R used to `R CMD INSTALL` the package. And it is the version of R used to install the package which is the version of R that executes the `if()` in NAMESPACE.  Which is why to use data.table 1.12.6+ in R 4+, it must be installed using R 4+ too.

The error message is correctly using the word "installed using" for this reason.

`This is R 4.0.0 but data.table has been installed using R 3.6.1. The major version must match. Please reinstall data.table.`
