### ISSUE TITLE
Question on join execution time 

### ISSUE THREAD

**Issue by quang-do-addactis** [Rdatatable/data.table#4013]
The following benchmark suggests that the join operation of pydatatable is much faster than Rdatatable: https://h2oai.github.io/db-benchmark, while the pydatatable is supposed to mimic the core algorithm of Rdatatable. 

What could make such a big difference? Could we implement it in the future version of Rdatatable?

**Comment by jangorecki** [comment]
I believe that pydatatable will use more parallelism during the join. In R data.table we do find order in parallel but the rest of joining in single threaded. Also the difference was not really that big. Actually it was small enough that variance in pydatatable join timings makes it sometimes slower than R's data.table. See related report in pydatatable repo: https://github.com/h2oai/datatable/issues/2161
What is more important I think is that pydatatable can approach to join 1e9 data size, because it supports on-disk data storage. On-disk storage in R data.table is on the road map. Having more parallel join, I would love to, but looking at those timings, it doesn't seems to be the priority. We should also note that this join questions are pretty basic. I the benchmark we aregoing to add advanced join questions, those will stress joining algorithms better.
