### ISSUE TITLE
fwrite to gain select argument, like fread.

### ISSUE THREAD

**Issue by artidata** [Rdatatable/data.table#4178]
_Originally posted by @artidata in https://github.com/Rdatatable/data.table/issues/4177#issuecomment-574921160_

I didn't find it in documentation, nor that I find other argument with such behavior.

**Comment by AdrianAntico** [comment]
@artidata I believe you can write you code as such to achieve what you're looking for... 
```
data.table::fwrite(data[, .SD, .SDcols = names(data)[c(1,4:10, 15)], file = "bla.csv") 
```

**Comment by MichaelChirico** [comment]
Hey @artidata I re-opened the other issue. Closing this one as duplicate.

@AdrianAntico this was noted in the original issue -- the approach you give is memory-inefficient since it requires creating a copy of the object, prohibitive if `data` is massive. The request was better-fleshed-out there, that this request is about memory efficiency.

**Comment by AdrianAntico** [comment]
@MichaelChirico Interesting... I assume then that currently the optimal solution would be to NULL out the columns in a merge?

```
merge(data1[, ":=" (bla1 = NULL, bla2 = NULL, ...)], data2[, ":=" (bla1 = NULL, bla2 = NULL, ...)], by= blabla, all = FALSE)
```
