### ISSUE TITLE
Is setkey useful for tasks other than subsetting as well?

### ISSUE THREAD

**Issue by hope-data-science** [Rdatatable/data.table#4224]
We know know when we have to do group computation, data.table is much faster than other tools.I have read `set*` functions and learn that it is most useful for entry filtering by row. Except for that, I want to know if this key could do more amazing things faster. Any hints?

Thanks.

**Comment by MichaelChirico** [comment]
Hi @hope-data-science!  Thanks for the issue!

We try and use this Issues tracker for bug reports, documentation requests, and feature requests, rather than general advice. You might try the `#rdatatable` tag on Twitter for that, or `[data.table]` tag on StackOverflow if you have a more specific question about using `setkey` in a given example.

You can check the Wiki here for a plethora of articles/presentations which might help to answer your question:

https://github.com/Rdatatable/data.table/wiki

More specifically, there's this vignette specifically about `setkey`:

https://cran.r-project.org/web/packages/data.table/vignettes/datatable-keys-fast-subset.html

If this doesn't answer your question, please come back as that would likely mean there's a gap in our documentation that we'd want to fill.

**Comment by jangorecki** [comment]
@hope-data-science It is very useful for other tasks. `setkey` basically sorts dataset, and there are virtually unlimited cases that will benefit (_groupby_, _join_), or even require ordered data (_rolling statistics_). Examples below.
- groupby benchmark
  - unsorted: https://h2oai.github.io/db-benchmark/groupby/G1_1e9_1e2_0_0_basic.png
  - sorted: https://h2oai.github.io/db-benchmark/groupby/G1_1e9_1e2_0_1_basic.png
- dplyr speed up by pre-sorting data: https://github.com/tidyverse/dplyr/issues/4406

**Comment by hope-data-science** [comment]
Thank you for the professional response. I am currently trying to write a wrapper for data.table (https://github.com/hope-data-science/tidydt), and using `by` or the group operations. This could save the original order of course, but I have no idea if it will be faster if I simply use `keyby`, or set keys internally. Any hints?

Thanks.

**Comment by jangorecki** [comment]
If you do groupby by same columns multiple times then `setkey`, few groupby (or one `groupingsets`), and `setkey` again to bring back original order. If you only do single groupby operation then  I would stick to `keyby`, for simplicity of code, benefits, if present, are likely to be marginal.

**Comment by hope-data-science** [comment]
This is a very,very professional answer. I think most of the time we just group by one time, only if we need it more will it became more economic to set the keys. It depends on the task. I find it hard to do trade-off and make it wise.  `keyby` is robust, I should consider using it. I should learn more about how to use key correctly in data.table. Thanks.
