### ISSUE TITLE
setkey vs setindex

### ISSUE THREAD

**Issue by hope-data-science** [Rdatatable/data.table#4273]
As I read the vignette in <https://cran.r-project.org/web/packages/data.table/vignettes/datatable-secondary-indices-and-auto-indexing.html>, I'm curious on about some questions and want to ask: Should I always use `setindex` over `setkey`? As the former is faster, reusable and flexible. Is there any circumtances that I should use `setkey` instead of `setindex`?

Another question: Is `keyby` and `on` automatically gives the data.table a key and index respectively? I could see the usage like `ans <- flights["JFK", max(dep_delay), keyby = month, on = "origin"]`. So `on` argument is doing everything invisibly. In the "ans" variable I could find a key but not any indices. Why?

Can I use `on` and `by` on the same column instead of using `keyby`?

**Comment by shrektan** [comment]
I believe a better place to ask questions is Stackoverflow. However, since you've already asked, I will to answer some.

> Should I always use setindex over setkey? As the former is faster, reusable and flexible. Is there any circumtances that I should use setkey instead of setindex?

1. This may not answer your question but you don't really need to consider the performance issues in most of the circumstances unless your data is really that large. The reason is data.table is just that fast.
1. Personally, I rarely need to call `setindex()`. The reason is simple, it will be created automatically whenever I need it.
1. So my answer is, you should always use `setkey()` especially when your data is mainly used with the "key". The reason is it's easier to use as you don't need to call `on` every time.

> So on argument is doing everything invisibly. In the "ans" variable I could find a key but not any indices. Why?

1. Again, do not worry about the indices. `on` will set the indices (if the column are not key) for the calling data.table respectively. In your context, it's `flights`.

>  Is keyby and on automatically gives the data.table a key and index respectively?

1. As answered above, I don't think you really need to know the existence of the "index". OK, this doesn't really answer your question, again.
1. When you set `keyby=` instead of `by=` you are guaranteeing that the resulting table will have a `key`. In contrast, `by=` guarantees a result with the original order of `by=` remained.

> Can I use on and by on the same column instead of using keyby?

1. Depending on you want to preserve the original order or want to have a data.table with key.

**Comment by hope-data-science** [comment]
Thank you so much for the professional answer. Because there is a whole vignette talking about this, so I take it very seriously. But I think `data.table` has optimized most of the processes already. Thank you.

**Comment by shrektan** [comment]
You are welcome. Once you build the right inner model of how data.table works, I believe you will be amazed by such a wonderful and powerful tool `data.table` is, like I did. Hope you find it useful for your work. 😄
