### ISSUE TITLE
Documentation of `by` about its order

### ISSUE THREAD

**Issue by sindribaldur** [Rdatatable/data.table#4281]
It could be argued that the document of `by` could be clearer when it comes to answering the question *[Does data table guarantee the same order after group by calculation?](https://stackoverflow.com/q/60549556/4552295)*

It says
> [...] order of the rows within each group is preserved, as is the order of the groups.

Wouldn't *row order is preserved* be enough and also clearer since the data.table isn't necessarily ordered by groups already (as the example in the linked question).

**Comment by atrayees** [comment]
#5967

**Comment by Nj221102** [comment]
Hi @MichaelChirico @tdhock @jangorecki i was going through the issues related to .BY documentation because i am working on #5389 so thought i can do multiple issues in the same PR, as last PR on this issue was closed finding no need for change in the existing doc, i was thinking that we should close this issue. 

or we can do some change like removing the `as is the order of the groups.` part from the existing doc if it seems right, what do you think ??

**Comment by tdhock** [comment]
> Wouldn't row order is preserved be enough and also clearer since the data.table isn't necessarily ordered by groups

no I don't think it would be enough, nor clearer.

the documentation is clear enough as is. the order of the groups is preserved, meaning the same order in the input is preserved in the output.
