### ISSUE TITLE
j = get("col") alone is inconsistent to mget("col")

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4314]
It might have been added for convenience but it breaks consistency.
`d[, get(v1)]` translates to `d[, c1]` as a result we are getting atomic vector rather than data.table. `d[, mget(v1)]` is handling that fine. Output from both should be identical.
```r
d = data.table(c1=c(1L,1L), c2=c(2L,2L))
v1 = "c1"
d[, get(v1)]
#[1] 1 1
d[, mget(v1)]
#      c1
#   <int>
#1:     1
#2:     1
```

**Comment by ToeKneeFan** [comment]
I might be missing something, but isn't this consistent with the fact that `mget()` returns a list of objects, whereas `get()` returns the object itself (rather than a list of length 1 containing the object) generally in base R (not just within `data.table`)? If we think of `data.table` calls as `base::with` data environments, the existing behavior seems to be consistent with base R. Naively, I would expect `d[, get(v1)]` and `d[, c1]` to give the same result, per your example.

**Comment by jangorecki** [comment]
@ToeKneeFan thanks for pointing that out. I agree.
