### ISSUE TITLE
Error checking package with R version 4.0.0 alpha

### ISSUE THREAD

**Issue by smouksassi** [Rdatatable/data.table#4347]
After searching and asking the R CRAN maintainer I could not resolve why when I check my package on win r dev: 
```devtools::check_win_devel()``` 

Vignette building fails  wich give a  WARNING   and the following message:

Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

This happens under  R version 4.0.0 alpha (2020-03-26 r78078)

Locally and current R release there is no warning or error.
I found in the past that it might be some disconnect with data. table versions/binaries etc. can you please help? or direct me to where should I submit an issue for the R win builder?

**Comment by jangorecki** [comment]
Does the issue happens only on windows platform?
If there is mismatch of data.table version vs dll, it will raise an error when attaching package, so that should not be an issue anymore.
Before submitting an issue anywhere, it is worth to make minimal reproducible example. It you cannot reproduce it locally on your windows machine and R 4.0.0 apha, then submitting to R win builder will be the best place. Unfortunatelly I don't have idea how to reach their maintainers, I would start by checking the manual of `devtools::check_win_devel()`.

I will update out CI windows box to recent devel and run it to double check if there are any issues spotted.

**Comment by smouksassi** [comment]
Hi,
I installed R 4.0 alpha locally and reinstalled all dependencies including data.table I did not get an error building the vignette.  Closing here and reporting back if there is any news from R win builder.

**Comment by jangorecki** [comment]
I checked 1.12.8 and latest devel on Windows R 4.0.0 alpha (2020-04-02 r78142) and had no issue.
