### ISSUE TITLE
Question (probably an issue) : what is the best way to join numeric values in data tables? 

### ISSUE THREAD

**Issue by vk111** [Rdatatable/data.table#4419]
Hi, there are 2 numeric fields in 2 datatables that should be joined 
Format of number is from 0.5 to 5-6 billions
It's rounded explicitly to 2 decimals
And sometimes its not joined because its a double
What is the best way to join big numbers? Its too big for integer
Thank you

**Comment by jangorecki** [comment]
Hi,
joining/grouping on double type should generally be avoided, unless doing rolling join. It is because of rounding issues of double type. If using double type for grouping and joining it is useful to be aware of `setNumericRounding` which can help on matching values that are nearly identical, by giving some tolerance.
Unfortunately I don't have good alternatives for you. What I would personally do is to map double type into unique integer, and then join on integer. This requires to have less than 2^31 of unique double values (counting in both tables).
```r
d1 = data.table(x = c(0.5, 0.55, 100, 1.00, 100, 5e9, 6e9))
d2 = data.table(x = c(0.5, 0.6, 1.00, 1.2, 100, 5e9, 6e9, 100, 5.5e9, 6e9))
ux = unique(c(d1$x, d2$x))
d1[, "y" := match(x, ux)]
d2[, "y" := match(x, ux)]
d1[d2, on="y"]
d2[d1, on="y"]
```
I hope this can help on handling your case, or similar cases of readers who will land up here. I will close this issue, as there is nothing I can think of we could do to improve that. Feel free to follow up with any ideas or questions.

**Comment by vk111** [comment]
Ok, thanks
I came up to joining them as a characters

**Comment by jangorecki** [comment]
Yes, characters as easier, you just turn your double column into character and rounding issues are gone, but it will take much more memory.
Making a map between double and integer is exaplained in code above, the `match` function precisely.

**Comment by MichaelChirico** [comment]
Another alternative is to hack your way into a `DECIMAL` type like SQL (there's also this FR for that: https://github.com/Rdatatable/data.table/issues/428)

The advantage of `DECIMAL` is that you state you know your input is accurate to exactly two decimal places.

So you can split your column into:

```
3339439.34 -> (3339439, 34)
```

The decimal part can be stored as `integer` and the integer part can be stored either as `integer` or as `integer64`. This should be more memory efficient than storing as `character`.

**Comment by vk111** [comment]
Hi @jangorecki , 
I have tried your sample with unique integers ("ux" version) - it looks quite interesting, however when I compare it to my current very-slow-character version of doubles join - the character version is better because a very few cases are still omitted in ux version
The reason is that when the unique dictionary is created it applies the different idx for the same numbers sometimes
For example it assigns 2 different idxs for the same number 4162400000
> ux[c(25187,4563)]
[1] 4162400000 4162400000

@MichaelChirico I will try that solution with decimal - I know what is it - I used it before but the thing is - I always initialized them with the characters initially and then you can work with them with operators +,- and etc like with the usual double
like a = as.decimal('1.1'); b = as.decimal('2.2'); c = a + b // c = 3.3
I am not sure that it will works automatically for doubles in my case - like I am not sure that it will distinguish correctly the decimal part but I will try

Thanks,

**Comment by jangorecki** [comment]
Are you sure that those 2 different ids are different numbers?
AFAIU that would mean a bug in `base::unique`. They may look identical, but they may not be. Does
`identical(ux[25187], ux[4563])` return TRUE?
If you use `dput` for comparing double type be aware of https://stat.ethz.ch/pipermail/r-devel/2020-February/079087.html
