### ISSUE TITLE
internal anyNamed no longer returns false?

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4424]
According to codecov the follow line is no longer visited:
https://github.com/Rdatatable/data.table/blob/dd7609e83132e19c9be80d71c73e8a8f95e19b27/src/assign.c#L665
Most likely the function may no longer return false (unless we have poor coverage of it), which is probably a result of switching codecov environment from R 3.6 to R 4.0. We might want to revisit use of `anyNamed` function.

**Comment by tlapak** [comment]
Unfortunately, I don't have the time to implement and test a fix but I did have the time to look through the sources and was curious. Maybe this helps.

The function can still return false, I guess, just not when it's called on a non-empty list. But that's currently all that it's used for. Thing is that with reference counting turned on, MAYBE_NAMED checks the reference count and SET_VECTOR_ELT bumps up the reference count of the element it sticks into the list so that it's always at least one. With reference counting turned off, the named attribute _doesn't_ get set. So you'd need to branch based on reference counting yes/no. Or rip out the test one way or another.
