### ISSUE TITLE
creating .R directory and Makevars file

### ISSUE THREAD

**Issue by Fenrir26** [Rdatatable/data.table#4437]
Hello, Im trying to get openmp support on my Mac by following the instructions here 
https://github.com/Rdatatable/data.table/wiki/Installation

But I can't seem to properly create a makevars file and put it in .R because im consistently stalled at step 3

Any help would be greatly appreciated!
`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

`#` `Output of sessionInfo()`

**Comment by jangorecki** [comment]
Hello,
You haven't wrote what exactly you are getting stuck at in step 3.
Are you able to try `gcc` instead of `clang`?

**Comment by Fenrir26** [comment]
The instructions say to add the lines from step 3 to the file ~/.R/Makevars but every time i try in terminal it says no such file or directory. 

Leads me to believe I haven't properly created .R or ~/.R/Makevars but this is all new to me.

**Comment by MichaelChirico** [comment]
you can run `mkdir -p ~/.R` to make the directory whether or not it exists.

then you can create the file before trying to edit it:

`touch ~/.R/Makevars`

you could also do both steps in R if you prefer:

```
dir.create('~/.R')
file.create('~/.R/Makevars')
```

**Comment by Fenrir26** [comment]
Thanks! I've done that and so now do i just add the lines from step 3 to the makevars file in R?

**Comment by jangorecki** [comment]
You can use any text file editor and just edit `~/.R/Makevars` file. From R you can use `writeLines`, or `cat` to file.

**Comment by Fenrir26** [comment]
Thank you! I've done all of that and installed gettext but i still can't get data.table to load without the openmp warning about it being single thread. Is there something else I should try?

**Comment by jangorecki** [comment]
`gcc` instead of `clang`

**Comment by Fenrir26** [comment]
same result with gcc instead of clang.

**Comment by jangorecki** [comment]
@Fenrir26 I think you have to help us to help you, otherwise there is not much we can do.
Please try recent version of data.table. Provide the content of your `.R/Makevars` file, as well as command(s) that you are using for installation and full console output. Take care of running installation in a fresh R session, just in R console, rather than RStudio or other IDE.

**Comment by jangorecki** [comment]
@Fenrir26 as we haven't heard back from you till June, I am going to close this issue. If you are able to provide required information then we will reopen this issue. As for now, having no details, there is nothing we can do.

**Comment by aguscamacho** [comment]
Hi, 
I have a fairly similar problem with Makevars. Need to change it to get R to use the gfortran on a mac air book pro, in order to make use of the package NicheMapR.

Following this site's indications: https://www.r-bloggers.com/2021/03/gfortran-support-for-r-on-macos-2/

I ran the following commands in the terminal ( i am the owner and ,supposedly, the administrator), but got permission denied for creating the file
agus@MacBook-Pro-de-agustin ~ % mkdir -p ~/.R
agus@MacBook-Pro-de-agustin ~ % ~/.R/Makevars
zsh: permission denied: /Users/agus/.R/Makevars

Then i tried in Rstudio:
> dir.create('~/.R')
Warning message:
In dir.create("~/.R") : '/Users/agus/.R' ya existe
> file.create('~/.R/Makevars')
[1] TRUE
> file.exists('~/.R/Makevars')
[1] TRUE

So the file exists, but the Mac's finder search wont find any file with Makevars in the name or , anywhere in the mac (this is so frustrating). I can though, find it using the command "go" in the finder commands for the folder name. The file Makevars is  actually there, is just the search bar that wont find it. 

I tried to update the file, following instructions:
from R the following command supposedly does it, 
writeLines("FC      = usr/local/opt/gcc/bin/gfortran
F77     = /usr/local/opt/gcc/bin/gfortran
FLIBS   = -L/usr/local/opt/gcc/lib",'~/.R/Makevars')

But it executes and nothing changes in the file.

So i changed it manually opening the file using text edit.

Then, i test everything did work installing
install.packages("cluster", type = "source")
it goes well

but when i try to install
devtools::install_github('mrke/NicheMapR')
i get
Downloading GitHub repo mrke/NicheMapR@HEAD
✓  checking for file ‘/private/var/folders/9d/rc00x3p91_92g0f0p55hst5r0000gn/T/RtmpftnYNb/remotes180a5c6eb3a1/mrke-NicheMapR-deb13eb/DESCRIPTION’ ...
─  preparing ‘NicheMapR’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘NicheMapR_3.1.0.tar.gz’
   
* installing *source* package ‘NicheMapR’ ...
** using staged installation
** libs
usr/local/opt/gcc/bin/gfortran -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c AACOMMONDAT.f -o AACOMMONDAT.o
make: usr/local/opt/gcc/bin/gfortran: No such file or directory
make: *** [AACOMMONDAT.o] Error 1
ERROR: compilation failed for package ‘NicheMapR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/NicheMapR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/NicheMapR’
Warning messages:
1: In readLines(old_path) :
  incomplete final line found on '/Users/agus/.R/Makevars'
2: In readLines(old_path) :
  incomplete final line found on '/Users/agus/.R/Makevars'
3: In i.p(...) :
  installation of package ‘/var/folders/9d/rc00x3p91_92g0f0p55hst5r0000gn/T//RtmpftnYNb/file180a48751948/NicheMapR_3.1.0.tar.gz’ had non-zero exit status

So it did not work..what could it be?

**Comment by GQFrank92** [comment]
Same problem with you. Regarding no Makevars: go to your finder find:~/.R directory, then use text compiler to creat a new file called”Makevars”, open it and copy the code in  https://github.com/Rdatatable/data.table/wiki/Installation, then save and exit. Go back to R, run: remove.packages(“data.table”) and reopen R, and run: install.packages(“data.table”, type = “source”). (I’ve no idea how to create Makevars at first, after some attempts, it’s easy, just like create a text file and name it “Makevars”, and after  that **you need to remove “data.table” packages already installed and reinstall it.**)
