### ISSUE TITLE
memrecycle when used for intentional valid coercion should not warn

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#4503]
Current behavior is like
```r
data.table(a=1:2, b=0L)[2L, b:="2"][]
   a b
1: 1 0
2: 2 2
#Warning message:
#In `[.data.table`(data.table(a = 1:2, b = 0L), 2L, `:=`(b, "2")) :
#  Coercing 'character' RHS to 'integer' to match the type of the target column (column 2 named 'b').
```
There is a comment
```
    // this "Coercing ..." warning first to give context in case coerceVector warns 'NAs introduced by coercion'
```
Do we really want to raise warning here? If RHS is of not-coercible to LHS we get a warning for that
```r
data.table(a=1:2, b=0L)[2L, b:="asd"]
#Warning messages:
#1: In `[.data.table`(data.table(a = 1:2, b = 0L), 2L, `:=`(b, "asd")) :
#  Coercing 'character' RHS to 'integer' to match the type of the target column (column 2 named 'b').
#2: In `[.data.table`(data.table(a = 1:2, b = 0L), 2L, `:=`(b, "asd")) :
#  NAs introduced by coercion
```
If we want to retain the warning even for coercible character, then we should add an option internally to disable that warning, so `memrecycle` can be used for such coercion.

**Comment by jangorecki** [comment]
warning is disabled when `memrecycle(numcol=0)` which seems good balance, in #4491

**Comment by mattdowle** [comment]
The idea was that if user code is assigning character "2" into an integer column, then it's more likely to be a mistake that the user wants to be warned about. If it's correct then it's inefficient. So the idea was to nudge the user to need to include `as.integer()` on the right hand side so it's clear to users of their code that an inefficient coercion is happening.   I thought we want to be stricter in data.table: either types match or the user sees a warning.
Also, because the 2nd warning (R's warning) doesn't include any context to help the user, the idea was to generate a more helpful warning first to include the context, so that if the `NA's introduced` does occur, then the user has some context from the first warning (i.e. which column).

**Comment by jangorecki** [comment]
Yes, I mentioned above, previous warning is [suppressed conditionally](https://github.com/Rdatatable/data.table/pull/4491/files#diff-22b103646a1efab9bbfc374791ccfc3fd1422eefc48918a3e126fc2f30d1f572R842-R844) by providing `colnum=0` in when [calling `memrecycle` from C `coerceAs`](https://github.com/Rdatatable/data.table/pull/4491/files#diff-3e04e056edbdc0f772b0ffd1c93cef1187209f37276d40d2a281d9b989398a73R372
). So all previous warnings stays valid.

**Comment by mattdowle** [comment]
Ok thanks. So the title needs updating, and the text of bullet 8 too in #4491?  Is there a better name than `colnum=0` to convey this?

**Comment by jangorecki** [comment]
To make the change minimal I re-used `memrecycle` for generic coercion. This lead to re-using existing argument rather than introducing new one. Whole change could probably be implemented more nicely but diff would be much bigger.

**Comment by mattdowle** [comment]
I still don't understand the title.  What is intentional valid coercion?  How do we know if it is intentional or not?  Requiring the user to write `as.integer()` on the RHS, to avoid the warning, is the way the user can make it clear the coercion is intentional.  Maybe it's a typo in the title: internal vs intentional?

**Comment by jangorecki** [comment]
Intentional coercion is the one invoked from `coerceAs`, all the other calls to `memrecycle` assumes unintentional so they will raise warning when coercing `"2"` to integer.

**Comment by mattdowle** [comment]
But `coerceAs` is a function called by `nafill()` internals. So I don't see how the coerce can be intended by the user when they aren't calling it directly.

**Comment by jangorecki** [comment]
Agree that naming this intentional is confusing. By intentional I meant that using `memrecycle` for coercion of valid coerce-able input should not raise warning during internal use for coercion.
So `data.table(a=1:2, b=0L)[2L, b:="2"][]` still raises warning but specially invoked (less strict) `memrecycle` does not raise warning anymore.

**Comment by mattdowle** [comment]
> coercion of valid coerce-able input should not raise warning during internal use for coercion.

The was the question of this issue and I think there should be warning.

Currently in PR 4491, and I guess for `nafill` before that PR too, we have : 

```R
> nafill(c(2,NA,4,5), fill="3")
# [1] 2 3 4 5
```

i.e. no warning. The type coercion from character to numeric happens silently.  That's inconsistent with `:=` and I don't see why 'nafill()` should be different. I wrote above:

> The idea was that if user code is assigning character "2" into an integer column, then it's more likely to be a mistake that the user wants to be warned about; e.g. assigning completely the wrong RHS by mistake and the only clue to that would be the type mismatch. 

The title of this issue doesn't mention types, so let's go into more detail on that.

`1` (by default type `double` in R) is coerceable to `1L` without any copy and therefore without any speed penalty. That's partly the raison d'etre for `memrecycle`; i.e. it does zero-copy coercions in some cases. We feel that the inconvenience of asking users to get `1` vs `1L` right is a step too far so we allow that without warning for convenience and we implemented zero-copy coercion so there wouldn't be any speed downside.   It's not just speed though, it's the likelihood of the type mismatch actually being due to user error which we want to tell the user about via a warning.

Coercing `"2"` to `2L` (character to integer) is different to `1` coerced to `1L`. i) it's much more likely that the character "2" being assigned is actually a user mistake, perhaps arising from a mistakenly selected column or variable.  ii) there is no zero-copy coerce in the case of character to integer so there's a performance penalty; i.e. it traverses the character string, coerces it, and allocates the integer result. It may be possible to implement zero-alloc in that case, especially easy in the case of `"0"`-`"9"`, but case (i) is still the dominating consideration.

So for now, I'm going to close this issue and remove the `numcol==0` switch in PR 4491.  I'll add some notes to NEWS so users know the thinking on this so they can comment if necessary, an 'and also' comment to the comment in `memrecycle`, and change the title to include 'character' type because it was really about 'character' to 'integer'/'double' and not other valid coercions, iiuc.

```
// this "Coercing ..." warning first to give context in case coerceVector warns 'NAs introduced by coercion'
// and also because character to integer/double coercion is often a user mistake (e.g. wrong target column, or wrong
// variable on RHS) which they are more likely to appreciate than find inconvenient
```

After this change in the PR, we have the following PR behaviour:

```R
> nafill(c(2,NA,4,5), fill="3")
[1] 2 3 4 5
Warning message:
In nafill(c(2, NA, 4, 5), fill = "3") :
  Coercing 'character' RHS to 'double' to match the type of target vector.
> nafill(c(2,NA,4,5), fill=3)
[1] 2 3 4 5      # no change, no warning as before
> nafill(c(2,NA,4,5), fill=3L)
[1] 2 3 4 5      # no change, no warning as before
> nafill(c(2L,NA,4L,5L), fill=3)
[1] 2 3 4 5     # no channge, no warning as before
> nafill(c(2L,NA,4L,5L), fill=3.4)
[1] 2 3 4 5     # no change, warning from memrecycle due to PR 4491 reusing memrecycle from coerceAs
Warning message:
In nafill(c(2L, NA, 4L, 5L), fill = 3.4) :
  3.400000 (type 'double') at RHS position 1 truncated (precision lost) when assigning to type 'integer' (target vector)
```

If I've misunderstand or got something wrong, please reopen with an explanation as to why `nafill` should not have a warning in the first example.
