### ISSUE TITLE
rhub - Package required but not available: 'data.table'

### ISSUE THREAD

**Issue by cbailiss** [Rdatatable/data.table#4521]
This is more an FYI than a bug report.

I have used rhub to test one of my packages (pivottabler), but one of the rhub checks fails with package not available.  This has been occurring for a few weeks at least.

This error doesn't happen for the Linux builds on r-hub.  It also doesn't occur on my own windows machine or on CRAN/win-builder, so seems specific to r-hub.  Obviously you don't maintain rhub, but I thought you may wish to be informed so you are aware.

If by chance you are aware of this issue or see an obvious fix, that would be helpful, but mainly reporting FYI.

Summary info below and build log attached in a couple of different formats (error is around line 680).
[Status for build.txt](https://github.com/Rdatatable/data.table/files/4722106/Status.for.build.txt)
[Status for build.docx](https://github.com/Rdatatable/data.table/files/4722107/Status.for.build.docx)
[Status for build (with line numbers).txt](https://github.com/Rdatatable/data.table/files/4722108/Status.for.build.with.line.numbers.txt)

## Build Info

| Info |  |
|---|---|
| Build ID: | pivottabler_1.4.0.9999.tar.gz-d2932efaf5f3420ca66b3cfb5d725431 |
| Platform: | Windows Server 2008 R2 SP1, R-devel, 32/64 bit |
| Submitted: | 2 minutes 49.4 seconds ago |
| Build time: | 2 minutes 39.1 seconds |

## ERRORS
checking package dependencies ...
ERROR  Package required but not available: 'data.table' 
See section 'The DESCRIPTION file' in the 'Writing R Extensions' manual.

**Comment by MichaelChirico** [comment]
Most likely that is because many of the `data.table` sources in CRAN are in ERROR at the moment:

https://cran.r-project.org/web/checks/check_results_data.table.html

There is a patch release forthcoming to address that; I'm not sure if there's an exact timeline yet.

**Comment by jangorecki** [comment]
Thanks for informing us.
On CRAN I see all data.table binaries available except for Windows R-devel. In such case, package should be compiled from source. If there are any problems with that, please let us know, I am not aware of any. Unfortunately I don't know why r-hub is not able to build from source.

We do publish Windows binaries for R-devel ourselves, but this is for our development version, not 1.12.8. If you don't have to stick to 1.12.8 you can append `https://Rdatatable.gitlab.io/data.table` to your `repos` argument, it will then use development data.table. Binaries are available for R 4.0.0 and R 4.1.0 (devel).

I believe that failure on Windows is caused by breaking change in R-devel specifically on Windows, reported some time ago on R-devel https://stat.ethz.ch/pipermail/r-devel/2020-May/079558.html It has not been answered yet. Therefore we are preparing patch release to "relax" our tests, so it can pass tests, without really understanding why we have to do it...
