### ISSUE TITLE
 dt_win_snprintf test 9 failed: snprintf:

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#4545]
Follow-up to #4531 

Seeing this in dev now on my Mac:

```
.Call(data.table:::Ctest_dt_win_snprintf)
Error: dt_win_snprintf test 9 failed: snprintf:
```

So test 2141 fails.

Should we be just skipping these tests on Unix?

**Comment by mattdowle** [comment]
Shouldn't skip on unix. Better to investigate why as it might happen on Windows too under different circumstances perhaps.

**Comment by mattdowle** [comment]
@MichaelChirico could you try that branch in PR #4555 please and post the output.  My guess is that it will fail on the `snpf9 %d clib error` because the `vsnprintf` in the clib on your machine/compiler is not fully C99 compliant by returning -1 when the string is longer than n. It should return how long n needs to be for the output to fit. That truncation is what test 9 is testing. If you pass -std=c99 to the compiler options then it might start to work.   If that is the problem then we need to make it work somehow even when the vsnprintf function is not C99 compliant and returns negative when chopped to n.
