### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by ale07alvarez** [Rdatatable/data.table#4650]
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘data.table’ in library.dynam(lib, package, package.lib):
 shared object ‘datatable.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’

The downloaded source packages are in
	‘/private/var/folders/1r/t1rym3x129db_2p73qttrw600000gn/T/RtmpY3bPyL/downloaded_packages’
R data.table package has been updated to NA (1.12.8)
Warning message:
In utils::install.packages(pkg, repos = repo, type = type, lib = lib,  :
  installation of package ‘data.table’ had non-zero exit status

`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

`#` `Output of sessionInfo()`

**Comment by ale07alvarez** [comment]
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default

BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_3.6.3      tools_3.6.3         data.table_1.12.8

**Comment by mattdowle** [comment]
Thanks. Seems the same as #4640. If you have time to wade through it all, it would help us anything you can work out. Otherwise, we'll try and get to it.
We don't know the fix yet.  Is pkg-config installed and does it return 1 (see that issue for output). Perhaps try upgrading to R 4 for which the macos binary on CRAN appears to be available and passing.  Our Travis OSX build here on GitHub is passing fine and I wonder if you can get the binary from that, or see what's different.  Mind you, a binary built using R 4 won't work in R 3, so that probably doesn't help you.
