### ISSUE TITLE
Enable adding columns to NULL data.table

### ISSUE THREAD

**Issue by gorodnichy** [Rdatatable/data.table#4732]
It would be very convient to be able to do that:
```
projectile <- data.table()
projectile$angle<- c(15, 30, 45, 60, 75)  
```

Currently, This does not work (as for any `data.frame`).  See:
https://stackoverflow.com/questions/64164612/error-in-data-framex-name-value-replacement-has-1-row-data-has-0#64164676

For `data.table` there a fix : `projectile <- setDT(setDF(projectile)).`

It would be great if this line is executed at the construction time by default -  So that no error will be generated.

**Comment by ben-schwen** [comment]
Can't reproduce with `data.table 1.13.0`, since your example works out.

However, what actually errors is the call
`ggplot2::ggplot(projectile)`

**Comment by ColeMiller1** [comment]
#4597 related? Assigning rows to a ```null.data.table``` does not update the attribute ```row.names``` - there is a pending PR for that

**Comment by ben-schwen** [comment]
@ColeMiller1 Yes. PR for #4597 also solves the problem mentioned in the SO thread.

**Comment by ColeMiller1** [comment]
I will close as a duplicate because ```ggplot2``` call uncovered the bug and is covered thoroughly in other thread. 

Note, I think Ronak's suggestion in SO of making vectors and then making a real data.table makes sense (e.g. ```var1 = 1:5; dt = data.table(var1)```) compared to a ```null.data.table```


Thanks for checking @ben-schwen! I didn't have a chance to verify before posting but wanted to flag ASAP because with all of your (great!) PRs, I didn't want us to duplicate work.
