### ISSUE TITLE
value is not udpated if it is NA

### ISSUE THREAD

**Issue by msgoussi** [Rdatatable/data.table#4807]
x <- data.table(a = letters[1:5], b = NA)
x[ a %in% c("a", "c"), b := "x"]
x

**Comment by MichaelChirico** [comment]
is there any warning? at a glance you are trying to change types (NA is
logical).

try defining with NA_character_ to start instead

**Comment by jangorecki** [comment]
There is warning and is pretty clear. `"x"` was coerced to logical, which results `NA`. Suggestion by Michael is the way to go here. Sub-assign by reference cannot change type of column you are assigning to, otherwise it wouldn't be by reference, but making new column having values converted from the old one.
