### ISSUE TITLE
xtfrm change in r-devel today breaks on data.frame

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#4838]
Email to Kurt copied here.

---

Dear Kurt,

I can't find you on GitHub, but this email is copied here so that everyone in data.table team knows the status: https://github.com/Rdatatable/data.table/issues/4838.
Your change to R-devel today appears to break two data.table tests (1319.1 & 1319.2).
https://github.com/wch/r-source/commit/8696236cdc7a2be91605f048164e23430aabf0b1
Here is an example using data.frame.  Did you intend for this to break?
This will affect the checks of the data.table submission which is waiting for you to manually accept the 3 spurious not-found URLs.
```
> xtfrm(data.frame(A=8:5))   # before the change
[1] 4 3 2 1
>

> xtfrm(data.frame(A=8:5))   # after the change
Error in xtfrm.default(data.frame(A = 8:5)) : cannot xtfrm 'x'
```

Best, Matt

---

**Comment by mattdowle** [comment]
Link to #4832

**Comment by jangorecki** [comment]
Kurt [said](https://stat.ethz.ch/pipermail/r-devel/2020-December/080164.html)

> Work in progress.  Likely this will become an error: ? sort clearly says
it does not work on data frames.

I think it is best to disable those tests till 4.1 release.

**Comment by mattdowle** [comment]
Tweak yes, to get out of R's way, but not disable completely. I haven't looked closely at those tests yet, but a minimal change to keep the remaining parts of those tests working is what we normally aim to do. For example, `base::order` is used for the `y` value of those 2 tests. The `x` value could still be checked, just not using base to generate the `y` value.

Aside: where in ?sort is Kurt referring to? I searched it for the text "data.frame" and there is no occurrence. So it's not clear to me.

**Comment by jangorecki** [comment]
The problem is that behavior might be still changing till 4.1.0 as it is work in progress. So it is probably better to enable this test once WIP is over, and news item, manual will document expected behavior.

**Comment by mattdowle** [comment]
I understand that. Please read the sentence starting 'For example' again., and look at the test. Does what I'm saying make sense now?

**Comment by jangorecki** [comment]
Agree, it make sense there.
The change that Kurt is implementing may also affect `order(list(.))`, which could eventually break 1319.6, 1319.7, 1319.8.
To stay more green on CRAN I think it should be fine to disable those tests now before release to CRAN, re-enable soon after, in 1.13.5, and then align to what will stabilize in R-devel. Of course there might be other unit tests that depends on `order(list(.))`, then disabling just this group won't make use much more green on CRAN.

**Comment by mattdowle** [comment]
I don't understand why you're still using the word 'disable'. I'm suggesting keeping the tests enabled, but removing the dependency on base, by changing the `y` calls. Do we need to have a call face to face and talk it through?

**Comment by jangorecki** [comment]
OK, by "disable" I meant to disable testing vs. base order. Testing vs. fixed values is perfectly fine.
This sorting was an undefined behavior in R. I pushed this issue asking for documenting behavior of `order` on list and data.frame, or raising error, so we can reliably implement https://github.com/Rdatatable/data.table/issues/4346.

**Comment by mattdowle** [comment]
Glad that's agreed on the tests.

Please write more precisely. Here is what I mean :

> This sorting was an undefined behavior in R. 

Ok I accept that but I'm asked where. Kurt wrote "? sort clearly says it does not work on data frames."  That's a very specific statement.  It's "? sort" which is a particular page.  And he uses the word "clearly".  So, where on that page?  I wrote that I searched it for "data.frame" and I don't see any occurrence.  Is it a different manual page then?  I would like to have a look and see it.  I'm not saying it doesn't exist.  I'm not arguing that it isn't undefined behavior.  I'm asking where Kurt is referring to.

> I pushed this issue 

We _push_ to branches. We _raise_ issues.  So I'm thinking, ok there's an issue link at the end of the sentence so he probably means issue not pr.  Then I clicked the issue and there are lots of links items there (all issues, I think) but there's still some doubt in my mind whether you might have a PR somewhere on this.

> asking for documenting behavior

asking who? At first I thought you meant you were asking R-core and I expected to find a link to r-devel or similar. But issue #4346 seems to be you proposing to change to behavior of our `forder`. It had been marked breaking-change and then removed, for example.  So now I'm looking at the text in issue #4838 trying to work out how "documenting behavior" relates to the issue.

> of order on list and data.frame, or raising error, so we can reliably implement #4346.

Now, "order" is the base R function name,  so now I'm thinking maybe you do mean you're asking on R-devel after all. But if you were asking on mailing list, you would have waiting until you had posted and then linked it, so I'm not sure.  We also have `DT[order(...)]` in data.table which we optimize to call our forder, and that's what the tests that have broken are doing, so maybe you're referring to order in that context.  Or maybe you made a typo and did mean our forder here (not base R order) because the issue #4346 seems to be about changing our `forder`.

Then I look in issue #4346 again, for the 3rd time, circle back and reread (I've been on this for over 30 mins) ... and I see this in the issue : 

> forder should be a replacement for order

And I'm thinking,  why?  Again and again over the years I've repeated that data.table's raison d'etre is to be different.  I didn't want to use base R because I didn't like it.  In this case, why can't order work for data.frame?   I mean,  I know that R-core maintainers like Kurt are in a tough spot. Base R is what it is and sort on a data.frame doesn't work.  So he's making it clear and making it an error message.  Believe me, I get that.  He doesn't have the time or the code ready to make it work and to document that it works, so a good step is just to make it an error. I get that.   In data.table, what I did, was create forder and make it work on data.frame. That's different to R because data.table work, and continues to work.

I see only one good way forward : propose a patch to R-devel that makes order/sort/sort.list (whatever is really meant) work on data.frame, and document that it now works in R in R's manual pages. But let's not change our forder backwards to push people towards forderv (that seems to be what #4346 is proposing, iiuc) all in the name of matching base R behavior even if that behavior is unimplemented. Instead, make R better. There is still no PR mechanism for R despite many requests. But we can submit a text `.patch` file to Bugzilla and they will consider it. Jan - could you do that please?
 
And please write much much more clearly.

**Comment by jangorecki** [comment]
> And please write much much more clearly.

Will do. If my comments are not clear or verbose enough, then please ask. I will be happy to elaborate more. Many related information are scattered in different issue. I hope my explanation below will make it more clear.

No idea what manual page backs what Kurt said.

By "pushed the issue" I mean that I insisted for `order` df/list behavior to be clarified. Initially on R-devel mailing list, and after a month or two creating [bugzilla](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17985) for that. So yes, I _raised_ this issue to R core, twice.

>> forder should be a replacement for order

> And I'm thinking, why?

- It makes it easier for users as they don't have to learn (slightly) new API, they just add extra `f` in front and it scales better.
- Consistent with other faster base R replacements that data.table already provide: `fifelse`, `frank`, `fsort`.
- You [seemed to agree on being drop-in replacement](https://github.com/Rdatatable/data.table/pull/3817#issue-313910549
) in the past, while this of course does mean we cannot support df/list even when base R does not support that. Decision on that needs to be made before exporting `forder`. Ideally in dedicated issue #4346 rather than here.
- We have two API for fast order, `forder` and `forderv`. I think it make sense to align one of them to base order.
- Having error for `forder(a_list_var)` would resolves issues like _order(list_column) gives strange error #4214_ (note a [link to R-devel mailing list thread](https://stat.ethz.ch/pipermail/r-devel/2020-May/079500.html) there)

> But let's not change our forder backwards to push people towards forderv (that seems to be what #4346 is proposing, iiuc) all in the name of matching base R behavior even if that behavior is unimplemented.

Issue _forder should not accept list, but forderv should #4346_ came up when working on _export forder
#3447_ issue. It will be difficult to change API of a function once it will be exported so it is best to review/change API before exporting.

`forder` is not yet exported therefore it will not be a breaking change. Our internal code will need to be amended. An example can be already found in _order optimizes to forderv, uses key or index, forder more consistent to base order #4458_. In short it is something like this:
```r
## now
DT[order(a,b)] -> DT[,forder(a, b)]
## proposed
DT[order(a,b)] -> forderv(DT, c("a","b"))
```
Such a change is beneficial because it allows to use existing key/indices, assuming _lazy forder #4386_ merged. It does use key/indices already when #4458 and #4386 are merged together.
Of course we can have this kind of optimization internally and still let `forder` to work as is now.

> propose a patch to R-devel that makes order/sort/sort.list (whatever is really meant) work on data.frame, and document that it now works in R in R's manual pages

I can do but I am not sure if the API we have now in `forder` would be accepted there. _order -> forder optimization follow up #3817_ changed signature of `forder` from `forder(x,...)` to `forder(...)`. The former signature seems to fit better use case like `forder(x=DT, a, b)` because there is clear distinction between types of arguments provided. Currently in `forder` (as in base `order` always) there is no `x` argument but only `...`. The way `forder` handles df/dt is like mimicking method dispatch by investigating `..1` argument. I think there might be resistance in R core to agree on this kind of implementation. Moreover from discussion on mailing list it seems that preferred implementation would look like
```r
do.call(order, df)
```
which is very different from `forder` way, as it orders over all columns, so only the first argument passed to `...` (a data.frame) is actually used.

**Comment by jangorecki** [comment]
After looking at the source of base `order` I think it is not a good idea to introduce `forder` style API there.
Main reason is that currently base `order` evaluates its argument. By changing its API to `forder` style, it will turn it into non-standard evaluation function, and that introduces new challenges, like use of `substitute`. (You of course know it) Base R way to achieve this interface is `with(DF, order(a, b))` and using `order(DF, a, b)` doesn't bring much over the former one, yet it introduces inconsistency on how `...` arguments are being treated: `..1` in a special way comparing to remaining arguments in `...`.
Behavior proposed on mailing list, `do.call(order, DF)`, seems much more reasonable for `order(DF)` call. Personally I would choose this implementation.

**Comment by mattdowle** [comment]
I ddn't suggest introducing our `forder` style API to base R; i.e. certainly not w.r.t. `...` and delayed evaluation as you're highlighting. All I had in mind was proposing a minimal patch where `order(data.frame(A=4:1))` continues to work as it has been doing in base R; i.e. where "work" means continuing to return `4:1`.  For that, a documentation change would be needed.  Then to make `order(data.frame(A=4:1, B=4:1))` (i.e. a multi-column data.frame) work by returning 4:1 instead of the not-useful result `4 8 3 7 2 6 1 5`. In other words,  just tackle `order(DF)` and that's all.
