### ISSUE TITLE
fwrite substitutes class integer rownames by 1,2,3...

### ISSUE THREAD

**Issue by dgarrimar** [Rdatatable/data.table#4957]
`#` [`Minimal reproducible example`](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

The following R code:

```r
library(data.table)
df <- data.frame(c1 = c(1, 2, 3), c2 = c("a",  "b",  "c"))
rownames(df) <- as.integer(c(10, 20, 30)) # class(attributes(df)$row.names) 
fwrite(df, "out_fwrite", quote = F, row.names = T, sep = "\t")
write.table(df, "out_wt", quote = F, row.names = T, sep = "\t") # added for comparison
```
generates two output files, whose content is shown below:

`out_fwrite`
```
	c1	c2
1	1	a
2	2	b
3	3	c
```
`out_wt`
```
c1	c2
10	1	a
20	2	b
30	3	c
```

I noticed `fwrite` is converting the actual rownames (i.e. 10, 20, 30) to 1, 2, 3 without warning. This does __not__ happen when `rownames(df)  <- as.numeric(c(10, 20, 30))` or `rownames(df) <- as.character(c(10, 20, 30))`. This is also different from the behaviour of `write.table`.

`#` `Output of sessionInfo()`

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.2 (Nitrogen)

Matrix products: default
BLAS:   /nfs/users2/rg/dgarrido/R/R-4.0.3/lib64/R/lib/libRblas.so
LAPACK: /nfs/users2/rg/dgarrido/R/R-4.0.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.13.6 optparse_1.6.6   

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    getopt_1.20.3 
```

**Comment by mrdwab** [comment]
I wonder whether it's [this line](https://github.com/Rdatatable/data.table/blob/1eadb95ae1f2d5be5b1b6bf89d8db06450d4b9cc/src/fwriteR.c#L262) that's causing the problem:

    args.rowNames = isString(rn) ? DATAPTR_RO(rn) : NULL;

**Comment by dgarrimar** [comment]
It may be related to this:

 https://github.com/Rdatatable/data.table/blob/1eadb95ae1f2d5be5b1b6bf89d8db06450d4b9cc/src/fwriteR.c#L262

**Comment by ColeMiller1** [comment]
Thanks for the report. Interestingly, R stores the numeric, non-integer row names as characters:

``` r
DF = data.frame(x = 1)

## integer storage
rownames(DF) = 1L
class(attributes(DF)$row.names)
#> [1] "integer"

## numeric actually stored as character!!
rownames(DF) = 1
class(attributes(DF)$row.names)
#> [1] "character"
```
Some options to change behavior:

1. `write.table` simply passes `as.character(row.names(x))` to the C code. It would be simple to change `fwrite.R` to do the same and make small changes in `fwriteR.c`
2. The code @dgarrimar pointed out in `freadR.c` could be change to convert the integer row names to a pointer of character row names.
3. `fread.c` could be modified to allow for integer row names to directly be written. The would probably be the best for performance but also the most code change because the argument structure would likely need changed.

The first option seems good - I will work on a PR.

<details>
  <summary>Changes to implement option 3: </summary>

Need to switch on type of rowNames so another arg may be needed. Meaning, if it is an integer row name, we need the maximum row name value to convert to character length.

https://github.com/Rdatatable/data.table/blob/831013a8892a6d39e12bbd45aeb559ccd258bc0a/src/fwrite.c#L641-L644

Other change - need to `writeInt64` if we are doing row name for integer type.

https://github.com/Rdatatable/data.table/blob/831013a8892a6d39e12bbd45aeb559ccd258bc0a/src/fwrite.c#L875-L883

</details>
