### ISSUE TITLE
Allow env dot alias in substitute2 and [.data.table

### ISSUE THREAD

**Issue by tonyfischetti** [Rdatatable/data.table#4994]
I propose allowing for the use of `.()` as an alias to `list()` in the `env` arguments to `substitute2` and `[.data.table`, as a convenience feature. Just like in the i, j, and by arguments.

```
DT = as.data.table(iris)
tmp = "Species"
DT[, .N, tmp, env=.(tmp=tmp)] # equivalent to DT[, .N, tmp, env=list(tmp=tmp)] 
```

PR #4992 has a sample implementation repurposing the `replace_dot_alias` in `R/data.table.R` for this purpose.

**Comment by jangorecki** [comment]
Thank you for opening the issue for discussion.
While working with meta programming interface during recent PR, and also for several years just when using data.table, I came to conclusion that from the programmatic point of view (not an interactive use which is very different) it is important to make clear distinction between non-standard evaluation and standard evaluation interfaces. Having NSE on top of the argument that is meant to be used for meta programming has already bitten multiple times. OTOMH would be `.SDcols` and `with=FALSE`. One example of the complexity it generates can be seen in https://github.com/Rdatatable/data.table/pull/4174 which failed to achieve its goals.
I agree that use of `.` instead of `list` would be very nice here, but those past experiences are discoursing me to support idea of putting NSE into `env` arg. Alternatively I would prefer to just create and export
```r
. = list
```
so there is no need for introducing NSE, and users can use the following syntax without having to worry about the scope of evaluation
```r
helper = function(x, y) .(y, x)
dt[, .j, env=helper(col1, col2)]
```

**Comment by tonyfischetti** [comment]
This is helpful, now I understand more about the potential issues involved.

The problem with exporting `.()` as an alias for `list()` is that `.()` is already used in `bquote`. That's why `replace_dot_alias` checks if it's being used in `bquote`.

In the sample implementation, the env argument is evaluated immediately after replacing the `.()`
```
env = eval.parent(replace_dot_alias(substitute(env)))
```
Does your hesitation still stand if the only purpose allowing `env`'s lazy evaluation is replacing the alias? And does it still stand if it's used in `[.data.table` but _not_ in `substitute2`?

**Comment by jangorecki** [comment]
Yes it does, presented helper function will not work. I modified it a little to be more real-world use case. `env` is a tool to work around NSE in `[` add putting NSE into it makes it difficult to program with.
Moreover, use of `env` is not that much needed in the most common usage of data.table and even less in interactive use. `env` is definitely useful for packages that imports data.table, but here, IMO, three extra characters (`.` vs `list`) is not that big deal for retaining consistency.

**Comment by tonyfischetti** [comment]
(see closing comments of #4995)

**Comment by jangorecki** [comment]
I was just browsing code of PR is question and found this, which nicely illustrate, why you wouldn't want to deal too much with NSE
https://github.com/Rdatatable/data.table/blob/d00f292596d82fd21aac59edc34a9f8b388450f4/R/programming.R#L72-L75
this is `substitute2` to which `[` redirects substitution.

**Comment by ColeMiller1** [comment]
Jan - I answered a comment about using the `env` argument on SO. It feels unnatural not to use the dot alias within the `env` argument. I do not really follow the reason for disallowing it in the `env` argument. 

https://stackoverflow.com/questions/68750548/how-can-i-make-update-by-reference-faster-than-shallow-copy?noredirect=1#comment138169625_68750548

**Comment by jangorecki** [comment]
The reason is very simple: env arg must not be NSE. If you can make dot working without NSE then perfect but I doubt it is possible without introducing many conflicts to dot being used in other packages.
