### ISSUE TITLE
Helpful error could extend to when the symbol is a function

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5014]
We already have a helpful error for accidentally treating a column as a table:

```
DT = data.table(vv = runif(100) > .5)
DT[vv]
# Error in `[.data.table`(DT, vv) : 
#  vv is not found in calling scope but it is a column of type logical. If you wish to select rows where that column contains TRUE, or perhaps that column contains row numbers of itself to select, try DT[(col)], DT[DT$col], or DT[col==TRUE] is particularly clear and is optimized. When the first argument inside DT[...] is a single symbol (e.g. DT[var]), data.table looks for var in calling scope.
```

However this doesn't appear if the culprit column happens to mask a function:

```
setnames(DT, 'vv', 'filter')
DT[filter]
# Error in `[.data.table`(DT, filter) : 
#  i has evaluated to type closure. Expecting logical, integer or double.
```

It would be nice if it's easy to extend the helpful message to such a case.

**Comment by MichaelChirico** [comment]
I'm not sure there's an easy way to do this unfortunately -- the friendly message relies on `eval(isub, parent.frame(), parent.frame())` failing, which won't happen in the case of this issue since `eval()` will find the call symbol. Best we could do is to put this alongside the other check:

```
exists(as.character(isub), envir=parent.frame(), mode="function")
```

Any opinion on whether it'd be useful enough to add this check?

**Comment by ColeMiller1** [comment]
It would be helpful. Wouldn’t implementation be similar to #4660? E.g `if (is.function(i)) stop(...)`

**Comment by MichaelChirico** [comment]
Unfortunately not:

```
is.function(substitute(filter))
# [1] FALSE
```

Seems we have to `get()` the name to find its type.

**Comment by ColeMiller1** [comment]
There are two error messages we are discussing. The second error message of 

> i has evaluated to type ...

happens after `isub` has been evaluated. Based on the title of the issue, I would recommend my suggestion.

The first error gets to the calling scope. I still believe `i` should look in the `data.table` before looking in the `parent.frame`. Expected behavior of example is to use the logical vector to subset `DT`. See also #4255

I do not believe it would be worth checking `get` for this issue. However, we could combine approaches and if `isub` evaluated to a function, we can do additional checks to see if it was a column name. e.g.

```
if (is.function(i))
  if (is.name(isub) && exists(as.character(isub), ...)
else
   ...
```
That way there’s no additional overhead for this infrequent error but users would still get a helpful error.
