### ISSUE TITLE
measure() function not found

### ISSUE THREAD

**Issue by Berghuette** [Rdatatable/data.table#5059]
https://rdatatable.gitlab.io/data.table/articles/datatable-reshape.html
The command
melt(two.iris, measure.vars = measure(part, dim, sep="."))
throws an error in RStudio saying the function is unknown in data.table 1.14.0.

**Comment by tlapak** [comment]
That is because that function will be new in 1.14.2. See news item 9 under new features for 1.14.1 in https://github.com/Rdatatable/data.table/blob/master/NEWS.md

If you want to use it now you can install the current dev version.

In the vignette `measure()` is introduced under the heading "Enhanced (new) functionality". It might be nice to mention in what version it was introduced.

**Comment by MichaelChirico** [comment]
I think the issue will be sufficiently transient that we can close. Thanks!
