### ISSUE TITLE
how to add sf dependencies to GLCI rel-lin

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5274]
Hi @jangorecki. Could you jot down here how to add the dependencies to the GLCI rel-lin job please? I'm happy to follow the steps. Maybe the steps already exist somewhere and if so just a link would be great. Thanks.   There were some previous comments somewhere that the extra dependencies for `sf` would make the image much larger. But I'd like to at least understand how to see what the size is now and how to see what the limit is.

**Comment by jangorecki** [comment]
Just to note that the process has been changed recently in #5086 (and a follow-up commit). Looking at current implementation it seems that it should work fine.
We can see that dependencies are properly pulled to local (other) cran repo in: https://gitlab.com/Rdatatable/data.table/-/jobs/1822303891
It seems that adding sf alone brings 88 extra packages (assuming cache has not been cleared before this job). Before we start digging into it more, it may be good to decide if we really want 89 new packages in the pipeline?

All packages that we use are not part of test images.
They are being installed every time. This ensure they are up to date. Otherwise if any of those packages get a new version then we would have to rebuild images.
Fortunately they are not downloaded every time thanks to GLCI cache. They should be downloaded only when new version is available. We can see in linked job that sf and it's dependencies were automatically downloaded.

**Comment by jangorecki** [comment]
So basically sf requires OS dependencies, on CRAN listed as
```
C++11, GDAL (>= 2.0.1), GEOS (>= 3.4.0), PROJ (>= 4.8.0), sqlite3
```
For me it is a red flag. To make it work we need to make new image just for this single test job, so the image has those OS deps pre-installed.

**Comment by mattdowle** [comment]
> Before we start digging into it more, it may be good to decide if we really want 89 new packages in the pipeline?

That's why I wrote "There were some previous comments somewhere that the extra dependencies for sf would make the image much larger. But I'd like to at least understand how to see what the size is now and how to see what the limit is."  So I was asking for metrics. I don't see how we can decide when I don't know what the problem is that you see. Currently, I'm thinking that 89 new packages is no problem at all. I have over 3,000 locally for revdep testing, including all of `sf`'s dependencies and system dependencies and I'm already doing that locally for many years. I compared the timing of rel-lin before sf was added, and if I'm looking at the right numbers, the job runtime has increased from 15 mins to 25 mins. Which seems fine. Why else might you not want to add 89 packages? I can imagine GL has a size limit for the image which is why I asked about that.

> So basically sf requires OS dependencies, on CRAN listed as `C++11, GDAL (>= 2.0.1), GEOS (>= 3.4.0), PROJ (>= 4.8.0), sqlite3`. For me it is a red flag and would prefer to remove sf from tests.

For me it is a red flag that this is so hard in GLCI. I'm happy to add these dependencies if you give me the general commands to update the image but it seems like you're telling me it is going to be hard or there is some difficulty. I already run other.Rraw routinely locally including `sf`, so can any other data.table-dev, it is in the CRAN_Release.cmd procedures, and users can run other.Rraw too themselves. So if the cost of running other.Rraw on GLCI is really so high, then I would prefer to remove `other.Rraw` being tested on GLCI.

**Comment by jangorecki** [comment]
Adding that is not hard, just apt install command in docker file. The harder part will be maintaining due to the number of dependencies.

All docker images we use can be found in https://gitlab.com/jangorecki/dockerfiles
Instead of adding new dependencies (unrelated to other test jobs) to r-builder image it makes more sense to add image on top of the it, say r-builder-sf. Then to use this image for rel-lin job.

I am not aware of any limit for images, but I think we are not anywhere close to it as I am always trying to keep images as minimal as necessary. Not only because of size but redundant stuff may cover up some issues.

r-builder image is 420mb, size can be checked at https://gitlab.com/jangorecki/dockerfiles/container_registry.

Would you like me to add r-builder-sf?

**Comment by mattdowle** [comment]
> Adding that is not hard, just apt install command in docker file. The harder part will be maintaining due to the number of dependencies.

Do you mean R package dependencies? I thought that the R packages are updated automatically. Or OS dependencies? If you mean OS dependencies doesn't someone have to go into the docker image and run `apt-get update` periodically anyway?  If so, I don't see why more dependencies is more work, since `apt-get update` is one command that updates them all.

> Instead of adding new dependencies (unrelated to other test jobs) to r-builder image it makes more sense to add image on top of r-builder, say r-builder-sf. Then to use this image for rel-lin job.

Why does that make more sense; i.e. what's wrong with adding new dependencies into r-builder?  Are there perhaps no OS dependencies in any of the other.Rraw packages that we test, so `sf` is the first one?

> Would you like me to add r-builder-sf?

What I'd really like, is what I already asked for in the first sentence up-front: "could you jot down here how to add the dependencies to the GLCI rel-lin job please?"   All the commands I use to manage release, revdep checking, and all maintenance are checked in to GitHub under .dev.  I don't have any scripts that are not checked in. So that anybody else can look at the commands, contribute and run them themselves if they wish. That's all I want to do for GLCI maintenance too. I'd like to see the commands and run them myself, at least be able to. I don't know whether adding r-builder-sf is the best way forward or not. I just want to understand why you are saying that for myself.

**Comment by jangorecki** [comment]
I mean OS dependencies. In case if we upgrade ubuntu image to newer version we may be having issues with those extra packages installed from apt. I am generally keeping everything to minimum, i.e. no libxml2-dev (required for xml2).

> Why does that make more sense; i.e. what's wrong with adding new dependencies into r-builder?

I described r-builder jobs as
```
Docker image for building R packages with support for building Rmarkdown and Sweave vignettes, package pdf manual.
Uses Ubuntu 16.04 and OS dependencies required for complete --as-cran check. Uses clean base R environment with no third party packages installed.
```
This image was not really aiming for data.table test jobs in particular (or even data.table package). It is being used there so vignettes and --as-cran can be fully tested.

> Are there perhaps no OS dependencies in any of the other.Rraw packages that we test, so sf is the first one?

Yes, sf is the first one. On clean ubuntu there is git, ssl, curl, vim, and R pkg build related software.

> how to add the dependencies to the GLCI rel-lin job please?

Adding apt install command inside yaml file is not really good way to go because it will keep installing same OS packages on every run of the job. So we need to include those in docker image.

> So that anybody else can look at the commands, contribute and run them themselves if they wish. That's all I want to do for GLCI maintenance too. I'd like to see the commands and run them myself, at least be able to.

So the straight description would be to clone dockerfiles repo and make changes to docker images there. I may add comments about this kind of situation (new OS deps) into [CI readme](https://github.com/Rdatatable/data.table/blob/master/.ci/README.md).

**Comment by mattdowle** [comment]
> In case if we upgrade ubuntu image to newer version we may be having issues with those extra packages installed from apt.

I doubt it. At least, nothing that warrants not adding them.

> I described r-builder jobs as

It doesn't matter what it was described as since the description can be changed to say it includes any OS dependencies for other.Rraw packages. My question remains then: "what's wrong with adding new dependencies into r-builder"?

> Adding apt install command inside yaml file is not really good way to go

I didn't suggest adding commands inside yaml! In fact I wrote above "I'm happy to add these dependencies if you give me the general commands to update the image" and "doesn't someone have to go into the docker image and run apt-get update periodically anyway?"

> So the straight description would be to clone dockerfiles repo and make changes to docker images there.
> I may add comments about this kind of situation (new OS deps) into CI readme.

"may"? Yes I'm asking for the commands to update the docker image so that I can do it. The sticking point appears to be I'm proposing to update the r-builder image and it seems like you don't agree. Adding an extra image on top of the r-builder one is what you propose, but that would be more commands and another image. I know how to clone, commit and push. But I don't know docker.

Meanwhile, we're now on the 7th comment in this thread, I still don't have any commands that I can run, GLCI is still in a broken state, and having GLCI run other.Raw, whilst helpful, isn't beneficial enough to warrant this time. I wrote above: "I already run other.Rraw routinely locally including sf, so can any other data.table-dev, it is in the CRAN_Release.cmd procedures, and users can run other.Rraw too themselves. So if the cost of running other.Rraw on GLCI is really so high, then I would prefer to remove other.Rraw being tested on GLCI".

**Comment by jangorecki** [comment]
>  "what's wrong with adding new dependencies into r-builder"?

because r-builder is not designed for data.table particularly, as said it is better to have r-data.table or r-builder-sf image, so the name match the designation. We can just copy r-builder, add extra deps and call it as we wish it.

> I didn't suggest adding commands inside yaml! 

yes, I know, this is just another way to deal with the problem, but more as a temporary solution due to the overhead.

So to add new image you need basic Dockerfile knowledge. You define source image at the top of the image (FROM command), in this case as r-builder, and then commands that you normally run on such source image to install dependencies: apt update, apt install (RUN command). At the end just `CMD ["R"]`. Normally I don't even remember these 3 commands as I always re-use previous dockerfile.

I see you removed other.Rraw already. I will follow up with documentation update in next days.
