### ISSUE TITLE
patterns function missing

### ISSUE THREAD

**Issue by ylelkes** [Rdatatable/data.table#5277]
With both version 1.14.2 and dev version: Error: 'patterns' is not an exported object from 'namespace:data.table'

**Comment by avimallu** [comment]
`patterns`, AFAIK has never been exported from `data.table`'s namespace. It is meant to be used inside the square brackets, or within the `melt` function. It's unlikely it'll work outside of `data.table` also (because it needs to get the column names from somewhere), but if you are so inclined, use `data.table:::patterns`.

**Comment by andrewrech** [comment]
I was also confused by this, because `patterns` is listed in the reference manual without an indication that it is not exported. Thus, I could not find it with `?patterns`. Normally R packages only list exported functions in the reference manual.

**Comment by MichaelChirico** [comment]
you're absolutely right that the documentation should mention the peculiar nature of patterns().

in fact we export a facsimile version of := as well for the sole purpose of steering users. I guess we should do the same for patterns

**Comment by avimallu** [comment]
@MichaelChirico, could you point me to some documentation (or similar PR) that can help me accomplish this beginner task? Even a link or search term would be helpful.

**Comment by MichaelChirico** [comment]
R/data.table.R has the definition of := towards the bottom and I think man/special-symbols.Rd is an example

**Comment by tdhock** [comment]
same for measure(), it is documented but not exported.
