### ISSUE TITLE
Modification of R constants (rcnst) due to auto indexing

### ISSUE THREAD

**Issue by asardaes** [Rdatatable/data.table#5280]
Hello, one of my packages delegates the main work to `data.table`. Its tests were flagged in [CRAN's `rcnst` checks](https://github.com/kalibera/cran-checks/blob/981f1d3d294ccf3046bd7f5915d29ca265941c6e/rcnst/results/table.express/00check.log), and I *think* I found what triggers it, but it's a bit tricky.

For more context, I was trying to isolate the test(s) that triggered the issue (see [this README](https://raw.githubusercontent.com/kalibera/cran-checks/master/rcnst/README.txt) for information on how to set up `rcnst` checks locally), and even though I did get the same "modified constant" error, it seems that it's not thrown immediately due to one particular test. While experimenting, I started changing the order of my tests and I realized that some were failing the normal `expect_identical` assertions. I found that it was because of this:

```r
lhs <- data.table::data.table(x = rep(c("b", "a", "c"), each = 3),
                              y = c(1, 3, 6),
                              v = 1:9)

# some tests ...

expected <- lhs[!lhs[x == "a"], on = "x"]

# more tests...
```

The call to `lhs[x == "a"]` created an index in place, so some of the subsequent comparisons failed because one of the data tables had an index but the other one didn't. To avoid this, I added this to my tests:

```r
options(datatable.auto.index = FALSE)
```

Surprisingly, that also makes the `rcnst` problem go away, so I wonder if there's something special about that call that triggers a weird modification of the R constant(s).

To elaborate on what I said earlier, even though the error was reproducible with my package's tests, deleting all tests except the one that had this index auto-creation is *not* enough to trigger the problem, it seems that one of the tests that runs after that one makes the `R CMD check` realize that something was changed earlier.

Like I said, I don't have the problem if I disable auto indexing, but you might want to check the corresponding code in case it's doing something wonky on the C side. Or maybe it's a weird interaction with the code that parses `x` and does something because of the negation with `!`?

**Comment by ben-schwen** [comment]
Ty for the report. Your experienced behavior is considered a feature since a subsequent call of `lhs[x == "a"]` will be faster.

Setting the options as you did is the way to go (see also #1422) as a user.

However, for a package relying on this option might not be the best idea since a user who uses your package and `data.table` could simply overwrite it.

The linked readme from mentions R objects flagged by macro MARK_NOT_MUTABLE. Can you check if the error occurs on such elements by inspecting them with `.Internal(inspect(objectname))`

There might also be some interference with other packages you might use under the hood and you can check if one of them is using `MARK_NOT_MUTABLE` with https://github.com/search?q=org%3Acran+MARK_NOT_MUTABLE&type=code

**Comment by asardaes** [comment]
Thanks for the suggestion, I asked in r-lib/rlang#1324 and it seems like `MARK_NOT_MUTABLE` could indeed by applied by them. That's of course problematic for `data.table`, but ignoring `rlang` entirely, if a `data.table` is marked as immutable for whatever reason, shouldn't it be detected? If it were me, I'd probably just throw an error if someone (in this case me) tries to modify an immutable object by reference, but if `data.table` doesn't check that, it could run into `rcnst` problems at some point.

**Comment by tlapak** [comment]
I think the issue is that you are spamming references to the data.table.
