### ISSUE TITLE
Error in .shallow(x, cols = cols, retain.key = TRUE): attempt to set index 0/0 in SET_VECTOR_ELT

### ISSUE THREAD

**Issue by andirey** [Rdatatable/data.table#5303]
I know that it's incorrect to provide an error without code but I have a really strange case. 
My R code is running OK in RStudio.
But gives me an error when I run it in console:
"Error in .shallow(x, cols = cols, retain.key = TRUE): attempt to set index 0/0 in SET_VECTOR_ELT"

What can be the reasons for this one?

Any help is welcome!

**Comment by andrewrech** [comment]
please provide a reproducible example

**Comment by andirey** [comment]
The problem that I can't do it. Code is under NDA. And I can't catch the bug.

Can you explain where and how it can happens?

**Comment by andirey** [comment]
This is really strange case for me as I see this bug only when run code via console mode. In RStudio all works fine. Can you guide me to the package code where this error arise - maybe I can understand the reason from source

**Comment by andirey** [comment]
This bug is "black magic". The same R code can process correctly or incorrectly. Please, check your internal mechanism = there is really a problem with the generation of this error.

**Comment by MichaelChirico** [comment]
https://youtu.be/vgYS-F8opgE

see this video for some ways to better debug your code. we can't help without more information.

**Comment by ben-schwen** [comment]
Since this sounds like some `C boogey` you could try to find out which C function errors at which line, using `debug(.shallow)` and `lldb` or `gdb` see also Jim Hester's tutorial on this [https://youtu.be/R3-IMGyNJY4](https://youtu.be/R3-IMGyNJY4)

You might check upfront if both `R` sessions in RStudio and Terminal refer to the same `R` installation via `R.home()` and same `data.table` version.

My guess would be that you pass some sort of empty `data.table` to shallow.

**Comment by mrbsoftisms** [comment]
Another non-reproducible example:  I run into this error frequently when running `devtools::test()` within RStudio. 

> devtools::test(filter = "verification*")
ℹ Testing action
Starting 2 test processes
✔ | F W S  OK | Context
✔ |         4 | verification-baseline [26.2s]                                                  
✔ |         4 | verification-int2 [25.8s]                                                      
✔ |         4 | verification-int3 [25.6s]                                                      
✔ |         4 | verification-int4 [25.6s]                                                      
✖ | 1       0 | verification-int1 [121.5s]                                                     
──────────────────────────────────────────────────
Error (test-verification-int1.R:17): verification int1
<purrr_error_indexed/rlang_error/error/condition>
Error in `map(.x, .f, ...)`: i In index: 1.
Caused by error in `map()`:
i In index: 5.
i With name: hex.
Caused by error in `.shallow()`:
! attempt to set index 0/0 in SET_VECTOR_ELT

Just re-running the identical test succeeds here but sometimes fails in a different place.  Every test sets its seed.  

> devtools::test(filter = "verification*")
ℹ Testing action
Starting 2 test processes
✔ | F W S  OK | Context
✔ |         4 | verification-baseline [34.4s]                                                  
✔ |         4 | verification-int2 [33.7s]                                                      
✔ |         4 | verification-int3 [32.5s]                                                      
✔ |         4 | verification-int4 [27.6s]                                                      
✔ |         4 | verification-int5 [27.1s]                                                      
✔ |         4 | verification-int6 [27.5s]                                                      
✔ |         4 | verification-lau1 [27.6s]                                                      
✔ |         4 | verification-lau2 [27.6s]                                                      
✔ |         4 | verification-lau3 [28.4s]                                                      
✔ |         4 | verification-int1 [302.6s]                                                     
✔ |         4 | verification-lau4 [40.2s]                                                      
✔ |         4 | verification-lau5 [41.0s]                                                      
✔ |         4 | verification-lau6 [43.4s]                                                      
✔ |         4 | verification-ol1 [27.4s]                                                       
✔ |         4 | verification-ol2 [26.8s]                                                       
✔ |         4 | verification-ol3 [25.7s]                                                       
✔ |         4 | verification-ol4 [26.3s]                                                       
✔ |         4 | verification-ol5 [25.2s]                                                       
✔ |         4 | verification-ol6 [26.5s]                                                                                                                  
══ Results ══════════════════════════════════════════
Duration: 435.8 s
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 76 ]


> sessionInfo()
> R version 4.2.2 (2022-10-31)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Monterey 12.6.3
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] fades_2.4.0    purrr_1.0.1    testthat_3.1.6 shiny_1.7.4    devtools_2.4.5 usethis_2.1.6 
> 
> loaded via a namespace (and not attached):
>   [1] readxl_1.4.2             systemfonts_1.0.4        shinydashboard_0.7.2    
>   [4] crosstalk_1.2.0          listenv_0.9.0            ggplot2_3.4.1           
>   [7] digest_0.6.31            htmltools_0.5.4          fansi_1.0.4             
>  [10] magrittr_2.0.3           memoise_2.0.1            config_0.3.1            
>  [13] openxlsx_4.2.5.2         esquisse_1.1.2           remotes_2.4.2           
>  [16] globals_0.16.2           shinybusy_0.3.1          anytime_0.3.9           
>  [19] prettyunits_1.1.1        colorspace_2.1-0         textshaping_0.3.6       
>  [22] haven_2.5.1              xfun_0.37                dplyr_1.1.0             
>  [25] callr_3.7.3              crayon_1.5.2             settings_0.2.7          
>  [28] jsonlite_1.8.4           roxygen2_7.2.3           zoo_1.8-11              
>  [31] glue_1.6.2               shinyFeedback_0.4.0      RcppCCTZ_0.2.12         
>  [34] gtable_0.3.1             phosphoricons_0.1.2      pkgbuild_1.4.0          
>  [37] shinylogs_0.2.1          scales_1.2.1             miniUI_0.1.1.1          
>  [40] Rcpp_1.0.10              viridisLite_0.4.1        xtable_1.8-4            
>  [43] diffobj_0.3.5            foreign_0.8-84           bit_4.0.5               
>  [46] xopen_1.0.0              profvis_0.3.7            htmlwidgets_1.6.1       
>  [49] RColorBrewer_1.1-3       ellipsis_0.3.2           urlchecker_1.0.1        
>  [52] shinydashboardPlus_2.0.3 pkgconfig_2.0.3          farver_2.1.1            
>  [55] sass_0.4.5               utf8_1.2.3               tidyselect_1.2.0        
>  [58] labeling_0.4.2           rlang_1.0.6              later_1.3.0             
>  [61] munsell_0.5.0            reactR_0.4.4             cellranger_1.1.0        
>  [64] tools_4.2.2              cachem_1.0.6             cli_3.6.0               
>  [67] generics_0.1.3           stringr_1.5.0            fastmap_1.1.0           
>  [70] yaml_2.3.7               ragg_1.2.5               rematch2_2.1.2          
>  [73] processx_3.8.0           knitr_1.42               bit64_4.0.5             
>  [76] fs_1.6.1                 zip_2.2.2                future_1.31.0           
>  [79] reactable_0.4.3          mime_0.12                xml2_1.3.3              
>  [82] brio_1.1.3               compiler_4.2.2           rstudioapi_0.14         
>  [85] datamods_1.4.0           curl_5.0.0               waiter_0.2.5            
>  [88] tibble_3.1.8             bslib_0.4.2              stringi_1.7.12          
>  [91] nanotime_0.3.7           ps_1.7.2                 desc_1.4.2              
>  [94] forcats_1.0.0            lattice_0.20-45          commonmark_1.8.1        
>  [97] shinyjs_2.1.0            vctrs_0.5.2              pillar_1.8.1            
> [100] lifecycle_1.0.3          furrr_0.3.1              jquerylib_0.1.4         
> [103] rcmdcheck_1.4.0          data.table_1.14.6        httpuv_1.6.8            
> [106] R6_2.5.1                 promises_1.2.0.1         rio_0.5.29              
> [109] validate_1.1.1           parallelly_1.34.0        writexl_1.4.2           
> [112] sessioninfo_1.2.2        codetools_0.2-19         pkgload_1.3.2           
> [115] golem_0.3.5              fontawesome_0.5.0        rprojroot_2.0.3         
> [118] shinyWidgets_0.7.6       withr_2.5.0              parallel_4.2.2          
> [121] hms_1.1.2                shinyvalidate_0.1.2      grid_4.2.2              
> [124] tidyr_1.3.0              waldo_0.4.0              attempt_0.3.1

**Comment by santoshbs** [comment]
I have the same issue. Very hard to give a reproducible example.

**Comment by mrbsoftisms** [comment]
Managed to capture a backtrace.  Not running in RStudio.  It's not repeatable.   Seems to be an example of [unsafe use of shallow copy](https://stackoverflow.com/questions/45925482/make-a-shallow-copy-in-data-table#:~:text=You%20can't%20use%20data,or%20arguments%20changing%20in%20future.) and I seem to conjure it occasionally by mutating data frames.    

```
<purrr_error_indexed/rlang_error/error/condition>
Error in `map(.x, .f, ...)`: i In index: 6.
Caused by error in `.shallow()`:
! attempt to set index 0/0 in SET_VECTOR_ELT
Backtrace:
     ▆
  1. ├─fades::runsim_cdrs_r("config-cdrs-r.yml", xp) at test-runsim-cdrs-r.R:4:2
  2. │ └─backend$write_excel(output_file_name) at fades/R/runsim_cdrs_r.R:59:2
  3. │   └─fades (local) get_results_list() at fades/R/backend_excel.R:38:6
  4. │     └─fades (local) set_results_list() at fades/R/backend.R:40:8
  5. │       └─results$combine_ledgers() at fades/R/backend.R:77:8
  6. │         └─purrr::map_dfr(...) at fades/R/results.R:103:8
  7. │           └─purrr::map(.x, .f, ...)
  8. │             └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  9. │               ├─purrr:::with_indexed_errors(...)
 10. │               │ └─base::withCallingHandlers(...)
 11. │               ├─purrr:::call_with_cleanup(...)
 12. │               └─fades (local) .f(.x[[i]], ...)
 13. │                 └─... %>% dplyr::select(-timer) at fades/R/results.R:104:10
 14. ├─dplyr::select(., -timer)
 15. ├─dplyr::mutate(., case = rc$case_number, .before = 1)
 16. ├─dplyr:::mutate.data.frame(., case = rc$case_number, .before = 1)
 17. │ └─dplyr:::mutate_relocate(...)
 18. │   ├─dplyr::relocate(out, all_of(names), .before = !!before, .after = !!after)
 19. │   └─dplyr:::relocate.data.frame(...)
 20. │     └─rlang::set_names(out, names(loc))
 21. │       ├─base::`names<-`(.x, .y)
 22. │       └─data.table:::`names<-.data.table`(.x, .y)
 23. │         └─data.table:::shallow(x)
 24. │           └─data.table:::.shallow(x, cols = cols, retain.key = TRUE)
 25. └─base::.handleSimpleError(...)
 26.   └─purrr (local) h(simpleError(msg, call))
 27.     └─cli::cli_abort(...)
 28.       └─rlang::abort(...)
 ```

Versions R 4.3.0, rlang 1.1.1, dplyr 1.1.3, data.table 1.14.8.

**Comment by jangorecki** [comment]
Does that happen on devel version? There has been many changes in devel

**Comment by jangorecki** [comment]
Does that happen on devel version? There have been many changes in devel

**Comment by mrbsoftisms** [comment]
> Does that happen on devel version? There have been many changes in devel

Unfortunately, yes.  

```

══ Results 
Duration: 975.9 s

── Failed tests
Error (test-class-backend-function.R:16:3): backend function sheets for multiple ORU and cases
<purrr_error_indexed/rlang_error/error/condition>
Error in `map(.x, .f, ...)`: i In index: 3.
Caused by error in `map()`:
i In index: 4.
i With name: dps.
Caused by error in `.shallow()`:
! attempt to set index 0/0 in SET_VECTOR_ELT

Error (test-runsim-e4d.R:4:3): runsim for E4D type
<purrr_error_indexed/rlang_error/error/condition>
Error in `map(.x, .f, ...)`: i In index: 5.
Caused by error in `map()`:
i In index: 5.
i With name: cor_pdui.
Caused by error in `.shallow()`:
! attempt to set index 0/0 in SET_VECTOR_ELT

Error (test-simulation-wps-shiny.R:21:3): backend wps to shiny
<purrr_error_indexed/rlang_error/error/condition>
Error in `map(.x, .f, ...)`: i In index: 1.
Caused by error in `map()`:
i In index: 15.
i With name: htr.
Caused by error in `.shallow()`:
! attempt to set index 0/0 in SET_VECTOR_ELT

Error (test-verification-cdrs-int1.R:17:3): verification cdrs int1
<purrr_error_indexed/rlang_error/error/condition>
Error in `map(.x, .f, ...)`: i In index: 12.
Caused by error in `map()`:
i In index: 6.
i With name: asp.
Caused by error in `.shallow()`:
! attempt to set index 0/0 in SET_VECTOR_ELT

[ FAIL 4 | WARN 0 | SKIP 0 | PASS 14025 ]
```

with

```
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.7

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] data.table_1.14.9 devtools_2.4.5    usethis_2.2.2

loaded via a namespace (and not attached):
 [1] miniUI_0.1.1.1    compiler_4.3.1    crayon_1.5.2      promises_1.2.1
 [5] Rcpp_1.0.11       stringr_1.5.0     callr_3.7.3       later_1.3.1
 [9] fastmap_1.1.1     mime_0.12         R6_2.5.1          curl_5.1.0
[13] htmlwidgets_1.6.2 desc_1.4.2        profvis_0.3.8     rprojroot_2.0.3
[17] shiny_1.7.5.1     rlang_1.1.1       cachem_1.0.8      stringi_1.7.12
[21] httpuv_1.6.11     fs_1.6.3          pkgload_1.3.3     memoise_2.0.1
[25] cli_3.6.1         magrittr_2.0.3    ps_1.7.5          digest_0.6.33
[29] processx_3.8.2    xtable_1.8-4      remotes_2.4.2.1   lifecycle_1.0.3
[33] prettyunits_1.2.0 vctrs_0.6.4       glue_1.6.2        urlchecker_1.0.1
[37] sessioninfo_1.2.2 pkgbuild_1.4.2    purrr_1.0.2       tools_4.3.1
[41] ellipsis_0.3.2    htmltools_0.5.6.1
```

**Comment by sbanville-delfi** [comment]
I have had similar issues, but I am using `parallel::mclapply`. I won't post the details here as they likely won't add to the conversation (unless someone wants them).
It is intermittent, and may give the error a number of successive times, then not do it for a while. I wonder if there is some sort of race condition.

**Comment by ben-schwen** [comment]
@sbanville-delfi Since we do not have a reproducible example yet, your case would be interesting

**Comment by sbanville-delfi** [comment]
> @sbanville-delfi Since we do not have a reproducible example yet, your case would be interesting

@ben-schwen I will try to put together a "simple"ish example to try to reproduce as much as possible (likely only sometimes reproducible), when I find some time.

This is one of those annoying problems that isn't easy to reproduce. I can run my code a bunch of times successfully, have others run it repeatedly successfully, and then the problem pops up seemingly at random. The code I am running is in the context of a larger system, processing confidential data, so I will have to reproduce with some test data.

-Steven

**Comment by jangorecki** [comment]
We will reopen when there will be reproducible example.
