### ISSUE TITLE
set() that does not update any rows should still add cols

### ISSUE THREAD

**Issue by mb706** [Rdatatable/data.table#5409]
I would expect `set(x, i, j, val)` to work similarly to `x[i, j := val]` or `x[i, j] <- val` for integer `i`. However, there is a discrepancy when `i` is `0L`: While `<-` and `:=` add missing columns, `set()` does not.

```r
x <- data.table(a = 1)
x[0L, "b"] <- character(0)
x
#>        a      b
#>    <num> <char>
#> 1:     1   <NA>

x <- data.table(a = 1)
x[0L, b := character(0)]
x
#>        a      b
#>    <num> <char>
#> 1:     1   <NA>
```
vs.
```r
x <- data.table(a = 1)
set(x, 0L, "b", character(0))
x
#>        a
#>    <num>
#> 1:     1
```

## sessionInfo()
```
R version 4.1.3 (2022-03-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora Linux 35 (Thirty Five)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libflexiblas.so.3.2

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8    
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8   
 [7] LC_PAPER=en_US.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.14.3

loaded via a namespace (and not attached):
[1] compiler_4.1.3 tools_4.1.3   
```

**Comment by ben-schwen** [comment]
set of tests
```r
dt = data.table(a=1L)
test(1, set(copy(dt), 0L,          "b", logical(0)), data.table(a=1L, b=NA))
test(1, set(copy(dt), NA_integer_, "b", NA),         data.table(a=1L, b=NA))
test(1, set(copy(dt), NA_integer_, "b", logical(0)), copy(dt)[0L, b := logical(0)])
test(1, set(copy(dt), 0L,          "b", NA),         copy(dt)[NA, b := NA])
```

**Comment by joshhwuu** [comment]
I've been trying to figure this one out. The `0L` case is easy enough to add by changing the condition here to include 0:

https://github.com/Rdatatable/data.table/blob/4e6ad97737fe3bb754ff6ca432848d8fd1fe241f/src/assign.c#L382-L384

But for the `NA_integer_` case, things are a little different. 

AFAIU, when `i` is `NA_integer_`, it isn't a valid entry and is disregarded (`numToDo` is not incremented). If no valid rows are selected and no new columns are being created, we return the `dt` early, which makes sense:

https://github.com/Rdatatable/data.table/blob/4e6ad97737fe3bb754ff6ca432848d8fd1fe241f/src/assign.c#L388-L392

This causes the behavior above as when we pass in `NA` or `0L`, `numToDo = 0`, and since we are calling from `set()`, `newcolnames = NULL` always, causing the operation to return early without creation of the new column.

I figured that this was able to be solved by checking whether we call from `set()` or from within `:=`. Initially I wasn't able to get a way to do this, but I noticed the following:

https://github.com/Rdatatable/data.table/blob/4e6ad97737fe3bb754ff6ca432848d8fd1fe241f/src/assign.c#L404-L413

`:=` never reaches this block, which I found strange as I didn't know that `SEXP cols` from `set()` and from `:=` are different. I thought this was heavily implied as this code block included `set()` specific warnings.

I was able to pass all tests (listed above and old ones) by adding an additional check for `isString(cols)`:

```C
if (!length(newcolnames) && !isString(cols)) {
    *_Last_updated = 0;
    UNPROTECT(protecti);
    return(dt); // all items of rows either 0 or NA. !length(newcolnames) for #759
  }
```
So what I'm wondering is, does `set()` always pass `SEXP cols` as a string while `:=` does not? If so, is this check reliable enough to differentiate from `:=` and `set()`?
