### ISSUE TITLE
Release management and revdep checks

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#5546]
I noticed a new wiki page: https://github.com/Rdatatable/data.table/wiki/Release-management-and-revdep-checks
It is great that @tdhock arranged machine that can do this tedious process faster. Feedback with exact git bisect into is very useful as well.

I am opening this issue to discuss roadmap for revdep checks project.

Firstly I would like wiki to explicitly mention which revdeps are included in the check. Precisely if suggests and enhances are there as well?
I would prefer to run it less frequently but include those as well as they may spot breaking changes/bugs that have been missed by strong revdeps.

I think it make sense to have a blacklist so we can exclude pkgs which are known to raise false positives.

Summary what have changed (new failures) since the previous run will also help.

**Comment by tdhock** [comment]
hi @jangorecki thanks for your interest.
I put the code that I am using in this git repo, https://github.com/tdhock/data.table-revdeps/blob/master/params.R
Revdeps included in check are all, 
```r
deps = tools::package_dependencies(
  "data.table",
  db = avail,  # just CRAN revdeps though (not Bioc) from October 2020
  which="all",
  reverse=TRUE,
  recursive=FALSE
)[[1]]
```
which according to ?package_dependencies means:
```
c("Depends", "Imports", "LinkingTo", "Suggests",
          "Enhances")'.  Character string '"all"' is shorthand for that
          vector, 
```
So yes Suggests and Enhances are there.

At this point I do not see any false positives, which ones are known to you?
My code in https://github.com/tdhock/data.table-revdeps/blob/master/myStatus.R includes a couple of heuristics for suppressing un-interesting differences in check logs:
```r
fun.list <- list(
  replace.tmpfile=function(lines){
    gsub("/tmp/Rtmp.*?/file[a-f0-9]+", "/tmp/RtmpXXX/fileXXX", lines, perl=TRUE)
  },
  replace.tmpdir=function(lines){
    gsub("/tmp/Rtmp.*?/", "/tmp/RtmpXXX/", lines)
  },
  remove.Duration=function(lines){
    gsub("  Duration:.*", "  Duration: IRRELEVANT", lines)
  },
  remove.time=function(lines){
    gsub("  [[].*?[]] ", "[XX:XX:XX]", lines)
  },
  ## single-line parsers above.
  vec.to.string=function(lines){
    paste(lines, collapse="\n")
  },
  ## multi-line string parsers below.
  remove.size=function(string){
    sub(
      "\n[*] checking installed package size.*\n(.*\n)*?[*]",
      "\n*", string, perl=TRUE)
  })
```
so we won't see any false positives for just differences in tmp file directories, or computation times, or package sizes.

I agree what have changed (new failures) since the previous run would be useful, but currently not implemented.

**Comment by jangorecki** [comment]
Good to hear about testing all revdeps, CRAN checks only strong revdeps.

If false positives are not yet there I am pretty sure they will sneak in at some point, but maybe then make sense to add such blacklist.

**Comment by tdhock** [comment]
I implemented the new column, which reports if there is anything new with respect to the previous day's checks.
There are a few revdeps which I can not check, because I have not been able to get symengine to install, so I filed an issue to ask for help: https://github.com/symengine/symengine.R/issues/119

**Comment by tdhock** [comment]
symengine now installs, so we are now able to check all revdeps every day.
There is also a new section with a table that has a row for each significant difference in package checks that has been fixed since the last check, https://github.com/Rdatatable/data.table/wiki/Release-management-and-revdep-checks#significant-differences-fixed-since-last-check so that lets us quickly identify issues that have been fixed and could potentially be closed.

**Comment by jangorecki** [comment]
I think we can close this issue if you believe the process is sufficiently well documented.

**Comment by tdhock** [comment]
great! please file new issues about revdeps in this other repo: https://github.com/tdhock/data.table-revdeps/issues

**Comment by TysonStanley** [comment]
@tdhock we should document that site for the revdeps issues somewhere, potentially in the release script? If that makes sense to you, I'll add it there (and comment out the old code for doing the revdeps).

**Comment by tdhock** [comment]
sure a link from the release script couldn't hurt. there is also a link from the wiki page https://github.com/Rdatatable/data.table/wiki/Release-management-and-revdep-checks and from the reports themselves.
