### ISSUE TITLE
Setting up local dev environment and running the tests (in Docker)

### ISSUE THREAD

**Issue by szabgab** [Rdatatable/data.table#5616]
The README has a wealth of information, but either it assumes something I did not know (not being an R developer) or there are some missing steps in the part explaining the setup of the local development environment and running the tests.

Eventually I figured it out and collected the commands in a [blog post](https://dev.to/szabgab/local-development-environment-for-the-datatable-r-project-5fhb)

If you are interested I'd be happy to send a PR to update the README with the details that I missed (primarily installing dependencies).

**Comment by jangorecki** [comment]
Hello,
If you would happen to be an R developer, and the one that knows something about dependencies, and how to manage them in R, you would know that dependencies you have listed in your blog post are not actually needed.

We even have a CI job called "test-rel-vanilla-lin" which is basically ubuntu + git + ssl + curl + vim + r-base-dev: [dockerfile](https://gitlab.com/jangorecki/dockerfiles/-/tree/master/r-base-dev). I believe it is possible to skip even some of those.

There are flags --no-build-vignettes, --ignore-vignettes, --no-manual. You can use them so you don't need latex, rmarkdown, etc. All the other R packages you listed in your post should be automatically escaped without extra flags, just because they are "Suggested" dependencies, which means they should not be needed to perform package build and check. But beware that many project declare suggested dependencies but does not properly escape their usage (most common case is use of testthat). In data.table we do care about best practices.

Thanks for willing to improve readme, but we don't really want to go into educating users about those things. There are already amazing resources on that matter, the first one to start with is: R's writing R extensions manual: https://cran.r-project.org/doc/manuals/R-exts.html
