### ISSUE TITLE
Downloading data.table with Updated R Studio - Invalid Active Developer Path

### ISSUE THREAD

**Issue by solomondaner** [Rdatatable/data.table#5638]
Whenever Updating R or R Studio on my MacOS Ventura , data.table cannot use parallel computing capabilities. Usually, I would run the following script to delete and redownload and everything would work fine with my existing MakeVars file.

remove.packages("data.table")
install.packages("data.table", type = "source",
                 repos = "https://Rdatatable.gitlab.io/data.table")

However, after updating R Studio this time around, data.table is getting downloaded to a private directory in which the rest of my packages are not stored. I cannot even load the package after and am unsure how to download this from Github.

**Comment by jangorecki** [comment]
I would start by trying to avoid RStudio during Installation process, it is just another layer on top of R which could possibly contribute to the problem. If you confirm that problem is either R or RStudio related, then it's easier to debug. RStudio used to mask install.packages function, not sure how it is now, so you mau try to prefix utils:: or just run R from terminal.

**Comment by solomondaner** [comment]
Thank You,

When running this in R instead of R Studio, I noticed a clear error that I was able to lookup. I had to open the Terminal App and enter:
xcode-select --install

After that, I restarted my computer and ran the above script from R Studio. It worked. Here is the documentation I followed:
https://stackoverflow.com/questions/34053682/fatal-error-invalid-active-developer-path-after-upgrading-r-r-studio

I updated the title of this issue so other users can troubleshoot the same thing.
