### ISSUE TITLE
fread() crashes when reading large csv file

### ISSUE THREAD

**Issue by torkildl** [Rdatatable/data.table#5651]
R version 4.2.3
data.table version 1.14.8

Input file is comma-separated and contains quoted text, numerical variables and NAs.

Error emerged on R 4.0.2. Updating to 4.2.3 and reinstalling data.table did not help.
Experiments with only reading some lines (nrows < 1, 10, 100, 1000) and specifying separator did not help.

read.csv2 can read any number of lines, but is typically markedly slower.

![image](https://github.com/Rdatatable/data.table/assets/9461154/bdfc1168-e733-43c3-9b0d-8fbe62589200)

**Comment by torkildl** [comment]
Not sure I understood what to do, but this is what I get when I read (a different, but also large) file:

![image](https://github.com/Rdatatable/data.table/assets/9461154/c026cb19-cf8f-42c2-bb26-b74807af6a14)

Response is the same across files.

**Comment by jangorecki** [comment]
I am afraid good first step will be to learn how to copy output from terminal. We are not even able to search for a text in the images you are posting here. Not providing easy to digest information (text, code, ideally reproducible, rather than screenshots), is basically limiting number of volunteers that would be willing to assist you in resolving your problem.

**Comment by jangorecki** [comment]
closing for now, can always reopen if we are able to reproduce the problem
