### ISSUE TITLE
[R-Forge #4724] add quote = argument to fread

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#568]
Submitted by: Ben Marwick; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=4724&group_id=240&atid=978)

I love fread for its speed, but I have some huge CSV files that are poorly formed and can't load into R without something like: 

read.csv("my.csv", row.names = NULL, comment.char = "", header = TRUE, 
                  stringsAsFactors = FALSE, colClasses= "character", encoding="utf-8",
                  quote = "")

I can't see an equivalent for fread except a note in the doc that says it's a known issue and not yet implemented. 

I eagerly await the day of the implementation of quote handling!

thanks for all your amazing work on this package,

Ben

**Comment by jangorecki** [comment]
+1

Currently I'm not able to write and fread the following data.table.
I've tried both write.table `qmethod` args, none of them works for fread.
```r
data.table(a = 1:2, b = c('f(c("a","b"))','sum(1,2)'))
#    a             b
# 1: 1 f(c("a","b"))
# 2: 2      sum(1,2)
```

**Comment by arunsrinivasan** [comment]
Closed the wrong issue.. argghhhh

**Comment by weetecklee** [comment]
yes, would certainly like to see quote handling in fread. it will surely help a great deal!  thanks.

**Comment by arunsrinivasan** [comment]
Thanks for the report. `quote = ""` is implemented. Either use that, or wrap your file with `""` around character columns so that `quote = "\""` can then read it properly. See `?fread` quote argument.

**Comment by AbhishekSinghVerma** [comment]
"quote" in still missing data.table vignette under fread command cran.r-project.org/web/packages/data.table/data.table.pdf or in git rdocumentation.org/packages/data.table/versions/1.9.6/topics‌​/…? Is this enhancement slated for 1.9.7 or am I missing something?

**Comment by MichaelChirico** [comment]
1.9.7 is the development version under current release, and yes `quote` is
absent from 1.9.6. there are instructions for installing 1.9.7 on the wiki

On Oct 5, 2016 9:44 AM, "AbhishekSinghVerma" <notifications@github.com>
wrote:

"quote" in still missing data.table vignette under fread command
cran.r-project.org/web/packages/data.table/data.table.pdf or in git
rdocumentation.org/packages/data.table/versions/1.9.6/topics‌​/…? Is this
enhancement slated for 1.9.7 or am I missing something?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rdatatable/data.table/issues/568#issuecomment-251678592>,
or mute the thread

**Comment by jangorecki** [comment]
@AbhishekSinghVerma you can find pretty up to date 1.9.7 fread manual [here](https://jangorecki.gitlab.io/data.table/library/data.table/html/fread.html).
