### ISSUE TITLE
Use selective imports

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#5970]
https://github.com/Rdatatable/data.table/blob/07fd933e7d724d00d292b325da2cb5d79ecbcb77/NAMESPACE#L133

In general it's preferable (perhaps just IMO) to import selectively vs. blanket `import(pkg)`. Blanket imports risk unintended collisions, especially as packages evolve (add+remove functions), though the risk for the case of default packages (methods/utils/stats) is more borderline.

**Comment by Nj221102** [comment]
Hi @MichaelChirico i want to work on this issue , can i get assigned and what can be a good method to know specifically which methods/classes we need to import selectively from the default packages (methods/utils/stats)

**Comment by ben-schwen** [comment]
One way to do this is to grep for each function in a package. You can list all functions from a package with `ls("package:utils")`. With this you can create yourself a regex for searching via `grep`. Then you can grep in the R directory with `grep -E -r -n searchString .`

Note that you might have to use the function name without any brackets since we sometimes assign function aliases like in `fread` with `./fread.R:103:      FUN = if (w==2L) untar else unzip`

You might want to use multiple different search string, e.g. for aliases `paste0("(", paste0(" ", ls("package:utils"), " ", collapse="|"), ")")` and for function calls something like `(download.file\([a-Z]+|capture.output\([a-Z]+)`

**Comment by MichaelChirico** [comment]
I would say it's easier to just remove the import(utils) like and run R CMD check. it should fail and the output will tell you which symbols are not defined anymore.

**Comment by Nj221102** [comment]
> I would say it's easier to just remove the import(utils) line and run R CMD check. it should fail and the output will tell you which symbols are not defined anymore.

thanks :)
