### ISSUE TITLE
test() should have an option to start at certain test

### ISSUE THREAD

**Issue by ben-schwen** [Rdatatable/data.table#6039]
Using `cc()` and `test.data.table()` works like a charm for rapid developing. However, when running `test.data.table()` I often know at which particular test I want to start testing (since this was the test failing before). This might become even more important since our testcase database is growing (or we might come up with a better partitioning into different test files).

**Comment by MichaelChirico** [comment]
I had a similar though recently about only running certain tests. I wonder how slow it would be to do a simple if (!match_pattern) return()

in test and run test 10K times but only run a few. otherwise we need something a bit more involved that may be fraught anyway given how non-hermetic our tests can be.

in the longer run I'd like to make our tests much more modular, main script is way too big
