### ISSUE TITLE
Make plural alternatives as plural-forms messages

### ISSUE THREAD

**Issue by rffontenelle** [Rdatatable/data.table#6194]
Some messages embed plural alternatives e.g. "column(s)" or "column%s" (where %s can be empty "" or "s") and this makes harder for translators to properly translate this message.

Some languages have plural-form expressions far more complex than English e.g. while English alternate between singular or plural, Slovenian has 4 plurals. Even for those that have the same plural-form expression as English, appending multiple "(s)" to denote plural alternative makes harder to read, mainly for screen readers used by people who suffers for visually impairment.

A better solution is to split such messages in plural-forms using ngettext.

Some references https://michaelchirico.github.io/potools/articles/developers.html#plurals and (one personal favorite) https://wiki.gnome.org/TranslationProject/DevGuidelines/Plurals

For me, as Brazilian Portuguese translator, there are cases that I can work around the situation, but there are times I need to add way more "(s)" than the original message. Hence, using plural-forms messages would be much more cleaner.

Here is a non-exhaustive list of messages I found in the source code with such problem:

https://github.com/Rdatatable/data.table/blob/f5a1e09328fef5f8a4c5e225bc5b75ca09700f76/src/assign.c#L394

https://github.com/Rdatatable/data.table/blob/f5a1e09328fef5f8a4c5e225bc5b75ca09700f76/src/rbindlist.c#L57

https://github.com/Rdatatable/data.table/blob/f5a1e09328fef5f8a4c5e225bc5b75ca09700f76/src/utils.c#L289

https://github.com/Rdatatable/data.table/blob/f5a1e09328fef5f8a4c5e225bc5b75ca09700f76/R/data.table.R#L721

https://github.com/Rdatatable/data.table/blob/f5a1e09328fef5f8a4c5e225bc5b75ca09700f76/R/data.table.R#L735

https://github.com/Rdatatable/data.table/blob/f5a1e09328fef5f8a4c5e225bc5b75ca09700f76/R/foverlaps.R#L157

https://github.com/Rdatatable/data.table/blob/f5a1e09328fef5f8a4c5e225bc5b75ca09700f76/R/print.data.table.R#L270-L273

**Comment by MichaelChirico** [comment]
Thanks for tracking these down! Yes please switch to `ngettext()`. So far they haven't been sussed out because Mandarin doesn't really have plural forms, so translating there is easy without using `ngettext()`.

**Comment by MichaelChirico** [comment]
For the C messages, we don't have any `ngettext()` usage there yet, so please ensure we are properly set up to start doing plural translations there:

 1. Make sure the package compiles and can pass tests, obviously :)
 2. Make sure the recommended translation workflow is picking these new strings up

https://github.com/Rdatatable/data.table/blob/de0cf94b0ffb004cb3d6e21187b449f803809931/.dev/CRAN_Release.cmd#L11-L26

At a glance, I don't think it will -- I don't see `ngettext()` mentioned there.

**Comment by aitap** [comment]
A couple more in C code:
https://github.com/Rdatatable/data.table/blob/d2f6e1d97c880f97962763179a2b7c727f96cd59/src/fread.c#L1595
https://github.com/Rdatatable/data.table/blob/d2f6e1d97c880f97962763179a2b7c727f96cd59/src/fwrite.c#L955-L958

**Comment by MichaelChirico** [comment]
This is particularly important for `ru` translation, which has 3 plural forms (Romance languages can usually match English style pluralization, i.e. 2 plural forms, and Chinese has no pluralization).

**Comment by rikivillalba** [comment]
Another case [here](https://github.com/Rdatatable/data.table/blob/8af7b43b07f50f00da793ec67ebdf4e8371b2f65/src/fread.c#L1978)
```
      autoFirstColName = (tt==ncol-1);
      DTWARN(_("Detected %d column names but the data has %d columns (i.e. invalid file). Added %d extra default column name%s\n"), tt, ncol, ncol-tt,
             autoFirstColName ? _(" for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.") : _("s at the end."));
```

Depending on autoFirstColName being != 0 "name" is appended a "s at the end" or the message is expanded in the singular case.

**Comment by MichaelChirico** [comment]
Thanks for flagging these. I also find more complicated cases like:

https://github.com/Rdatatable/data.table/blob/97980d9a0795095e8b32d5bbf315da7e087e39fd/src/frollR.c#L178

I believe allowing _fully proper_ translation of those will require nested `ngettext()`, with a pretty bad impact on code readability. Shall we just leave those as is for now? What do the translators think?

**Comment by rikivillalba** [comment]
https://github.com/Rdatatable/data.table/blob/97980d9a0795095e8b32d5bbf315da7e087e39fd/src/dogroups.c#L449

There are two issues here:
1 - gettext tools like msgmerge complains about `\r` as non portable
2 - %d groups can be 1 group or n groups?

**Comment by MichaelChirico** [comment]
> 1 - gettext tools like msgmerge complain about \r as "non portable"

I thought that might be the case, but that message is in .pot/.po already with no reported issue:

```shell
grep -Er "[^\\][\\]r" po/*.pot
# po/data.table.pot:"\rProcessed %d groups out of %d. %.0f%% done. Time elapsed: %ds. ETA: %ds."
# po/data.table.pot:"\rProcessed %d groups out of %d. %.0f%% done. Time elapsed: %ds. ETA: %ds.\n"
```

Should combine those messages too...

**Comment by aitap** [comment]
A related case (should I create a new issue?) is applying grammatical case to nouns. For example, [here](https://github.com/Rdatatable/data.table/blob/cf05b4a0951958d2b6f9f7a4819e5b2cd851ceca/src/assign.c#L739) "target vector" would be "целево**й** вектор", but [later](https://github.com/Rdatatable/data.table/blob/cf05b4a0951958d2b6f9f7a4819e5b2cd851ceca/src/assign.c#L787) "Assigning factor numbers to target vector" must be "Присваиваю фактор целево**му** вектор**у**". Not that big of a deal; I think that all uses of `targetDesc` in `assign.c` are in the dative case and so can be translated pre-inflected, but I'm not sure this would remain the case for Arabic and Hindi.

Also a problem might be concatenation of messages in `fread.c` [[1](https://github.com/Rdatatable/data.table/blob/cf05b4a0951958d2b6f9f7a4819e5b2cd851ceca/src/fread.c#L446), [2](https://github.com/Rdatatable/data.table/blob/cf05b4a0951958d2b6f9f7a4819e5b2cd851ceca/src/fread.c#L451)], but it doesn't pose a problem for me. Are there languages with very strict word order that would break [this sentence](https://github.com/Rdatatable/data.table/blob/cf05b4a0951958d2b6f9f7a4819e5b2cd851ceca/src/fread.c#L1537)? [This](https://github.com/Rdatatable/data.table/blob/cf05b4a0951958d2b6f9f7a4819e5b2cd851ceca/src/fread.c#L1804), on the other hand, is already slightly broken because `msg` is a full sentence.

**Comment by rikivillalba** [comment]
> I believe allowing _fully proper_ translation of those will require nested `ngettext()`, with a pretty bad impact on code readability. Shall we just leave those as is for now? What do the translators think?

I agree. IMHO such a pursuit for grammatical correcteness must be secondary to simplicity. Also it complicates translation. On the other hand, some messages could be put in a more grammatical number independent form, i.e. instead of "1 item / %d items" one could say "(affected items: %d)", when possible. Sometimes that could be made in the translations directly.

**Comment by MichaelChirico** [comment]
@aitap let's open a separate issue for the fragmented sentences you've identified. indeed languages like Turkish and Japanese often have inverted sentence order that makes translating fragments pretty awkward.

**Comment by MichaelChirico** [comment]
> > I believe allowing _fully proper_ translation of those will require nested `ngettext()`, with a pretty bad impact on code readability. Shall we just leave those as is for now? What do the translators think?
> 
> I agree. IMHO such a pursuit for grammatical correcteness must be secondary to simplicity. Also it complicates translation. On the other hand, some messages could be put in a more grammatical number independent form, i.e. instead of "1 item / %d items" one could say "(affected items: %d)", when possible. Sometimes that could be made in the translations directly.

Sounds great. Yes, let's do that on an individual basis where seen fit then.
