### ISSUE TITLE
[R-Forge #2033] Add by.x and by.y to merge.data.table

### ISSUE THREAD

**Issue by arunsrinivasan** [Rdatatable/data.table#637]
Submitted by: Chris Neff; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=2033&group_id=240&atid=978)

Especially implementing by.x and by.y.

**Comment by gcdnyc** [comment]
i am actually moving back to using data frames instead of data  tables since i need to use merge frequently, and work with lots of datasets with different column names. hopefully this will be enhanced soon, although i see this post from Matt from 3 years ago about this topic:

http://stackoverflow.com/questions/14069796/merging-data-tables-based-on-columns-names

**Comment by jangorecki** [comment]
@gcdnyc a simple wrapper to re-setkey on columns which has to be joined seems to be pretty straightforward.
There are multiple functionalities which are easy do-able in data.table, just not wrapped as single call, see *set operators*, *cross join*. Some PR with those functions are waiting here on github. I believe Matt and Arun wants to incorporate them in the most efficient way with good docs and tests.
If you would develop such wrapper you may drop a link here so others may use/contribute to it.
