### ISSUE TITLE
`:=` and `substitute2` way instead of using `get`. How to proceed?

### ISSUE THREAD

**Issue by iago-pssjd** [Rdatatable/data.table#6391]
I use often the following construction
```r
> v1 = "Petal.Width"
> DT = as.data.table(iris)
> DT[, (v1) := get(v1)*2]
```
which works nicely.

Now, looking at the examples in https://rdatatable.gitlab.io/data.table/articles/datatable-programming.html#retired-interfaces for the retired interface `get`, I try
```r
> DT[, (v1) := v1 * 2, env = list(v1 = v1)]
Error in eval(lhs, parent.frame(), parent.frame()) : 
  object 'Petal.Width' not found
```

What should I do instead?

Thanks!

**Comment by iago-pssjd** [comment]
And a slightly different issue. This is a stupid example, but comes when I need information of another data.table containing the same variable.

```r
> DT[, .(iris[[v1]]), env = list(v1=v1)]
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index <real>
> traceback()
7: (function(x, i, exact) if (is.matrix(i)) as.matrix(x)[[i]] else .subset2(x, 
       i, exact = exact))(x, ..., exact = exact)
6: `[[.data.frame`(iris, Petal.Width)
5: iris[[Petal.Width]]
4: eval(jsub, SDenv, parent.frame())
3: eval(jsub, SDenv, parent.frame())
2: `[.data.table`(DT, , .(iris[[v1]]), env = list(v1 = v1))
1: DT[, .(iris[[v1]]), env = list(v1 = v1)]
```


PD: I do not know why, but if I run a similar example but with another data.table, I get a similar traceback but the second line of the error is distinct:
```r
Error in .subset2(x, i, exact = exact) : 
  recursive indexing failed at level 2
```

**Comment by Anirban166** [comment]
> Now, looking at https://rdatatable.gitlab.io/data.table/articles/datatable-programming.html, in particular to the examples for the retired interface `get`, I try
> 
> ```r
> > DT[, (v1) := v1 * 2, env = list(v1 = v1)]
> Error in eval(lhs, parent.frame(), parent.frame()) : 
>   object 'Petal.Width' not found
> ```

I think the expression `v1 * 2` is getting evaluated before considering the `env` argument in this attempt to create/modify the column in place, or `v1` is still a character string (`'Petal.Width'`) in value and not the numeric vector (`iris$Petal.Width` values) that you would expect. 

Regarding the example in the vignette, it uses `.()` which is slightly different or creates a new `data.table` (allowing `env` to work smoothly for inline calculations), while `:=` here modifies/creates columns and I suppose its internal handling does not allow`env` to substitute variables before the expression is evaluated.

Also, it might be helpful for future readers to point to that particular section of the vignette with a hyperlink: https://rdatatable.gitlab.io/data.table/articles/datatable-programming.html#retired-interfaces

**Comment by rikivillalba** [comment]
In your example `(v1)` is substituted by a "symbol" Petal.Width, not by a string. So the parens are not needed.
This works:
`DT[, v1 := v1 * 2, env = list(v1 = v1)]
`

**Comment by Kamgang-B** [comment]
@iago-pssjd The solution to your problem would be:

`v1 = "Petal.Width"`
`DT = data.table(Petal.Width = c(1, 3, 2), id = 1:3)`

`DT[, .(iris$v1), env = list(v1=v1)]`     
or
`DT[, .(iris[[v1]]), env = list(v1=I(v1))]`  


Even when `v1` does not exist in `DT` (meaning that `DT` and `iris` have no name in common), I don't expect your code to work. If for example `DT = as.data.table(mtcars)`, `v1` will be replaced with `Petal.Width` and your code, translated, will become `DT[, .(iris[[Petal.Width]])]`. It will not work because `substitute2` converts strings into _names_, and there would be no variable named ` Petal.Width` (in the current or enclosing frames). But you can use `iris$v1` since `$` allows a name object or a litteral string as index, and will also work even when the two data.tables contain a variable with the same name as shown above.  (P.S.: I'am using data.table `1.15.4`)

Sometimes it is useful to look at the translated code (using `subsitute2` directly) to understand the issue and how to solve it:

`substitute2(DT[, .(iris[[v1]])], env = list(v1=v1))      --> DT[, .(iris[[Petal.Width]])]`        
`substitute2(DT[, .(iris[[v1]])], env = list(v1=I(v1)))   --> DT[, .(iris[["Petal.Width"]])]`         
`substitute2(DT[, .(iris$v1)], env = list(v1=v1))         --> DT[, .(iris$Petal.Width)]`        

The last two are ok but not the first one.

Reason why having two variables with the same name in two data.tables would not work as expected in your code (either it throws an error or it silently returns a wrong result):     
The error in your example come from the fact that you are actually trying to subset `iris` data at a _deeper level_ than what is actually possible, and this is due to the fact that your code translated into something different from what you intended. 
It translated from `DT[, .(iris[[v1]]), env = list(v1=I(v1))]`  to `DT[, .(iris[[Petal.Width]])]`. Since `Petal.Width` exists in `DT`, it is used as a vector of indices (in `[[`) to subset `iris` data and not as a variable name in `iris`. And since `Petal.Width` is numeric and has length greater than one, the first value will be used as top level index (because you are using `[[`), the second as index one level deeper, etc. (try `iris[[c(2)]]`, `iris[[c(2, 3)]]`, iris[[`c(2, 3, 1)`]] to understand what I mean. The last case will throw an error but first two will work).

**Comment by iago-pssjd** [comment]
@rikivillalba @rikivillalba Thanks for your answers.  My goal is something like the next:
```r
# Prepare data
> DT1 = as.data.table(iris)
> DT2 = as.data.table(iris)
> levels(DT2$Species)
[1] "setosa"     "versicolor" "virginica" 
> DT2[, Species := factor(Species, labels = c("set", "ver", "vir"))]
> levels(DT2$Species)
[1] "set" "ver" "vir"
> levels(DT1$Species)
[1] "setosa"     "versicolor" "virginica" 
> v1 = "Species"

# Attempts taking into account your comments

> DT1[, v1 := factor(v1, labels = levels(DT2[[v1]])), env = list(v1=v1)]
Error in .subset2(x, i, exact = exact) : 
  recursive indexing failed at level 2

> DT1[, v1 := factor(v1, labels = levels(DT2[[v1]])), env = list(v1=I(v1))]
Error in factor("Species", labels = levels(DT2[["Species"]])) : 
  invalid 'labels'; length 3 should be 1 or 1

#What I use and works
> DT1[, (v1) := factor(get(v1), labels = levels(DT2[[v1]]))]
> DT1
     Sepal.Length Sepal.Width Petal.Length Petal.Width Species
            <num>       <num>        <num>       <num>  <fctr>
  1:          5.1         3.5          1.4         0.2     set
  2:          4.9         3.0          1.4         0.2     set
  3:          4.7         3.2          1.3         0.2     set
  4:          4.6         3.1          1.5         0.2     set
  5:          5.0         3.6          1.4         0.2     set
 ---                                                          
146:          6.7         3.0          5.2         2.3     vir
147:          6.3         2.5          5.0         1.9     vir
148:          6.5         3.0          5.2         2.0     vir
149:          6.2         3.4          5.4         2.3     vir
150:          5.9         3.0          5.1         1.8     vir

# and finally another possibility would be to duplicate the variable name as follows:
> DT1 = as.data.table(iris)
> v2=v1
> DT1[, v1 := factor(v1, labels = levels(DT2[[v2]])), env = list(v1=v1)]
> DT1
     Sepal.Length Sepal.Width Petal.Length Petal.Width Species
            <num>       <num>        <num>       <num>  <fctr>
  1:          5.1         3.5          1.4         0.2     set
  2:          4.9         3.0          1.4         0.2     set
  3:          4.7         3.2          1.3         0.2     set
  4:          4.6         3.1          1.5         0.2     set
  5:          5.0         3.6          1.4         0.2     set
 ---                                                          
146:          6.7         3.0          5.2         2.3     vir
147:          6.3         2.5          5.0         1.9     vir
148:          6.5         3.0          5.2         2.0     vir
149:          6.2         3.4          5.4         2.3     vir
150:          5.9         3.0          5.1         1.8     vir

```

**Comment by Kamgang-B** [comment]
Any of the following should solve your problem:

`DT1[, v1 := factor(v1, labels = levels(DT2$v1)), env = list(v1=v1)]`
`DT1[, v1 := factor(v1, labels = levels(DT2$v2)), env = list(v1=v1, v2=I(v1))]`  
`DT1[, v1 := factor(v1, labels = levels(DT2[[v2]])), env = list(v1=v1, v2=I(v1))]`

Note that `$` allows both a name and a literal string (in R by design). So, it's not a data.table specific feature.

**Comment by iago-pssjd** [comment]
@Kamgang-B thanks!

And another I hadn't though before
```r
DT1[, v1 := factor(v1, labels = levels(DT2[,v1])), env = list(v1=v1)]
```
