### ISSUE TITLE
New `showProgress must be TRUE or FALSE` error in testthat tests on cran machines under certain circumstances with dt 1.16.0

### ISSUE THREAD

**Issue by s-fleck** [Rdatatable/data.table#6453]
I've encountered the following issue with one of my packages released on CRAN. It **only happens on the CRAN build machine**, local test runs run fine (even with the most recent data.table version). I assume the problem got introduced in data.table 1.16.0.
It can be reproduced by running the tests via `devtools::check_win_devel()`. 

Because i could only reproduce this on the CRAN build machines, I can't supply easily reproducible code, but you can just check out my repo at this commit and call `devtools::check_win_devel()`:
https://github.com/s-fleck/lgrExtra/commit/caa19377cc4e0c15ad4fda96bc439a1f1b6d0a01
 
## The problem:
`foo[bar < 2, ]` will fail with `showProgress must be TRUE or FALSE`. `foo[bar < 2]` works.

I also encountered some cases, where removing the `,` wasn't possible, e.g.
```
cols = c("col1", "col2")
foo[bar == 1, , cols, with = false]
```

Additionally, setting `options("datatable.showProgress" = FALSE)` inside the testthat tests works as a workaround, but I still wanted to report this problem since it could hint at bigger issues in the implementation.

example error:

```
Backtrace:
      ▆
   1. ├─testthat::expect_true(data.table::is.data.table(app$dt)) at test_AppenderDt.R:20:3
   2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
   3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
   4. ├─data.table::is.data.table(app$dt)
   5. └─lgrExtra (local) `<fn>`()
   6.   ├─private$.data[!is.na(private$.data$.id), ]
   7.   └─data.table:::`[.data.table`(...)
   8.     └─data.table:::stopf("%s must be TRUE or FALSE", "showProgress")
   9.       └─data.table:::raise_condition(...)
  ── Error ('test_AppenderDt.R:57:3'): AppenderDt: works with list columns ───────
  Error in ``[.data.table`(private$.data, !is.na(private$.data$.id), )`: showProgress must be TRUE or FALSE
```

**Comment by s-fleck** [comment]
yikes i guess it's all my fault then. sorry for the bother

**Comment by MichaelChirico** [comment]
FWIW, rather than the setup/teardown code, I would have accomplished that with:

```r
withr::local_options(list(datatable.showProgress = FALSE))
```

At a higher level, though, it's not clear why you have this option in the first place. `fwrite()` and `fread()`, which before 1.16.0 were the only places using this option, also have the same check for `isTRUEorFALSE()`:

https://github.com/Rdatatable/data.table/blob/732761424f1b5ec9970a4c4095e50648e85f2da2/R/fread.R#L26
https://github.com/Rdatatable/data.table/blob/732761424f1b5ec9970a4c4095e50648e85f2da2/R/fwrite.R#L59

That you haven't encountered this error previously just tells us you were never actually using the option before.
