### ISSUE TITLE
Faster implementation for %between%

### ISSUE THREAD

**Issue by sainathadapa** [Rdatatable/data.table#707]
As specified in documentation for the %between% function, the current implementation doesn't use the ordered keys in any way. At-least for the case of numeric column being the key, we can use a simple binary search to make this function much faster.

**Comment by MichaelChirico** [comment]
@brodieG the latter should be quite easy to do...

**Comment by MichaelChirico** [comment]
Perhaps we could add a `keyed` argument to `between` which would return a sequence, and use `%bw%` as an alias for this?

```
between <- function(x, lower, upper, incbounds = TRUE, keyed = FALSE){
  if (keyed){
    seq(from = lower + (!incbounds), to = upper - (!incbounds), by = 1L)
  }
  else {# as before
  }
}
```

And

```
`%bw%` <- function(x, y){
  between(x, y[1L], y[2L], incbounds = TRUE, keyed = TRUE)
}
```

?

**Comment by arunsrinivasan** [comment]
Two improvements here:

1. `%between%` and `between()` are vectorised. It is equivalent to `x >= lower & x <= upper` whether `lower, upper` are both single values are vector of values (recycled if `!= length(x)`).

2. `%inrange%` implements this feature, and also accepts multiple ranges. Here's an example.

```r
require(data.table) # v1.9.7+
set.seed(45L)
ids = apply(matrix(sample(letters, 1e6, TRUE), nrow=1e5), 1, paste, collapse="")
dt = data.table(id = sample(ids, 2e7, TRUE), 
                val1 = sample(100, 1e7, TRUE), 
                val2 = sample(150, 1e7, TRUE))
dt[, c("val1", "val2") := .(pmin(val1, val2), pmax(val1, val2))]
print(object.size(dt), units="Mb") # ~310MB

system.time(ans1 <- dt[val1 %between% c(50, 100)]) # 0.7s
system.time(ans2 <- dt[val1 %inrange% c(50, 100)]) # 0.5s

identical(ans1, ans2) # [1] TRUE
```

`between()` and `inrange()` are true on length-1 `lower, upper` values.

With `inrange`, however, a vector of values to `lower, upper` is not equivalen to `x >= lower & x <= upper`.. It returns all rows where `val1` is inside *any* of the ranges.. This uses the recently implemented non-equi joins.

```r
ivals = list(c(10,30), c(20, 50))
system.time(ans1 <- dt[val1 %inrange% ivals]) # 0.5s

# the equivalent expression with between would be:
system.time(ans2 <- dt[val1 %between% c(10, 20) | val1 %between% c(30, 50)]) # 2.5s

identical(ans1, ans2) # [1] TRUE
```

So that's about **5x speedup** for just two intervals.

Relevant commit for this issue is: https://github.com/Rdatatable/data.table/commit/9cf11c6ed277d7710c4cc24fcd9a03f1b7beca0c

even though this was first implemented as `%anywhere%`, it was completely reimplemented.

**Comment by sainathadapa** [comment]
Thanks!
