### ISSUE TITLE
Unify type of `by` across commands

### ISSUE THREAD

**Issue by matthieugomez** [Rdatatable/data.table#791]
As a beginner in data.table, I find the different syntaxes allowed for the by variable in `setkey`, `setkeyv`, and `unique` confusing

Would not it be more consistent to make these functions accept the same type than `by` in `[`, ie a column or a character for a unique variable and a list of characters for multiple variables?
More precisely, I'd like to be able to do these two things

``` R
setkey(DT,c("V1","V2"))
unique(DT,by=V1)`
```

**Comment by jangorecki** [comment]
I don't agree about unifying interfaces of `"[.data.table"(by=...)`, `setkey` and `unique`. If doing so, then there will be more functions that should be unified as well. Introducing lazy evaluate where it was not used before, like `unique`, is adding extra complexity in the code. IMO the most important is to provide interface that does not depend on lazy evaluation (`setkeyv`, `unique`). Lazy evaluation is important when we want to accept arbitrary expression, like in `"[.data.table"(by=...)`. Otherwise those two extra quotes needed for each character column name are not that big problem, at least comparing to the complexity they introduce.
