### ISSUE TITLE
Syntax of `.SD`

### ISSUE THREAD

**Issue by matthieugomez** [Rdatatable/data.table#815]
- Could  the syntax of .SDcols be made similar to the syntax of `by`? ie  also accept .SDcolds=id or .SDcols=.(id1,id2)
- Could `.` be accepted in the `j` part instead of `.SD` ?In my opinion, such a syntax  would make .SDcols easier to use interactively, and also close to magrittr.
  
  ``` R
  DT[,f(.SD),.SDcols=names(DT)]
  DT[,f(.),.=names(DT)]
  ```

**Comment by arunsrinivasan** [comment]
Not quite sure if this'll be necessary after implementing `a:b`, but have added to 1.9.6

**Comment by arunsrinivasan** [comment]
Thinking a bit more about this, allowing `.SDcols = id` would break existing code where `id` is a variable holding column names.

We'll implement other ways to use `.SDcols` in a much more user-friendly manner. 

Closing this one.

**Comment by MichaelChirico** [comment]
This is related to #1474 and #1475

**Comment by MichaelChirico** [comment]
cc @jangorecki 

I think since this issue we've added plenty of flexibility to `.SDcols` (filter by pattern or column condition). The only convenience left is just about saving two quotation marks, with the cost of maintenance difficulty due to scoping issues.

I think there are some somewhat related ways to extend `.SDcols` but I think we can close this now anyway.
