### ISSUE TITLE
fread - smart parse multiple data sets in one file

### ISSUE THREAD

**Issue by rsaporta** [Rdatatable/data.table#848]
I have a large collection of files, where each file has anywhere between 2 to 5 diffferent datasets written to the same .txt file.  There is no uniformity as to the number of rows in each data set.

Ingesting the files currently involve `grep`ing each one for the header rows, then iterating over the different `skip`/`nrow` combinations for each file. 

It would be amazing -- albeit possibly a tall order -- to have something similar to a `multiple.sets.expected=TRUE` argument in `fread`.

**Comment by mattdowle** [comment]
Just came across this issue.  I doubt we'll ever support returning multiple DT from a single file so closing for clarity.  Picking out one subtable is still supported.  If someone wants to build a package that calls fread iteratively, that's probably best.  Such code could find the offsets of the file to split it up, as if it were separate files.  Then pass offsets into fread which it could jump directly to.  fread's API could be embellished to enable that.  Otherwise it would have to scan from the beginning for each subtable and that wouldn't be efficient.   Or perhaps there's a way to make a file soft pointer which is a subset into another file and then pass that to fread.

Also, latest NEWS (for v1.9.6) contains : 

> The ability to position autostart anywhere inside one of multiple tables in a single file is removed with warning. It used to search upwards from that line to find the start of the table based on a consistent number of columns. People appear to be using `skip="string"` or `skip=nrow` to find the header row exactly, which is retained and simpler. It was too difficult to retain search-upwards-autostart together with skipping blank lines, filling incomplete rows and parallelization. Varying format and height messy header info above the column names is still auto detected and auto skipped.
