### ISSUE TITLE
Support function lag in data.table

### ISSUE THREAD

**Issue by Jureiss** [Rdatatable/data.table#965]
Can include in object data.table lag function?
As example?

lag <- function(var, k) {
if (k > 0) {
    #bring past valeus forward k times
    return(c(rep(NA, k), head(var, -k)))
} else {
    #bring future values backward
    return(c(tail(var, k), rep(NA, -k)))
}
}

x = data.table(a=1:10, dte=sample(seq.Date(from=as.Date("2012-01-20"), to=as.Date("2012-01-30"), by=1),10))
x[, L1_a:=lag(a,1)]

**Comment by arunsrinivasan** [comment]
Implemented `shift()`, which takes `type = "lag"` and `type = "lead"`. The reason is three fold:

1) Avoid name clashes as much as possible.
2) These operations are related, and therefore makes sense to be arguments under a common name.
3) We can add more `types`. For example, I think adding `type = "lagdiff"` might be useful which is equivalent to doing `c(NA, diff(.)`. For example:

```R
x = 1:5
# [1] 1 2 3 4 5
c(NA, diff(x))
# [1] NA  1  1  1  1
c(NA, NA, diff(x, differences=2L)
# [1] NA NA  0  0  0

# If we want both of these in a list, then we  
# should be able to accomplish this as:
shift(x, n=1:2, type="lagdiff")
```
4) Another `type` is *cyclic* shift.
